// Wire assignment code for RCA_AB (32-bit)
// Generated by generate_hpp.py
// Beaver triples needed: 31
// Zero-add gates: 32, Reshared wires: 0
#pragma once
#include <array>
#include "../../../datatypes/k_bitset.hpp"
#include "../../../protocols/Protocols.h"

template <typename DATATYPE>
class RCA_AB_32bit
{
  private:
    static constexpr int BIT_WIDTH = 32;
    using Bitset = sbitset_t<BIT_WIDTH, DATATYPE>;

    Bitset& x;
    Bitset& y;
    Bitset& z;
    int level;
    static constexpr int BeaverTripleCount = 31;
    std::array<triple<DATATYPE>, BeaverTripleCount> triples;
    std::array<DATATYPE, BeaverTripleCount> beavertriples_a{};
    std::array<DATATYPE, BeaverTripleCount> beavertriples_b{};
    std::array<DATATYPE, BeaverTripleCount> beavertriples_c{};

    DATATYPE r63;

    DATATYPE carry_10;
    DATATYPE carry_11;
    DATATYPE carry_12;
    DATATYPE carry_13;
    DATATYPE carry_14;
    DATATYPE carry_15;
    DATATYPE carry_16;
    DATATYPE carry_17;
    DATATYPE carry_18;
    DATATYPE carry_19;
    DATATYPE carry_1;
    DATATYPE carry_20;
    DATATYPE carry_21;
    DATATYPE carry_22;
    DATATYPE carry_23;
    DATATYPE carry_24;
    DATATYPE carry_25;
    DATATYPE carry_26;
    DATATYPE carry_27;
    DATATYPE carry_28;
    DATATYPE carry_29;
    DATATYPE carry_2;
    DATATYPE carry_30;
    DATATYPE carry_31;
    DATATYPE carry_3;
    DATATYPE carry_4;
    DATATYPE carry_5;
    DATATYPE carry_6;
    DATATYPE carry_7;
    DATATYPE carry_8;
    DATATYPE carry_9;
    DATATYPE carry_t_10;
    DATATYPE carry_t_11;
    DATATYPE carry_t_12;
    DATATYPE carry_t_13;
    DATATYPE carry_t_14;
    DATATYPE carry_t_15;
    DATATYPE carry_t_16;
    DATATYPE carry_t_17;
    DATATYPE carry_t_18;
    DATATYPE carry_t_19;
    DATATYPE carry_t_1;
    DATATYPE carry_t_20;
    DATATYPE carry_t_21;
    DATATYPE carry_t_22;
    DATATYPE carry_t_23;
    DATATYPE carry_t_24;
    DATATYPE carry_t_25;
    DATATYPE carry_t_26;
    DATATYPE carry_t_27;
    DATATYPE carry_t_28;
    DATATYPE carry_t_29;
    DATATYPE carry_t_2;
    DATATYPE carry_t_30;
    DATATYPE carry_t_3;
    DATATYPE carry_t_4;
    DATATYPE carry_t_5;
    DATATYPE carry_t_6;
    DATATYPE carry_t_7;
    DATATYPE carry_t_8;
    DATATYPE carry_t_9;
    DATATYPE cx_10;
    DATATYPE cx_11;
    DATATYPE cx_12;
    DATATYPE cx_13;
    DATATYPE cx_14;
    DATATYPE cx_15;
    DATATYPE cx_16;
    DATATYPE cx_17;
    DATATYPE cx_18;
    DATATYPE cx_19;
    DATATYPE cx_1;
    DATATYPE cx_20;
    DATATYPE cx_21;
    DATATYPE cx_22;
    DATATYPE cx_23;
    DATATYPE cx_24;
    DATATYPE cx_25;
    DATATYPE cx_26;
    DATATYPE cx_27;
    DATATYPE cx_28;
    DATATYPE cx_29;
    DATATYPE cx_2;
    DATATYPE cx_30;
    DATATYPE cx_3;
    DATATYPE cx_4;
    DATATYPE cx_5;
    DATATYPE cx_6;
    DATATYPE cx_7;
    DATATYPE cx_8;
    DATATYPE cx_9;
    DATATYPE cy_10;
    DATATYPE cy_10_p;
    DATATYPE cy_11;
    DATATYPE cy_11_p;
    DATATYPE cy_12;
    DATATYPE cy_12_p;
    DATATYPE cy_13;
    DATATYPE cy_13_p;
    DATATYPE cy_14;
    DATATYPE cy_14_p;
    DATATYPE cy_15;
    DATATYPE cy_15_p;
    DATATYPE cy_16;
    DATATYPE cy_16_p;
    DATATYPE cy_17;
    DATATYPE cy_17_p;
    DATATYPE cy_18;
    DATATYPE cy_18_p;
    DATATYPE cy_19;
    DATATYPE cy_19_p;
    DATATYPE cy_1;
    DATATYPE cy_1_p;
    DATATYPE cy_20;
    DATATYPE cy_20_p;
    DATATYPE cy_21;
    DATATYPE cy_21_p;
    DATATYPE cy_22;
    DATATYPE cy_22_p;
    DATATYPE cy_23;
    DATATYPE cy_23_p;
    DATATYPE cy_24;
    DATATYPE cy_24_p;
    DATATYPE cy_25;
    DATATYPE cy_25_p;
    DATATYPE cy_26;
    DATATYPE cy_26_p;
    DATATYPE cy_27;
    DATATYPE cy_27_p;
    DATATYPE cy_28;
    DATATYPE cy_28_p;
    DATATYPE cy_29;
    DATATYPE cy_29_p;
    DATATYPE cy_2;
    DATATYPE cy_2_p;
    DATATYPE cy_30;
    DATATYPE cy_30_p;
    DATATYPE cy_3;
    DATATYPE cy_3_p;
    DATATYPE cy_4;
    DATATYPE cy_4_p;
    DATATYPE cy_5;
    DATATYPE cy_5_p;
    DATATYPE cy_6;
    DATATYPE cy_6_p;
    DATATYPE cy_7;
    DATATYPE cy_7_p;
    DATATYPE cy_8;
    DATATYPE cy_8_p;
    DATATYPE cy_9;
    DATATYPE cy_9_p;
    DATATYPE t_xy_0;
    DATATYPE t_xy_10;
    DATATYPE t_xy_11;
    DATATYPE t_xy_12;
    DATATYPE t_xy_13;
    DATATYPE t_xy_14;
    DATATYPE t_xy_15;
    DATATYPE t_xy_16;
    DATATYPE t_xy_17;
    DATATYPE t_xy_18;
    DATATYPE t_xy_19;
    DATATYPE t_xy_1;
    DATATYPE t_xy_20;
    DATATYPE t_xy_21;
    DATATYPE t_xy_22;
    DATATYPE t_xy_23;
    DATATYPE t_xy_24;
    DATATYPE t_xy_25;
    DATATYPE t_xy_26;
    DATATYPE t_xy_27;
    DATATYPE t_xy_28;
    DATATYPE t_xy_29;
    DATATYPE t_xy_2;
    DATATYPE t_xy_30;
    DATATYPE t_xy_3;
    DATATYPE t_xy_4;
    DATATYPE t_xy_5;
    DATATYPE t_xy_6;
    DATATYPE t_xy_7;
    DATATYPE t_xy_8;
    DATATYPE t_xy_9;
    DATATYPE x_31_p;
    DATATYPE y_31_p;

  public:
    RCA_AB_32bit(Bitset& x_input, Bitset& y_input, Bitset& z_output) : x(x_input), y(y_input), z(z_output), level(0)
    {
        for (int i = 0; i < BeaverTripleCount; ++i)
        {
            triples[i] = retrieveBooleanTriple();
            beavertriples_a[i] = triples[i].a;
            beavertriples_b[i] = triples[i].b;
            beavertriples_c[i] = triples[i].c;
        }
        // Random mask values (shared across mask expressions)
        r63 = getRandomVal(PSELF);

    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 32; }
    bool is_done() const { return level > 31; }

    void step()
    {
        switch(level) {
            case 0:
                z[31] = x[31] ^ y[31];  // z[31]
                t_xy_30 = x[30] ^ y[30];  // t_xy[30]
                t_xy_29 = x[29] ^ y[29];  // t_xy[29]
                t_xy_28 = x[28] ^ y[28];  // t_xy[28]
                t_xy_27 = x[27] ^ y[27];  // t_xy[27]
                t_xy_26 = x[26] ^ y[26];  // t_xy[26]
                t_xy_25 = x[25] ^ y[25];  // t_xy[25]
                t_xy_24 = x[24] ^ y[24];  // t_xy[24]
                t_xy_23 = x[23] ^ y[23];  // t_xy[23]
                t_xy_22 = x[22] ^ y[22];  // t_xy[22]
                t_xy_21 = x[21] ^ y[21];  // t_xy[21]
                t_xy_20 = x[20] ^ y[20];  // t_xy[20]
                t_xy_19 = x[19] ^ y[19];  // t_xy[19]
                t_xy_18 = x[18] ^ y[18];  // t_xy[18]
                t_xy_17 = x[17] ^ y[17];  // t_xy[17]
                t_xy_16 = x[16] ^ y[16];  // t_xy[16]
                t_xy_15 = x[15] ^ y[15];  // t_xy[15]
                t_xy_14 = x[14] ^ y[14];  // t_xy[14]
                t_xy_13 = x[13] ^ y[13];  // t_xy[13]
                t_xy_12 = x[12] ^ y[12];  // t_xy[12]
                t_xy_11 = x[11] ^ y[11];  // t_xy[11]
                t_xy_10 = x[10] ^ y[10];  // t_xy[10]
                t_xy_9 = x[9] ^ y[9];  // t_xy[9]
                t_xy_8 = x[8] ^ y[8];  // t_xy[8]
                t_xy_7 = x[7] ^ y[7];  // t_xy[7]
                t_xy_6 = x[6] ^ y[6];  // t_xy[6]
                t_xy_5 = x[5] ^ y[5];  // t_xy[5]
                t_xy_4 = x[4] ^ y[4];  // t_xy[4]
                t_xy_3 = x[3] ^ y[3];  // t_xy[3]
                t_xy_2 = x[2] ^ y[2];  // t_xy[2]
                t_xy_1 = x[1] ^ y[1];  // t_xy[1]
                t_xy_0 = x[0] ^ y[0];  // t_xy[0]
                x_31_p = x[31].zero_add(beavertriples_a[0]);  // x[31]', mask=a0
                y_31_p = y[31].zero_add(beavertriples_b[0]);  // y[31]', mask=b0
                // and_1: a0=beavertriples_a[0], b0=beavertriples_b[0], c0=beavertriples_c[0], output mask=(a1-f(x[30]))
                carry_31 = x_31_p.prepare_and(y_31_p, FUNC_XOR(beavertriples_a[1], x[30]), beavertriples_c[0]);  // and_1
                carry_31.mask_and_send_dot();
                break;
            case 1:
                carry_31.complete_and();
                z[30] = t_xy_30 ^ carry_31;  // z[30]
                cx_30 = carry_31 ^ x[30];  // cx[30]
                cy_30 = carry_31 ^ y[30];  // cy[30]
                cy_30_p = cy_30.zero_add(beavertriples_b[1]);  // cy[30]', mask=b1
                // and_6: a1=beavertriples_a[1], b1=beavertriples_b[1], c1=beavertriples_c[1], output mask=((a2-f(x[29]))-(a1-f(x[30])))
                carry_t_30 = cx_30.prepare_and(cy_30_p, FUNC_XOR(FUNC_XOR(beavertriples_a[2], x[29]), FUNC_XOR(beavertriples_a[1], x[30])), beavertriples_c[1]);  // and_6
                carry_t_30.mask_and_send_dot();
                break;
            case 2:
                carry_t_30.complete_and();
                carry_30 = carry_t_30 ^ carry_31;  // carry[30]
                z[29] = t_xy_29 ^ carry_30;  // z[29]
                cx_29 = carry_30 ^ x[29];  // cx[29]
                cy_29 = carry_30 ^ y[29];  // cy[29]
                cy_29_p = cy_29.zero_add(beavertriples_b[2]);  // cy[29]', mask=b2
                // and_12: a2=beavertriples_a[2], b2=beavertriples_b[2], c2=beavertriples_c[2], output mask=((a3-f(x[28]))-(a2-f(x[29])))
                carry_t_29 = cx_29.prepare_and(cy_29_p, FUNC_XOR(FUNC_XOR(beavertriples_a[3], x[28]), FUNC_XOR(beavertriples_a[2], x[29])), beavertriples_c[2]);  // and_12
                carry_t_29.mask_and_send_dot();
                break;
            case 3:
                carry_t_29.complete_and();
                carry_29 = carry_t_29 ^ carry_30;  // carry[29]
                z[28] = t_xy_28 ^ carry_29;  // z[28]
                cx_28 = carry_29 ^ x[28];  // cx[28]
                cy_28 = carry_29 ^ y[28];  // cy[28]
                cy_28_p = cy_28.zero_add(beavertriples_b[3]);  // cy[28]', mask=b3
                // and_18: a3=beavertriples_a[3], b3=beavertriples_b[3], c3=beavertriples_c[3], output mask=((a4-f(x[27]))-(a3-f(x[28])))
                carry_t_28 = cx_28.prepare_and(cy_28_p, FUNC_XOR(FUNC_XOR(beavertriples_a[4], x[27]), FUNC_XOR(beavertriples_a[3], x[28])), beavertriples_c[3]);  // and_18
                carry_t_28.mask_and_send_dot();
                break;
            case 4:
                carry_t_28.complete_and();
                carry_28 = carry_t_28 ^ carry_29;  // carry[28]
                z[27] = t_xy_27 ^ carry_28;  // z[27]
                cx_27 = carry_28 ^ x[27];  // cx[27]
                cy_27 = carry_28 ^ y[27];  // cy[27]
                cy_27_p = cy_27.zero_add(beavertriples_b[4]);  // cy[27]', mask=b4
                // and_24: a4=beavertriples_a[4], b4=beavertriples_b[4], c4=beavertriples_c[4], output mask=((a5-f(x[26]))-(a4-f(x[27])))
                carry_t_27 = cx_27.prepare_and(cy_27_p, FUNC_XOR(FUNC_XOR(beavertriples_a[5], x[26]), FUNC_XOR(beavertriples_a[4], x[27])), beavertriples_c[4]);  // and_24
                carry_t_27.mask_and_send_dot();
                break;
            case 5:
                carry_t_27.complete_and();
                carry_27 = carry_t_27 ^ carry_28;  // carry[27]
                z[26] = t_xy_26 ^ carry_27;  // z[26]
                cx_26 = carry_27 ^ x[26];  // cx[26]
                cy_26 = carry_27 ^ y[26];  // cy[26]
                cy_26_p = cy_26.zero_add(beavertriples_b[5]);  // cy[26]', mask=b5
                // and_30: a5=beavertriples_a[5], b5=beavertriples_b[5], c5=beavertriples_c[5], output mask=((a6-f(x[25]))-(a5-f(x[26])))
                carry_t_26 = cx_26.prepare_and(cy_26_p, FUNC_XOR(FUNC_XOR(beavertriples_a[6], x[25]), FUNC_XOR(beavertriples_a[5], x[26])), beavertriples_c[5]);  // and_30
                carry_t_26.mask_and_send_dot();
                break;
            case 6:
                carry_t_26.complete_and();
                carry_26 = carry_t_26 ^ carry_27;  // carry[26]
                z[25] = t_xy_25 ^ carry_26;  // z[25]
                cx_25 = carry_26 ^ x[25];  // cx[25]
                cy_25 = carry_26 ^ y[25];  // cy[25]
                cy_25_p = cy_25.zero_add(beavertriples_b[6]);  // cy[25]', mask=b6
                // and_36: a6=beavertriples_a[6], b6=beavertriples_b[6], c6=beavertriples_c[6], output mask=((a7-f(x[24]))-(a6-f(x[25])))
                carry_t_25 = cx_25.prepare_and(cy_25_p, FUNC_XOR(FUNC_XOR(beavertriples_a[7], x[24]), FUNC_XOR(beavertriples_a[6], x[25])), beavertriples_c[6]);  // and_36
                carry_t_25.mask_and_send_dot();
                break;
            case 7:
                carry_t_25.complete_and();
                carry_25 = carry_t_25 ^ carry_26;  // carry[25]
                z[24] = t_xy_24 ^ carry_25;  // z[24]
                cx_24 = carry_25 ^ x[24];  // cx[24]
                cy_24 = carry_25 ^ y[24];  // cy[24]
                cy_24_p = cy_24.zero_add(beavertriples_b[7]);  // cy[24]', mask=b7
                // and_42: a7=beavertriples_a[7], b7=beavertriples_b[7], c7=beavertriples_c[7], output mask=((a8-f(x[23]))-(a7-f(x[24])))
                carry_t_24 = cx_24.prepare_and(cy_24_p, FUNC_XOR(FUNC_XOR(beavertriples_a[8], x[23]), FUNC_XOR(beavertriples_a[7], x[24])), beavertriples_c[7]);  // and_42
                carry_t_24.mask_and_send_dot();
                break;
            case 8:
                carry_t_24.complete_and();
                carry_24 = carry_t_24 ^ carry_25;  // carry[24]
                z[23] = t_xy_23 ^ carry_24;  // z[23]
                cx_23 = carry_24 ^ x[23];  // cx[23]
                cy_23 = carry_24 ^ y[23];  // cy[23]
                cy_23_p = cy_23.zero_add(beavertriples_b[8]);  // cy[23]', mask=b8
                // and_48: a8=beavertriples_a[8], b8=beavertriples_b[8], c8=beavertriples_c[8], output mask=((a9-f(x[22]))-(a8-f(x[23])))
                carry_t_23 = cx_23.prepare_and(cy_23_p, FUNC_XOR(FUNC_XOR(beavertriples_a[9], x[22]), FUNC_XOR(beavertriples_a[8], x[23])), beavertriples_c[8]);  // and_48
                carry_t_23.mask_and_send_dot();
                break;
            case 9:
                carry_t_23.complete_and();
                carry_23 = carry_t_23 ^ carry_24;  // carry[23]
                z[22] = t_xy_22 ^ carry_23;  // z[22]
                cx_22 = carry_23 ^ x[22];  // cx[22]
                cy_22 = carry_23 ^ y[22];  // cy[22]
                cy_22_p = cy_22.zero_add(beavertriples_b[9]);  // cy[22]', mask=b9
                // and_54: a9=beavertriples_a[9], b9=beavertriples_b[9], c9=beavertriples_c[9], output mask=((a10-f(x[21]))-(a9-f(x[22])))
                carry_t_22 = cx_22.prepare_and(cy_22_p, FUNC_XOR(FUNC_XOR(beavertriples_a[10], x[21]), FUNC_XOR(beavertriples_a[9], x[22])), beavertriples_c[9]);  // and_54
                carry_t_22.mask_and_send_dot();
                break;
            case 10:
                carry_t_22.complete_and();
                carry_22 = carry_t_22 ^ carry_23;  // carry[22]
                z[21] = t_xy_21 ^ carry_22;  // z[21]
                cx_21 = carry_22 ^ x[21];  // cx[21]
                cy_21 = carry_22 ^ y[21];  // cy[21]
                cy_21_p = cy_21.zero_add(beavertriples_b[10]);  // cy[21]', mask=b10
                // and_60: a10=beavertriples_a[10], b10=beavertriples_b[10], c10=beavertriples_c[10], output mask=((a11-f(x[20]))-(a10-f(x[21])))
                carry_t_21 = cx_21.prepare_and(cy_21_p, FUNC_XOR(FUNC_XOR(beavertriples_a[11], x[20]), FUNC_XOR(beavertriples_a[10], x[21])), beavertriples_c[10]);  // and_60
                carry_t_21.mask_and_send_dot();
                break;
            case 11:
                carry_t_21.complete_and();
                carry_21 = carry_t_21 ^ carry_22;  // carry[21]
                z[20] = t_xy_20 ^ carry_21;  // z[20]
                cx_20 = carry_21 ^ x[20];  // cx[20]
                cy_20 = carry_21 ^ y[20];  // cy[20]
                cy_20_p = cy_20.zero_add(beavertriples_b[11]);  // cy[20]', mask=b11
                // and_66: a11=beavertriples_a[11], b11=beavertriples_b[11], c11=beavertriples_c[11], output mask=((a12-f(x[19]))-(a11-f(x[20])))
                carry_t_20 = cx_20.prepare_and(cy_20_p, FUNC_XOR(FUNC_XOR(beavertriples_a[12], x[19]), FUNC_XOR(beavertriples_a[11], x[20])), beavertriples_c[11]);  // and_66
                carry_t_20.mask_and_send_dot();
                break;
            case 12:
                carry_t_20.complete_and();
                carry_20 = carry_t_20 ^ carry_21;  // carry[20]
                z[19] = t_xy_19 ^ carry_20;  // z[19]
                cx_19 = carry_20 ^ x[19];  // cx[19]
                cy_19 = carry_20 ^ y[19];  // cy[19]
                cy_19_p = cy_19.zero_add(beavertriples_b[12]);  // cy[19]', mask=b12
                // and_72: a12=beavertriples_a[12], b12=beavertriples_b[12], c12=beavertriples_c[12], output mask=((a13-f(x[18]))-(a12-f(x[19])))
                carry_t_19 = cx_19.prepare_and(cy_19_p, FUNC_XOR(FUNC_XOR(beavertriples_a[13], x[18]), FUNC_XOR(beavertriples_a[12], x[19])), beavertriples_c[12]);  // and_72
                carry_t_19.mask_and_send_dot();
                break;
            case 13:
                carry_t_19.complete_and();
                carry_19 = carry_t_19 ^ carry_20;  // carry[19]
                z[18] = t_xy_18 ^ carry_19;  // z[18]
                cx_18 = carry_19 ^ x[18];  // cx[18]
                cy_18 = carry_19 ^ y[18];  // cy[18]
                cy_18_p = cy_18.zero_add(beavertriples_b[13]);  // cy[18]', mask=b13
                // and_78: a13=beavertriples_a[13], b13=beavertriples_b[13], c13=beavertriples_c[13], output mask=((a14-f(x[17]))-(a13-f(x[18])))
                carry_t_18 = cx_18.prepare_and(cy_18_p, FUNC_XOR(FUNC_XOR(beavertriples_a[14], x[17]), FUNC_XOR(beavertriples_a[13], x[18])), beavertriples_c[13]);  // and_78
                carry_t_18.mask_and_send_dot();
                break;
            case 14:
                carry_t_18.complete_and();
                carry_18 = carry_t_18 ^ carry_19;  // carry[18]
                z[17] = t_xy_17 ^ carry_18;  // z[17]
                cx_17 = carry_18 ^ x[17];  // cx[17]
                cy_17 = carry_18 ^ y[17];  // cy[17]
                cy_17_p = cy_17.zero_add(beavertriples_b[14]);  // cy[17]', mask=b14
                // and_84: a14=beavertriples_a[14], b14=beavertriples_b[14], c14=beavertriples_c[14], output mask=((a15-f(x[16]))-(a14-f(x[17])))
                carry_t_17 = cx_17.prepare_and(cy_17_p, FUNC_XOR(FUNC_XOR(beavertriples_a[15], x[16]), FUNC_XOR(beavertriples_a[14], x[17])), beavertriples_c[14]);  // and_84
                carry_t_17.mask_and_send_dot();
                break;
            case 15:
                carry_t_17.complete_and();
                carry_17 = carry_t_17 ^ carry_18;  // carry[17]
                z[16] = t_xy_16 ^ carry_17;  // z[16]
                cx_16 = carry_17 ^ x[16];  // cx[16]
                cy_16 = carry_17 ^ y[16];  // cy[16]
                cy_16_p = cy_16.zero_add(beavertriples_b[15]);  // cy[16]', mask=b15
                // and_90: a15=beavertriples_a[15], b15=beavertriples_b[15], c15=beavertriples_c[15], output mask=((a16-f(x[15]))-(a15-f(x[16])))
                carry_t_16 = cx_16.prepare_and(cy_16_p, FUNC_XOR(FUNC_XOR(beavertriples_a[16], x[15]), FUNC_XOR(beavertriples_a[15], x[16])), beavertriples_c[15]);  // and_90
                carry_t_16.mask_and_send_dot();
                break;
            case 16:
                carry_t_16.complete_and();
                carry_16 = carry_t_16 ^ carry_17;  // carry[16]
                z[15] = t_xy_15 ^ carry_16;  // z[15]
                cx_15 = carry_16 ^ x[15];  // cx[15]
                cy_15 = carry_16 ^ y[15];  // cy[15]
                cy_15_p = cy_15.zero_add(beavertriples_b[16]);  // cy[15]', mask=b16
                // and_96: a16=beavertriples_a[16], b16=beavertriples_b[16], c16=beavertriples_c[16], output mask=((a17-f(x[14]))-(a16-f(x[15])))
                carry_t_15 = cx_15.prepare_and(cy_15_p, FUNC_XOR(FUNC_XOR(beavertriples_a[17], x[14]), FUNC_XOR(beavertriples_a[16], x[15])), beavertriples_c[16]);  // and_96
                carry_t_15.mask_and_send_dot();
                break;
            case 17:
                carry_t_15.complete_and();
                carry_15 = carry_t_15 ^ carry_16;  // carry[15]
                z[14] = t_xy_14 ^ carry_15;  // z[14]
                cx_14 = carry_15 ^ x[14];  // cx[14]
                cy_14 = carry_15 ^ y[14];  // cy[14]
                cy_14_p = cy_14.zero_add(beavertriples_b[17]);  // cy[14]', mask=b17
                // and_102: a17=beavertriples_a[17], b17=beavertriples_b[17], c17=beavertriples_c[17], output mask=((a18-f(x[13]))-(a17-f(x[14])))
                carry_t_14 = cx_14.prepare_and(cy_14_p, FUNC_XOR(FUNC_XOR(beavertriples_a[18], x[13]), FUNC_XOR(beavertriples_a[17], x[14])), beavertriples_c[17]);  // and_102
                carry_t_14.mask_and_send_dot();
                break;
            case 18:
                carry_t_14.complete_and();
                carry_14 = carry_t_14 ^ carry_15;  // carry[14]
                z[13] = t_xy_13 ^ carry_14;  // z[13]
                cx_13 = carry_14 ^ x[13];  // cx[13]
                cy_13 = carry_14 ^ y[13];  // cy[13]
                cy_13_p = cy_13.zero_add(beavertriples_b[18]);  // cy[13]', mask=b18
                // and_108: a18=beavertriples_a[18], b18=beavertriples_b[18], c18=beavertriples_c[18], output mask=((a19-f(x[12]))-(a18-f(x[13])))
                carry_t_13 = cx_13.prepare_and(cy_13_p, FUNC_XOR(FUNC_XOR(beavertriples_a[19], x[12]), FUNC_XOR(beavertriples_a[18], x[13])), beavertriples_c[18]);  // and_108
                carry_t_13.mask_and_send_dot();
                break;
            case 19:
                carry_t_13.complete_and();
                carry_13 = carry_t_13 ^ carry_14;  // carry[13]
                z[12] = t_xy_12 ^ carry_13;  // z[12]
                cx_12 = carry_13 ^ x[12];  // cx[12]
                cy_12 = carry_13 ^ y[12];  // cy[12]
                cy_12_p = cy_12.zero_add(beavertriples_b[19]);  // cy[12]', mask=b19
                // and_114: a19=beavertriples_a[19], b19=beavertriples_b[19], c19=beavertriples_c[19], output mask=((a20-f(x[11]))-(a19-f(x[12])))
                carry_t_12 = cx_12.prepare_and(cy_12_p, FUNC_XOR(FUNC_XOR(beavertriples_a[20], x[11]), FUNC_XOR(beavertriples_a[19], x[12])), beavertriples_c[19]);  // and_114
                carry_t_12.mask_and_send_dot();
                break;
            case 20:
                carry_t_12.complete_and();
                carry_12 = carry_t_12 ^ carry_13;  // carry[12]
                z[11] = t_xy_11 ^ carry_12;  // z[11]
                cx_11 = carry_12 ^ x[11];  // cx[11]
                cy_11 = carry_12 ^ y[11];  // cy[11]
                cy_11_p = cy_11.zero_add(beavertriples_b[20]);  // cy[11]', mask=b20
                // and_120: a20=beavertriples_a[20], b20=beavertriples_b[20], c20=beavertriples_c[20], output mask=((a21-f(x[10]))-(a20-f(x[11])))
                carry_t_11 = cx_11.prepare_and(cy_11_p, FUNC_XOR(FUNC_XOR(beavertriples_a[21], x[10]), FUNC_XOR(beavertriples_a[20], x[11])), beavertriples_c[20]);  // and_120
                carry_t_11.mask_and_send_dot();
                break;
            case 21:
                carry_t_11.complete_and();
                carry_11 = carry_t_11 ^ carry_12;  // carry[11]
                z[10] = t_xy_10 ^ carry_11;  // z[10]
                cx_10 = carry_11 ^ x[10];  // cx[10]
                cy_10 = carry_11 ^ y[10];  // cy[10]
                cy_10_p = cy_10.zero_add(beavertriples_b[21]);  // cy[10]', mask=b21
                // and_126: a21=beavertriples_a[21], b21=beavertriples_b[21], c21=beavertriples_c[21], output mask=((a22-f(x[9]))-(a21-f(x[10])))
                carry_t_10 = cx_10.prepare_and(cy_10_p, FUNC_XOR(FUNC_XOR(beavertriples_a[22], x[9]), FUNC_XOR(beavertriples_a[21], x[10])), beavertriples_c[21]);  // and_126
                carry_t_10.mask_and_send_dot();
                break;
            case 22:
                carry_t_10.complete_and();
                carry_10 = carry_t_10 ^ carry_11;  // carry[10]
                z[9] = t_xy_9 ^ carry_10;  // z[9]
                cx_9 = carry_10 ^ x[9];  // cx[9]
                cy_9 = carry_10 ^ y[9];  // cy[9]
                cy_9_p = cy_9.zero_add(beavertriples_b[22]);  // cy[9]', mask=b22
                // and_132: a22=beavertriples_a[22], b22=beavertriples_b[22], c22=beavertriples_c[22], output mask=((a23-f(x[8]))-(a22-f(x[9])))
                carry_t_9 = cx_9.prepare_and(cy_9_p, FUNC_XOR(FUNC_XOR(beavertriples_a[23], x[8]), FUNC_XOR(beavertriples_a[22], x[9])), beavertriples_c[22]);  // and_132
                carry_t_9.mask_and_send_dot();
                break;
            case 23:
                carry_t_9.complete_and();
                carry_9 = carry_t_9 ^ carry_10;  // carry[9]
                z[8] = t_xy_8 ^ carry_9;  // z[8]
                cx_8 = carry_9 ^ x[8];  // cx[8]
                cy_8 = carry_9 ^ y[8];  // cy[8]
                cy_8_p = cy_8.zero_add(beavertriples_b[23]);  // cy[8]', mask=b23
                // and_138: a23=beavertriples_a[23], b23=beavertriples_b[23], c23=beavertriples_c[23], output mask=((a24-f(x[7]))-(a23-f(x[8])))
                carry_t_8 = cx_8.prepare_and(cy_8_p, FUNC_XOR(FUNC_XOR(beavertriples_a[24], x[7]), FUNC_XOR(beavertriples_a[23], x[8])), beavertriples_c[23]);  // and_138
                carry_t_8.mask_and_send_dot();
                break;
            case 24:
                carry_t_8.complete_and();
                carry_8 = carry_t_8 ^ carry_9;  // carry[8]
                z[7] = t_xy_7 ^ carry_8;  // z[7]
                cx_7 = carry_8 ^ x[7];  // cx[7]
                cy_7 = carry_8 ^ y[7];  // cy[7]
                cy_7_p = cy_7.zero_add(beavertriples_b[24]);  // cy[7]', mask=b24
                // and_144: a24=beavertriples_a[24], b24=beavertriples_b[24], c24=beavertriples_c[24], output mask=((a25-f(x[6]))-(a24-f(x[7])))
                carry_t_7 = cx_7.prepare_and(cy_7_p, FUNC_XOR(FUNC_XOR(beavertriples_a[25], x[6]), FUNC_XOR(beavertriples_a[24], x[7])), beavertriples_c[24]);  // and_144
                carry_t_7.mask_and_send_dot();
                break;
            case 25:
                carry_t_7.complete_and();
                carry_7 = carry_t_7 ^ carry_8;  // carry[7]
                z[6] = t_xy_6 ^ carry_7;  // z[6]
                cx_6 = carry_7 ^ x[6];  // cx[6]
                cy_6 = carry_7 ^ y[6];  // cy[6]
                cy_6_p = cy_6.zero_add(beavertriples_b[25]);  // cy[6]', mask=b25
                // and_150: a25=beavertriples_a[25], b25=beavertriples_b[25], c25=beavertriples_c[25], output mask=((a26-f(x[5]))-(a25-f(x[6])))
                carry_t_6 = cx_6.prepare_and(cy_6_p, FUNC_XOR(FUNC_XOR(beavertriples_a[26], x[5]), FUNC_XOR(beavertriples_a[25], x[6])), beavertriples_c[25]);  // and_150
                carry_t_6.mask_and_send_dot();
                break;
            case 26:
                carry_t_6.complete_and();
                carry_6 = carry_t_6 ^ carry_7;  // carry[6]
                z[5] = t_xy_5 ^ carry_6;  // z[5]
                cx_5 = carry_6 ^ x[5];  // cx[5]
                cy_5 = carry_6 ^ y[5];  // cy[5]
                cy_5_p = cy_5.zero_add(beavertriples_b[26]);  // cy[5]', mask=b26
                // and_156: a26=beavertriples_a[26], b26=beavertriples_b[26], c26=beavertriples_c[26], output mask=((a27-f(x[4]))-(a26-f(x[5])))
                carry_t_5 = cx_5.prepare_and(cy_5_p, FUNC_XOR(FUNC_XOR(beavertriples_a[27], x[4]), FUNC_XOR(beavertriples_a[26], x[5])), beavertriples_c[26]);  // and_156
                carry_t_5.mask_and_send_dot();
                break;
            case 27:
                carry_t_5.complete_and();
                carry_5 = carry_t_5 ^ carry_6;  // carry[5]
                z[4] = t_xy_4 ^ carry_5;  // z[4]
                cx_4 = carry_5 ^ x[4];  // cx[4]
                cy_4 = carry_5 ^ y[4];  // cy[4]
                cy_4_p = cy_4.zero_add(beavertriples_b[27]);  // cy[4]', mask=b27
                // and_162: a27=beavertriples_a[27], b27=beavertriples_b[27], c27=beavertriples_c[27], output mask=((a28-f(x[3]))-(a27-f(x[4])))
                carry_t_4 = cx_4.prepare_and(cy_4_p, FUNC_XOR(FUNC_XOR(beavertriples_a[28], x[3]), FUNC_XOR(beavertriples_a[27], x[4])), beavertriples_c[27]);  // and_162
                carry_t_4.mask_and_send_dot();
                break;
            case 28:
                carry_t_4.complete_and();
                carry_4 = carry_t_4 ^ carry_5;  // carry[4]
                z[3] = t_xy_3 ^ carry_4;  // z[3]
                cx_3 = carry_4 ^ x[3];  // cx[3]
                cy_3 = carry_4 ^ y[3];  // cy[3]
                cy_3_p = cy_3.zero_add(beavertriples_b[28]);  // cy[3]', mask=b28
                // and_168: a28=beavertriples_a[28], b28=beavertriples_b[28], c28=beavertriples_c[28], output mask=((a29-f(x[2]))-(a28-f(x[3])))
                carry_t_3 = cx_3.prepare_and(cy_3_p, FUNC_XOR(FUNC_XOR(beavertriples_a[29], x[2]), FUNC_XOR(beavertriples_a[28], x[3])), beavertriples_c[28]);  // and_168
                carry_t_3.mask_and_send_dot();
                break;
            case 29:
                carry_t_3.complete_and();
                carry_3 = carry_t_3 ^ carry_4;  // carry[3]
                z[2] = t_xy_2 ^ carry_3;  // z[2]
                cx_2 = carry_3 ^ x[2];  // cx[2]
                cy_2 = carry_3 ^ y[2];  // cy[2]
                cy_2_p = cy_2.zero_add(beavertriples_b[29]);  // cy[2]', mask=b29
                // and_174: a29=beavertriples_a[29], b29=beavertriples_b[29], c29=beavertriples_c[29], output mask=((a30-f(x[1]))-(a29-f(x[2])))
                carry_t_2 = cx_2.prepare_and(cy_2_p, FUNC_XOR(FUNC_XOR(beavertriples_a[30], x[1]), FUNC_XOR(beavertriples_a[29], x[2])), beavertriples_c[29]);  // and_174
                carry_t_2.mask_and_send_dot();
                break;
            case 30:
                carry_t_2.complete_and();
                carry_2 = carry_t_2 ^ carry_3;  // carry[2]
                z[1] = t_xy_1 ^ carry_2;  // z[1]
                cx_1 = carry_2 ^ x[1];  // cx[1]
                cy_1 = carry_2 ^ y[1];  // cy[1]
                cy_1_p = cy_1.zero_add(beavertriples_b[30]);  // cy[1]', mask=b30
                // and_180: a30=beavertriples_a[30], b30=beavertriples_b[30], c30=beavertriples_c[30], output mask=r63
                carry_t_1 = cx_1.prepare_and(cy_1_p, r63, beavertriples_c[30]);  // and_180
                carry_t_1.mask_and_send_dot();
                break;
            case 31:
                carry_t_1.complete_and();
                carry_1 = carry_t_1 ^ carry_2;  // carry[1]
                z[0] = t_xy_0 ^ carry_1;  // z[0]
                break;
        }
        level++;
    }
};
