FUNCTION_IDENTIFIER=87,187,287
MODELOWNER=P_0
DATAOWNER=P_1
BITLENGTH=32
DATTYPE=32
NUM_INPUTS=1
FRACTIONAL=5
PROTOCOL=4
PRE=1
SKIP_PRE=0
OPTIMIZED_BIT_INJECTION_RELU=0
BIT_INJECTION_PREPROCESSING_OPT=1
A_KNOWN_TO_EVALUATORS_OPT=0
A2B_ONLINE_OPT=0
FUSE_RELU_AVG=0
FUSE_CONV_BN=0
COMPRESS=0
CHEETAH_BOOL_OT_TYPE=2
A_KNOWN=0
