FUNCTION_IDENTIFIER=87,187,287
MODELOWNER=-1
DATAOWNER=-1
BITLENGTH=32
DATTYPE=32
NUM_INPUTS=1
FRACTIONAL=5
PROTOCOL=4
PRE=1
SKIP_PRE=0
OPTIMIZED_BIT_INJECTION_RELU=1
BIT_INJECTION_PREPROCESSING_OPT=1
ROT_PREPROCESSING=1
FUSE_RELU_AVG=1
FUSE_CONV_BN=1
COMPRESS=0,1
CHEETAH_BOOL_OT_TYPE=0
CHEETAH_THREADS=32
A_KNOWN=1
MODELWEIGHTS_KNOWN_DURING_PREPROCESSING=1
PUBLIC_WEIGHTS=0
A_KNOWN_TO_EVALUATORS_OPT=0
A2B_ONLINE_OPT=0
RESHARE_OPT=1
RESHARE_OPT_SIM=1
CHEETAH_CONV_TYPE=0
USE_CUDA_GEMM=2
CHEETAH_GPU=1
CHEETAH_FC_GPU=1
CHEETAH_DISCONNECT=1
