// generated by scripts/circuits/gen_64bit_adders.py: the values of FRACTIONAL with narrow MSB adders at
// BITLENGTH 64 (narrow64/*.hpp), which CUT_FRACTIONAL_BITS_OPT needs there
#pragma once
#define CUT_FRAC_NARROW64_HAVE(F) ((F) == 8 || (F) == 10 || (F) == 12 || (F) == 14 || (F) == 16 || (F) == 18 || (F) == 20 || (F) == 24)
