#pragma once
#include <algorithm>
#include <arpa/inet.h>
#include <bitset>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <functional>
#include <inttypes.h>
#include <iostream>
#include <iterator>
#include <memory>
#include <memory.h>
#include <netdb.h>
#include <new>
#include <pthread.h>
#include <random>
#include <signal.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <thread>
#include <unistd.h>
#include <unordered_map>
#include <vector>

