// Wire assignment code for PPA_MSB_Unsafe_AB family
// Generated by generate_hpp.py
#pragma once
#include <type_traits>
#include "../../../datatypes/k_bitset.hpp"
#include "../../../protocols/Protocols.h"

template <int k, typename Share, typename Enable = void>
class PPA_MSB_Unsafe_AB;

// Wire assignment code for PPA_MSB_Unsafe_AB (8-bit)
// Generated by generate_hpp.py
// Gates: AND2=9, AND3=0, AND4=0, AND_A=0, AND_RESHARED=7, XOR=15, ZERO_ADD=9
// Beaver triples: 9, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 7
template <int k, typename Share>
class PPA_MSB_Unsafe_AB<k, Share, typename std::enable_if<(k == 8)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 8;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& a;
    Bitset& b;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 9;
    triple<DATATYPE> triples[BeaverTripleCount];
    static constexpr int RandomTripleCount = 7;
    RandomMultiplication<DATATYPE> random_triples[RandomTripleCount];

    DATATYPE r19;
    DATATYPE r20;
    DATATYPE r21;
    DATATYPE r22;
    DATATYPE r23;
    DATATYPE r24;
    DATATYPE r25;

    Share g_1;
    Share g_2;
    Share g_3;
    Share g_4;
    Share g_5;
    Share g_6;
    Share g_7;
    Share g_L1_2;
    Share g_L1_4;
    Share g_L1_6;
    Share g_L2_1;
    Share g_L2_4;
    Share g_L3_1;
    Share p_0;
    Share p_1;
    Share p_1_p;
    Share p_1_p_1;
    Share p_2;
    Share p_2_p;
    Share p_2_p_1;
    Share p_3;
    Share p_3_p;
    Share p_4;
    Share p_4_p;
    Share p_4_p_1;
    Share p_5;
    Share p_5_p;
    Share p_6;
    Share p_6_p;
    Share p_7;
    Share p_L1_2;
    Share p_L1_4;
    Share p_L2_1;
    Share pg_L0_2_3;
    Share pg_L0_4_5;
    Share pg_L0_6_7;
    Share pg_L1_1_2;
    Share pg_L1_4_6;
    Share pg_L2_1_4;

  public:
    PPA_MSB_Unsafe_AB(Bitset& a_input, Bitset& b_input, Share& msb_output) : a(a_input), b(b_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            for (int i = 0; i < RandomTripleCount; ++i)
            {
                random_triples[i] = retrieveRandomMultiplication<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r19 = getRandomVal(PSELF);
            r20 = getRandomVal(PSELF);
            r21 = getRandomVal(PSELF);
            r22 = getRandomVal(PSELF);
            r23 = getRandomVal(PSELF);
            r24 = getRandomVal(PSELF);
            r25 = getRandomVal(PSELF);

        }
        a[1].reshare_a(random_triples[0].a);
        b[1].reshare_b(random_triples[0].a);
        a[2].reshare_a(random_triples[1].a);
        b[2].reshare_b(random_triples[1].a);
        a[3].reshare_a(random_triples[2].a);
        b[3].reshare_b(random_triples[2].a);
        a[4].reshare_a(random_triples[3].a);
        b[4].reshare_b(random_triples[3].a);
        a[5].reshare_a(random_triples[4].a);
        b[5].reshare_b(random_triples[4].a);
        a[6].reshare_a(random_triples[5].a);
        b[6].reshare_b(random_triples[5].a);
        a[7].reshare_a(random_triples[6].a);
        b[7].reshare_b(random_triples[6].a);
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 5; }
    bool is_done() const { return level > 4; }

    void step()
    {
        switch(level) {
            case 0:
                p_0 = a[0] ^ b[0];  // p[0]
                p_1 = a[1] ^ b[1];  // p[1]
                p_2 = a[2] ^ b[2];  // p[2]
                p_3 = a[3] ^ b[3];  // p[3]
                p_4 = a[4] ^ b[4];  // p[4]
                p_5 = a[5] ^ b[5];  // p[5]
                p_6 = a[6] ^ b[6];  // p[6]
                p_7 = a[7] ^ b[7];  // p[7]
                p_1_p = p_1.zero_add(triples[6].a);  // p[1]', mask=a13
                p_1_p_1 = p_1.zero_add(triples[7].b);  // p[1]'_1, mask=b14
                p_2_p = p_2.zero_add(triples[3].a);  // p[2]', mask=a10
                p_2_p_1 = p_2.zero_add(triples[4].b);  // p[2]'_1, mask=b11
                p_3_p = p_3.zero_add(triples[4].a);  // p[3]', mask=a11
                p_4_p = p_4.zero_add(triples[1].a);  // p[4]', mask=a8
                p_4_p_1 = p_4.zero_add(triples[2].b);  // p[4]'_1, mask=b9
                p_5_p = p_5.zero_add(triples[2].a);  // p[5]', mask=a9
                p_6_p = p_6.zero_add(triples[0].a);  // p[6]', mask=a7
                // and_5: random_triples[2].a, random_triples[2].b, output mask=b10
                g_3 = a[3].prepare_and_reshared(b[3], triples[3].b, random_triples[2].b);  // and_5
                // and_9: random_triples[4].a, random_triples[4].b, output mask=b8
                g_5 = a[5].prepare_and_reshared(b[5], triples[1].b, random_triples[4].b);  // and_9
                // and_13: random_triples[6].a, random_triples[6].b, output mask=b7
                g_7 = a[7].prepare_and_reshared(b[7], triples[0].b, random_triples[6].b);  // and_13
                // and_19: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=a12
                p_L1_4 = p_5_p.prepare_and(p_4_p_1, triples[5].a, triples[2].c);  // and_19
                // and_22: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=a14
                p_L1_2 = p_3_p.prepare_and(p_2_p_1, triples[7].a, triples[4].c);  // and_22
                break;
            case 1:
                g_3.complete_and();
                g_5.complete_and();
                g_7.complete_and();
                p_L1_4.complete_and();
                p_L1_2.complete_and();
                // and_3: random_triples[1].a, random_triples[1].b, output mask=r20
                g_2 = a[2].prepare_and_reshared(b[2], r20, random_triples[1].b);  // and_3
                // and_20: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=(b13-r20)
                pg_L0_2_3 = p_2_p.prepare_and(g_3, FUNC_XOR(triples[6].b, r20), triples[3].c);  // and_20
                // and_7: random_triples[3].a, random_triples[3].b, output mask=r22
                g_4 = a[4].prepare_and_reshared(b[4], r22, random_triples[3].b);  // and_7
                // and_17: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=(r21-r22)
                pg_L0_4_5 = p_4_p.prepare_and(g_5, FUNC_XOR(r21, r22), triples[1].c);  // and_17
                // and_11: random_triples[5].a, random_triples[5].b, output mask=r19
                g_6 = a[6].prepare_and_reshared(b[6], r19, random_triples[5].b);  // and_11
                // and_15: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=(b12-r19)
                pg_L0_6_7 = p_6_p.prepare_and(g_7, FUNC_XOR(triples[5].b, r19), triples[0].c);  // and_15
                // and_27: a7=triples[7].a, b7=triples[7].b, c7=triples[7].c, output mask=a15
                p_L2_1 = p_L1_2.prepare_and(p_1_p_1, triples[8].a, triples[7].c);  // and_27
                break;
            case 2:
                g_2.complete_and();
                pg_L0_2_3.complete_and();
                g_L1_2 = g_2 ^ pg_L0_2_3;  // g_L1[2]
                g_4.complete_and();
                pg_L0_4_5.complete_and();
                g_L1_4 = g_4 ^ pg_L0_4_5;  // g_L1[4]
                g_6.complete_and();
                pg_L0_6_7.complete_and();
                g_L1_6 = g_6 ^ pg_L0_6_7;  // g_L1[6]
                p_L2_1.complete_and();
                // and_1: random_triples[0].a, random_triples[0].b, output mask=r23
                g_1 = a[1].prepare_and_reshared(b[1], r23, random_triples[0].b);  // and_1
                // and_25: a6=triples[6].a, b6=triples[6].b, c6=triples[6].c, output mask=r24
                pg_L1_1_2 = p_1_p.prepare_and(g_L1_2, r24, triples[6].c);  // and_25
                // and_23: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=(b15-r21)
                pg_L1_4_6 = p_L1_4.prepare_and(g_L1_6, FUNC_XOR(triples[8].b, r21), triples[5].c);  // and_23
                break;
            case 3:
                g_1.complete_and();
                pg_L1_1_2.complete_and();
                g_L2_1 = g_1 ^ pg_L1_1_2;  // g_L2[1]
                pg_L1_4_6.complete_and();
                g_L2_4 = g_L1_4 ^ pg_L1_4_6;  // g_L2[4]
                // and_28: a8=triples[8].a, b8=triples[8].b, c8=triples[8].c, output mask=r25
                pg_L2_1_4 = p_L2_1.prepare_and(g_L2_4, r25, triples[8].c);  // and_28
                break;
            case 4:
                pg_L2_1_4.complete_and();
                g_L3_1 = g_L2_1 ^ pg_L2_1_4;  // g_L3[1]
                msb = p_0 ^ g_L3_1;  // msb
                break;
        }
        level++;
    }
};

// Wire assignment code for PPA_MSB_Unsafe_AB (16-bit)
// Generated by generate_hpp.py
// Gates: AND2=24, AND3=0, AND4=0, AND_A=0, AND_RESHARED=15, XOR=31, ZERO_ADD=24
// Beaver triples: 24, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 15
template <int k, typename Share>
class PPA_MSB_Unsafe_AB<k, Share, typename std::enable_if<(k == 16)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 16;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& a;
    Bitset& b;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 24;
    triple<DATATYPE> triples[BeaverTripleCount];
    static constexpr int RandomTripleCount = 15;
    RandomMultiplication<DATATYPE> random_triples[RandomTripleCount];

    DATATYPE r49;
    DATATYPE r50;
    DATATYPE r51;
    DATATYPE r52;
    DATATYPE r53;
    DATATYPE r54;
    DATATYPE r55;
    DATATYPE r56;
    DATATYPE r57;
    DATATYPE r58;
    DATATYPE r59;
    DATATYPE r60;
    DATATYPE r61;
    DATATYPE r62;
    DATATYPE r63;

    Share g_10;
    Share g_11;
    Share g_12;
    Share g_13;
    Share g_14;
    Share g_15;
    Share g_1;
    Share g_2;
    Share g_3;
    Share g_4;
    Share g_5;
    Share g_6;
    Share g_7;
    Share g_8;
    Share g_9;
    Share g_L1_10;
    Share g_L1_12;
    Share g_L1_14;
    Share g_L1_2;
    Share g_L1_4;
    Share g_L1_6;
    Share g_L1_8;
    Share g_L2_12;
    Share g_L2_1;
    Share g_L2_4;
    Share g_L2_8;
    Share g_L3_1;
    Share g_L3_8;
    Share g_L4_1;
    Share p_0;
    Share p_10;
    Share p_10_p;
    Share p_10_p_1;
    Share p_11;
    Share p_11_p;
    Share p_12;
    Share p_12_p;
    Share p_12_p_1;
    Share p_13;
    Share p_13_p;
    Share p_14;
    Share p_14_p;
    Share p_15;
    Share p_1;
    Share p_1_p;
    Share p_1_p_1;
    Share p_2;
    Share p_2_p;
    Share p_2_p_1;
    Share p_3;
    Share p_3_p;
    Share p_4;
    Share p_4_p;
    Share p_4_p_1;
    Share p_5;
    Share p_5_p;
    Share p_6;
    Share p_6_p;
    Share p_6_p_1;
    Share p_7;
    Share p_7_p;
    Share p_8;
    Share p_8_p;
    Share p_8_p_1;
    Share p_9;
    Share p_9_p;
    Share p_L1_10;
    Share p_L1_12;
    Share p_L1_2;
    Share p_L1_4;
    Share p_L1_4_p;
    Share p_L1_6;
    Share p_L1_8;
    Share p_L1_8_p;
    Share p_L2_1;
    Share p_L2_1_p;
    Share p_L2_4;
    Share p_L2_8;
    Share p_L3_1;
    Share pg_L0_10_11;
    Share pg_L0_12_13;
    Share pg_L0_14_15;
    Share pg_L0_2_3;
    Share pg_L0_4_5;
    Share pg_L0_6_7;
    Share pg_L0_8_9;
    Share pg_L1_1_2;
    Share pg_L1_12_14;
    Share pg_L1_4_6;
    Share pg_L1_8_10;
    Share pg_L2_1_4;
    Share pg_L2_8_12;
    Share pg_L3_1_8;

  public:
    PPA_MSB_Unsafe_AB(Bitset& a_input, Bitset& b_input, Share& msb_output) : a(a_input), b(b_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            for (int i = 0; i < RandomTripleCount; ++i)
            {
                random_triples[i] = retrieveRandomMultiplication<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r49 = getRandomVal(PSELF);
            r50 = getRandomVal(PSELF);
            r51 = getRandomVal(PSELF);
            r52 = getRandomVal(PSELF);
            r53 = getRandomVal(PSELF);
            r54 = getRandomVal(PSELF);
            r55 = getRandomVal(PSELF);
            r56 = getRandomVal(PSELF);
            r57 = getRandomVal(PSELF);
            r58 = getRandomVal(PSELF);
            r59 = getRandomVal(PSELF);
            r60 = getRandomVal(PSELF);
            r61 = getRandomVal(PSELF);
            r62 = getRandomVal(PSELF);
            r63 = getRandomVal(PSELF);

        }
        a[1].reshare_a(random_triples[0].a);
        b[1].reshare_b(random_triples[0].a);
        a[2].reshare_a(random_triples[1].a);
        b[2].reshare_b(random_triples[1].a);
        a[3].reshare_a(random_triples[2].a);
        b[3].reshare_b(random_triples[2].a);
        a[4].reshare_a(random_triples[3].a);
        b[4].reshare_b(random_triples[3].a);
        a[5].reshare_a(random_triples[4].a);
        b[5].reshare_b(random_triples[4].a);
        a[6].reshare_a(random_triples[5].a);
        b[6].reshare_b(random_triples[5].a);
        a[7].reshare_a(random_triples[6].a);
        b[7].reshare_b(random_triples[6].a);
        a[8].reshare_a(random_triples[7].a);
        b[8].reshare_b(random_triples[7].a);
        a[9].reshare_a(random_triples[8].a);
        b[9].reshare_b(random_triples[8].a);
        a[10].reshare_a(random_triples[9].a);
        b[10].reshare_b(random_triples[9].a);
        a[11].reshare_a(random_triples[10].a);
        b[11].reshare_b(random_triples[10].a);
        a[12].reshare_a(random_triples[11].a);
        b[12].reshare_b(random_triples[11].a);
        a[13].reshare_a(random_triples[12].a);
        b[13].reshare_b(random_triples[12].a);
        a[14].reshare_a(random_triples[13].a);
        b[14].reshare_b(random_triples[13].a);
        a[15].reshare_a(random_triples[14].a);
        b[15].reshare_b(random_triples[14].a);
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 6; }
    bool is_done() const { return level > 5; }

    void step()
    {
        switch(level) {
            case 0:
                p_0 = a[0] ^ b[0];  // p[0]
                p_1 = a[1] ^ b[1];  // p[1]
                p_2 = a[2] ^ b[2];  // p[2]
                p_3 = a[3] ^ b[3];  // p[3]
                p_4 = a[4] ^ b[4];  // p[4]
                p_5 = a[5] ^ b[5];  // p[5]
                p_6 = a[6] ^ b[6];  // p[6]
                p_7 = a[7] ^ b[7];  // p[7]
                p_8 = a[8] ^ b[8];  // p[8]
                p_9 = a[9] ^ b[9];  // p[9]
                p_10 = a[10] ^ b[10];  // p[10]
                p_11 = a[11] ^ b[11];  // p[11]
                p_12 = a[12] ^ b[12];  // p[12]
                p_13 = a[13] ^ b[13];  // p[13]
                p_14 = a[14] ^ b[14];  // p[14]
                p_15 = a[15] ^ b[15];  // p[15]
                p_1_p = p_1.zero_add(triples[18].a);  // p[1]', mask=a33
                p_1_p_1 = p_1.zero_add(triples[19].b);  // p[1]'_1, mask=b34
                p_2_p = p_2.zero_add(triples[11].a);  // p[2]', mask=a26
                p_2_p_1 = p_2.zero_add(triples[12].b);  // p[2]'_1, mask=b27
                p_3_p = p_3.zero_add(triples[12].a);  // p[3]', mask=a27
                p_4_p = p_4.zero_add(triples[9].a);  // p[4]', mask=a24
                p_4_p_1 = p_4.zero_add(triples[10].b);  // p[4]'_1, mask=b25
                p_5_p = p_5.zero_add(triples[10].a);  // p[5]', mask=a25
                p_6_p = p_6.zero_add(triples[7].a);  // p[6]', mask=a22
                p_6_p_1 = p_6.zero_add(triples[8].b);  // p[6]'_1, mask=b23
                p_7_p = p_7.zero_add(triples[8].a);  // p[7]', mask=a23
                p_8_p = p_8.zero_add(triples[5].a);  // p[8]', mask=a20
                p_8_p_1 = p_8.zero_add(triples[6].b);  // p[8]'_1, mask=b21
                p_9_p = p_9.zero_add(triples[6].a);  // p[9]', mask=a21
                p_10_p = p_10.zero_add(triples[3].a);  // p[10]', mask=a18
                p_10_p_1 = p_10.zero_add(triples[4].b);  // p[10]'_1, mask=b19
                p_11_p = p_11.zero_add(triples[4].a);  // p[11]', mask=a19
                p_12_p = p_12.zero_add(triples[1].a);  // p[12]', mask=a16
                p_12_p_1 = p_12.zero_add(triples[2].b);  // p[12]'_1, mask=b17
                p_13_p = p_13.zero_add(triples[2].a);  // p[13]', mask=a17
                p_14_p = p_14.zero_add(triples[0].a);  // p[14]', mask=a15
                // and_5: random_triples[2].a, random_triples[2].b, output mask=b26
                g_3 = a[3].prepare_and_reshared(b[3], triples[11].b, random_triples[2].b);  // and_5
                // and_9: random_triples[4].a, random_triples[4].b, output mask=b24
                g_5 = a[5].prepare_and_reshared(b[5], triples[9].b, random_triples[4].b);  // and_9
                // and_13: random_triples[6].a, random_triples[6].b, output mask=b22
                g_7 = a[7].prepare_and_reshared(b[7], triples[7].b, random_triples[6].b);  // and_13
                // and_17: random_triples[8].a, random_triples[8].b, output mask=b20
                g_9 = a[9].prepare_and_reshared(b[9], triples[5].b, random_triples[8].b);  // and_17
                // and_21: random_triples[10].a, random_triples[10].b, output mask=b18
                g_11 = a[11].prepare_and_reshared(b[11], triples[3].b, random_triples[10].b);  // and_21
                // and_25: random_triples[12].a, random_triples[12].b, output mask=b16
                g_13 = a[13].prepare_and_reshared(b[13], triples[1].b, random_triples[12].b);  // and_25
                // and_29: random_triples[14].a, random_triples[14].b, output mask=b15
                g_15 = a[15].prepare_and_reshared(b[15], triples[0].b, random_triples[14].b);  // and_29
                // and_35: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=a28
                p_L1_12 = p_13_p.prepare_and(p_12_p_1, triples[13].a, triples[2].c);  // and_35
                // and_38: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=a30
                p_L1_10 = p_11_p.prepare_and(p_10_p_1, triples[15].a, triples[4].c);  // and_38
                // and_41: a6=triples[6].a, b6=triples[6].b, c6=triples[6].c, output mask=b30
                p_L1_8 = p_9_p.prepare_and(p_8_p_1, triples[15].b, triples[6].c);  // and_41
                // and_44: a8=triples[8].a, b8=triples[8].b, c8=triples[8].c, output mask=a32
                p_L1_6 = p_7_p.prepare_and(p_6_p_1, triples[17].a, triples[8].c);  // and_44
                // and_47: a10=triples[10].a, b10=triples[10].b, c10=triples[10].c, output mask=b32
                p_L1_4 = p_5_p.prepare_and(p_4_p_1, triples[17].b, triples[10].c);  // and_47
                // and_50: a12=triples[12].a, b12=triples[12].b, c12=triples[12].c, output mask=a34
                p_L1_2 = p_3_p.prepare_and(p_2_p_1, triples[19].a, triples[12].c);  // and_50
                break;
            case 1:
                g_3.complete_and();
                g_5.complete_and();
                g_7.complete_and();
                g_9.complete_and();
                g_11.complete_and();
                g_13.complete_and();
                g_15.complete_and();
                p_L1_12.complete_and();
                p_L1_10.complete_and();
                p_L1_8.complete_and();
                p_L1_6.complete_and();
                p_L1_4.complete_and();
                p_L1_2.complete_and();
                p_L1_4_p = p_L1_4.zero_add(triples[16].a);  // p_L1[4]', mask=a31
                p_L1_8_p = p_L1_8.zero_add(triples[14].a);  // p_L1[8]', mask=a29
                // and_3: random_triples[1].a, random_triples[1].b, output mask=r52
                g_2 = a[2].prepare_and_reshared(b[2], r52, random_triples[1].b);  // and_3
                // and_48: a11=triples[11].a, b11=triples[11].b, c11=triples[11].c, output mask=(b33-r52)
                pg_L0_2_3 = p_2_p.prepare_and(g_3, FUNC_XOR(triples[18].b, r52), triples[11].c);  // and_48
                // and_7: random_triples[3].a, random_triples[3].b, output mask=r56
                g_4 = a[4].prepare_and_reshared(b[4], r56, random_triples[3].b);  // and_7
                // and_45: a9=triples[9].a, b9=triples[9].b, c9=triples[9].c, output mask=(r55-r56)
                pg_L0_4_5 = p_4_p.prepare_and(g_5, FUNC_XOR(r55, r56), triples[9].c);  // and_45
                // and_11: random_triples[5].a, random_triples[5].b, output mask=r51
                g_6 = a[6].prepare_and_reshared(b[6], r51, random_triples[5].b);  // and_11
                // and_42: a7=triples[7].a, b7=triples[7].b, c7=triples[7].c, output mask=(b31-r51)
                pg_L0_6_7 = p_6_p.prepare_and(g_7, FUNC_XOR(triples[16].b, r51), triples[7].c);  // and_42
                // and_15: random_triples[7].a, random_triples[7].b, output mask=r59
                g_8 = a[8].prepare_and_reshared(b[8], r59, random_triples[7].b);  // and_15
                // and_39: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=(r58-r59)
                pg_L0_8_9 = p_8_p.prepare_and(g_9, FUNC_XOR(r58, r59), triples[5].c);  // and_39
                // and_19: random_triples[9].a, random_triples[9].b, output mask=r50
                g_10 = a[10].prepare_and_reshared(b[10], r50, random_triples[9].b);  // and_19
                // and_36: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=(b29-r50)
                pg_L0_10_11 = p_10_p.prepare_and(g_11, FUNC_XOR(triples[14].b, r50), triples[3].c);  // and_36
                // and_23: random_triples[11].a, random_triples[11].b, output mask=r54
                g_12 = a[12].prepare_and_reshared(b[12], r54, random_triples[11].b);  // and_23
                // and_33: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=(r53-r54)
                pg_L0_12_13 = p_12_p.prepare_and(g_13, FUNC_XOR(r53, r54), triples[1].c);  // and_33
                // and_27: random_triples[13].a, random_triples[13].b, output mask=r49
                g_14 = a[14].prepare_and_reshared(b[14], r49, random_triples[13].b);  // and_27
                // and_31: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=(b28-r49)
                pg_L0_14_15 = p_14_p.prepare_and(g_15, FUNC_XOR(triples[13].b, r49), triples[0].c);  // and_31
                // and_55: a15=triples[15].a, b15=triples[15].b, c15=triples[15].c, output mask=a35
                p_L2_8 = p_L1_10.prepare_and(p_L1_8, triples[20].a, triples[15].c);  // and_55
                // and_58: a17=triples[17].a, b17=triples[17].b, c17=triples[17].c, output mask=a37
                p_L2_4 = p_L1_6.prepare_and(p_L1_4, triples[22].a, triples[17].c);  // and_58
                // and_61: a19=triples[19].a, b19=triples[19].b, c19=triples[19].c, output mask=b37
                p_L2_1 = p_L1_2.prepare_and(p_1_p_1, triples[22].b, triples[19].c);  // and_61
                break;
            case 2:
                g_2.complete_and();
                pg_L0_2_3.complete_and();
                g_L1_2 = g_2 ^ pg_L0_2_3;  // g_L1[2]
                g_4.complete_and();
                pg_L0_4_5.complete_and();
                g_L1_4 = g_4 ^ pg_L0_4_5;  // g_L1[4]
                g_6.complete_and();
                pg_L0_6_7.complete_and();
                g_L1_6 = g_6 ^ pg_L0_6_7;  // g_L1[6]
                g_8.complete_and();
                pg_L0_8_9.complete_and();
                g_L1_8 = g_8 ^ pg_L0_8_9;  // g_L1[8]
                g_10.complete_and();
                pg_L0_10_11.complete_and();
                g_L1_10 = g_10 ^ pg_L0_10_11;  // g_L1[10]
                g_12.complete_and();
                pg_L0_12_13.complete_and();
                g_L1_12 = g_12 ^ pg_L0_12_13;  // g_L1[12]
                g_14.complete_and();
                pg_L0_14_15.complete_and();
                g_L1_14 = g_14 ^ pg_L0_14_15;  // g_L1[14]
                p_L2_8.complete_and();
                p_L2_4.complete_and();
                p_L2_1.complete_and();
                p_L2_1_p = p_L2_1.zero_add(triples[21].a);  // p_L2[1]', mask=a36
                // and_1: random_triples[0].a, random_triples[0].b, output mask=r60
                g_1 = a[1].prepare_and_reshared(b[1], r60, random_triples[0].b);  // and_1
                // and_59: a18=triples[18].a, b18=triples[18].b, c18=triples[18].c, output mask=r61
                pg_L1_1_2 = p_1_p.prepare_and(g_L1_2, r61, triples[18].c);  // and_59
                // and_51: a13=triples[13].a, b13=triples[13].b, c13=triples[13].c, output mask=(b35-r53)
                pg_L1_12_14 = p_L1_12.prepare_and(g_L1_14, FUNC_XOR(triples[20].b, r53), triples[13].c);  // and_51
                // and_53: a14=triples[14].a, b14=triples[14].b, c14=triples[14].c, output mask=(r57-r58)
                pg_L1_8_10 = p_L1_8_p.prepare_and(g_L1_10, FUNC_XOR(r57, r58), triples[14].c);  // and_53
                // and_56: a16=triples[16].a, b16=triples[16].b, c16=triples[16].c, output mask=(b36-r55)
                pg_L1_4_6 = p_L1_4_p.prepare_and(g_L1_6, FUNC_XOR(triples[21].b, r55), triples[16].c);  // and_56
                // and_66: a22=triples[22].a, b22=triples[22].b, c22=triples[22].c, output mask=a38
                p_L3_1 = p_L2_4.prepare_and(p_L2_1, triples[23].a, triples[22].c);  // and_66
                break;
            case 3:
                g_1.complete_and();
                pg_L1_1_2.complete_and();
                g_L2_1 = g_1 ^ pg_L1_1_2;  // g_L2[1]
                pg_L1_12_14.complete_and();
                pg_L1_8_10.complete_and();
                pg_L1_4_6.complete_and();
                p_L3_1.complete_and();
                g_L2_4 = g_L1_4 ^ pg_L1_4_6;  // g_L2[4]
                g_L2_8 = g_L1_8 ^ pg_L1_8_10;  // g_L2[8]
                g_L2_12 = g_L1_12 ^ pg_L1_12_14;  // g_L2[12]
                // and_62: a20=triples[20].a, b20=triples[20].b, c20=triples[20].c, output mask=(b38-r57)
                pg_L2_8_12 = p_L2_8.prepare_and(g_L2_12, FUNC_XOR(triples[23].b, r57), triples[20].c);  // and_62
                // and_64: a21=triples[21].a, b21=triples[21].b, c21=triples[21].c, output mask=r62
                pg_L2_1_4 = p_L2_1_p.prepare_and(g_L2_4, r62, triples[21].c);  // and_64
                break;
            case 4:
                pg_L2_8_12.complete_and();
                pg_L2_1_4.complete_and();
                g_L3_1 = g_L2_1 ^ pg_L2_1_4;  // g_L3[1]
                g_L3_8 = g_L2_8 ^ pg_L2_8_12;  // g_L3[8]
                // and_67: a23=triples[23].a, b23=triples[23].b, c23=triples[23].c, output mask=r63
                pg_L3_1_8 = p_L3_1.prepare_and(g_L3_8, r63, triples[23].c);  // and_67
                break;
            case 5:
                pg_L3_1_8.complete_and();
                g_L4_1 = g_L3_1 ^ pg_L3_1_8;  // g_L4[1]
                msb = p_0 ^ g_L4_1;  // msb
                break;
        }
        level++;
    }
};

// Wire assignment code for PPA_MSB_Unsafe_AB (32-bit)
// Generated by generate_hpp.py
// Gates: AND2=55, AND3=0, AND4=0, AND_A=0, AND_RESHARED=31, XOR=63, ZERO_ADD=55
// Beaver triples: 55, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 31
template <int k, typename Share>
class PPA_MSB_Unsafe_AB<k, Share, typename std::enable_if<(k == 32)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 32;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& a;
    Bitset& b;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 55;
    triple<DATATYPE> triples[BeaverTripleCount];
    static constexpr int RandomTripleCount = 31;
    RandomMultiplication<DATATYPE> random_triples[RandomTripleCount];

    DATATYPE r111;
    DATATYPE r112;
    DATATYPE r113;
    DATATYPE r114;
    DATATYPE r115;
    DATATYPE r116;
    DATATYPE r117;
    DATATYPE r118;
    DATATYPE r119;
    DATATYPE r120;
    DATATYPE r121;
    DATATYPE r122;
    DATATYPE r123;
    DATATYPE r124;
    DATATYPE r125;
    DATATYPE r126;
    DATATYPE r127;
    DATATYPE r128;
    DATATYPE r129;
    DATATYPE r130;
    DATATYPE r131;
    DATATYPE r132;
    DATATYPE r133;
    DATATYPE r134;
    DATATYPE r135;
    DATATYPE r136;
    DATATYPE r137;
    DATATYPE r138;
    DATATYPE r139;
    DATATYPE r140;
    DATATYPE r141;

    Share g_10;
    Share g_11;
    Share g_12;
    Share g_13;
    Share g_14;
    Share g_15;
    Share g_16;
    Share g_17;
    Share g_18;
    Share g_19;
    Share g_1;
    Share g_20;
    Share g_21;
    Share g_22;
    Share g_23;
    Share g_24;
    Share g_25;
    Share g_26;
    Share g_27;
    Share g_28;
    Share g_29;
    Share g_2;
    Share g_30;
    Share g_31;
    Share g_3;
    Share g_4;
    Share g_5;
    Share g_6;
    Share g_7;
    Share g_8;
    Share g_9;
    Share g_L1_10;
    Share g_L1_12;
    Share g_L1_14;
    Share g_L1_16;
    Share g_L1_18;
    Share g_L1_20;
    Share g_L1_22;
    Share g_L1_24;
    Share g_L1_26;
    Share g_L1_28;
    Share g_L1_2;
    Share g_L1_30;
    Share g_L1_4;
    Share g_L1_6;
    Share g_L1_8;
    Share g_L2_12;
    Share g_L2_16;
    Share g_L2_1;
    Share g_L2_20;
    Share g_L2_24;
    Share g_L2_28;
    Share g_L2_4;
    Share g_L2_8;
    Share g_L3_16;
    Share g_L3_1;
    Share g_L3_24;
    Share g_L3_8;
    Share g_L4_16;
    Share g_L4_1;
    Share g_L5_1;
    Share p_0;
    Share p_10;
    Share p_10_p;
    Share p_10_p_1;
    Share p_11;
    Share p_11_p;
    Share p_12;
    Share p_12_p;
    Share p_12_p_1;
    Share p_13;
    Share p_13_p;
    Share p_14;
    Share p_14_p;
    Share p_14_p_1;
    Share p_15;
    Share p_15_p;
    Share p_16;
    Share p_16_p;
    Share p_16_p_1;
    Share p_17;
    Share p_17_p;
    Share p_18;
    Share p_18_p;
    Share p_18_p_1;
    Share p_19;
    Share p_19_p;
    Share p_1;
    Share p_1_p;
    Share p_1_p_1;
    Share p_20;
    Share p_20_p;
    Share p_20_p_1;
    Share p_21;
    Share p_21_p;
    Share p_22;
    Share p_22_p;
    Share p_22_p_1;
    Share p_23;
    Share p_23_p;
    Share p_24;
    Share p_24_p;
    Share p_24_p_1;
    Share p_25;
    Share p_25_p;
    Share p_26;
    Share p_26_p;
    Share p_26_p_1;
    Share p_27;
    Share p_27_p;
    Share p_28;
    Share p_28_p;
    Share p_28_p_1;
    Share p_29;
    Share p_29_p;
    Share p_2;
    Share p_2_p;
    Share p_2_p_1;
    Share p_30;
    Share p_30_p;
    Share p_31;
    Share p_3;
    Share p_3_p;
    Share p_4;
    Share p_4_p;
    Share p_4_p_1;
    Share p_5;
    Share p_5_p;
    Share p_6;
    Share p_6_p;
    Share p_6_p_1;
    Share p_7;
    Share p_7_p;
    Share p_8;
    Share p_8_p;
    Share p_8_p_1;
    Share p_9;
    Share p_9_p;
    Share p_L1_10;
    Share p_L1_12;
    Share p_L1_12_p;
    Share p_L1_14;
    Share p_L1_16;
    Share p_L1_16_p;
    Share p_L1_18;
    Share p_L1_20;
    Share p_L1_20_p;
    Share p_L1_22;
    Share p_L1_24;
    Share p_L1_24_p;
    Share p_L1_26;
    Share p_L1_28;
    Share p_L1_2;
    Share p_L1_4;
    Share p_L1_4_p;
    Share p_L1_6;
    Share p_L1_8;
    Share p_L1_8_p;
    Share p_L2_12;
    Share p_L2_16;
    Share p_L2_16_p;
    Share p_L2_1;
    Share p_L2_1_p;
    Share p_L2_20;
    Share p_L2_24;
    Share p_L2_4;
    Share p_L2_8;
    Share p_L2_8_p;
    Share p_L3_16;
    Share p_L3_1;
    Share p_L3_1_p;
    Share p_L3_8;
    Share p_L4_1;
    Share pg_L0_10_11;
    Share pg_L0_12_13;
    Share pg_L0_14_15;
    Share pg_L0_16_17;
    Share pg_L0_18_19;
    Share pg_L0_2_3;
    Share pg_L0_20_21;
    Share pg_L0_22_23;
    Share pg_L0_24_25;
    Share pg_L0_26_27;
    Share pg_L0_28_29;
    Share pg_L0_30_31;
    Share pg_L0_4_5;
    Share pg_L0_6_7;
    Share pg_L0_8_9;
    Share pg_L1_1_2;
    Share pg_L1_12_14;
    Share pg_L1_16_18;
    Share pg_L1_20_22;
    Share pg_L1_24_26;
    Share pg_L1_28_30;
    Share pg_L1_4_6;
    Share pg_L1_8_10;
    Share pg_L2_1_4;
    Share pg_L2_16_20;
    Share pg_L2_24_28;
    Share pg_L2_8_12;
    Share pg_L3_1_8;
    Share pg_L3_16_24;
    Share pg_L4_1_16;

  public:
    PPA_MSB_Unsafe_AB(Bitset& a_input, Bitset& b_input, Share& msb_output) : a(a_input), b(b_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            for (int i = 0; i < RandomTripleCount; ++i)
            {
                random_triples[i] = retrieveRandomMultiplication<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r111 = getRandomVal(PSELF);
            r112 = getRandomVal(PSELF);
            r113 = getRandomVal(PSELF);
            r114 = getRandomVal(PSELF);
            r115 = getRandomVal(PSELF);
            r116 = getRandomVal(PSELF);
            r117 = getRandomVal(PSELF);
            r118 = getRandomVal(PSELF);
            r119 = getRandomVal(PSELF);
            r120 = getRandomVal(PSELF);
            r121 = getRandomVal(PSELF);
            r122 = getRandomVal(PSELF);
            r123 = getRandomVal(PSELF);
            r124 = getRandomVal(PSELF);
            r125 = getRandomVal(PSELF);
            r126 = getRandomVal(PSELF);
            r127 = getRandomVal(PSELF);
            r128 = getRandomVal(PSELF);
            r129 = getRandomVal(PSELF);
            r130 = getRandomVal(PSELF);
            r131 = getRandomVal(PSELF);
            r132 = getRandomVal(PSELF);
            r133 = getRandomVal(PSELF);
            r134 = getRandomVal(PSELF);
            r135 = getRandomVal(PSELF);
            r136 = getRandomVal(PSELF);
            r137 = getRandomVal(PSELF);
            r138 = getRandomVal(PSELF);
            r139 = getRandomVal(PSELF);
            r140 = getRandomVal(PSELF);
            r141 = getRandomVal(PSELF);

        }
        a[1].reshare_a(random_triples[0].a);
        b[1].reshare_b(random_triples[0].a);
        a[2].reshare_a(random_triples[1].a);
        b[2].reshare_b(random_triples[1].a);
        a[3].reshare_a(random_triples[2].a);
        b[3].reshare_b(random_triples[2].a);
        a[4].reshare_a(random_triples[3].a);
        b[4].reshare_b(random_triples[3].a);
        a[5].reshare_a(random_triples[4].a);
        b[5].reshare_b(random_triples[4].a);
        a[6].reshare_a(random_triples[5].a);
        b[6].reshare_b(random_triples[5].a);
        a[7].reshare_a(random_triples[6].a);
        b[7].reshare_b(random_triples[6].a);
        a[8].reshare_a(random_triples[7].a);
        b[8].reshare_b(random_triples[7].a);
        a[9].reshare_a(random_triples[8].a);
        b[9].reshare_b(random_triples[8].a);
        a[10].reshare_a(random_triples[9].a);
        b[10].reshare_b(random_triples[9].a);
        a[11].reshare_a(random_triples[10].a);
        b[11].reshare_b(random_triples[10].a);
        a[12].reshare_a(random_triples[11].a);
        b[12].reshare_b(random_triples[11].a);
        a[13].reshare_a(random_triples[12].a);
        b[13].reshare_b(random_triples[12].a);
        a[14].reshare_a(random_triples[13].a);
        b[14].reshare_b(random_triples[13].a);
        a[15].reshare_a(random_triples[14].a);
        b[15].reshare_b(random_triples[14].a);
        a[16].reshare_a(random_triples[15].a);
        b[16].reshare_b(random_triples[15].a);
        a[17].reshare_a(random_triples[16].a);
        b[17].reshare_b(random_triples[16].a);
        a[18].reshare_a(random_triples[17].a);
        b[18].reshare_b(random_triples[17].a);
        a[19].reshare_a(random_triples[18].a);
        b[19].reshare_b(random_triples[18].a);
        a[20].reshare_a(random_triples[19].a);
        b[20].reshare_b(random_triples[19].a);
        a[21].reshare_a(random_triples[20].a);
        b[21].reshare_b(random_triples[20].a);
        a[22].reshare_a(random_triples[21].a);
        b[22].reshare_b(random_triples[21].a);
        a[23].reshare_a(random_triples[22].a);
        b[23].reshare_b(random_triples[22].a);
        a[24].reshare_a(random_triples[23].a);
        b[24].reshare_b(random_triples[23].a);
        a[25].reshare_a(random_triples[24].a);
        b[25].reshare_b(random_triples[24].a);
        a[26].reshare_a(random_triples[25].a);
        b[26].reshare_b(random_triples[25].a);
        a[27].reshare_a(random_triples[26].a);
        b[27].reshare_b(random_triples[26].a);
        a[28].reshare_a(random_triples[27].a);
        b[28].reshare_b(random_triples[27].a);
        a[29].reshare_a(random_triples[28].a);
        b[29].reshare_b(random_triples[28].a);
        a[30].reshare_a(random_triples[29].a);
        b[30].reshare_b(random_triples[29].a);
        a[31].reshare_a(random_triples[30].a);
        b[31].reshare_b(random_triples[30].a);
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 7; }
    bool is_done() const { return level > 6; }

    void step()
    {
        switch(level) {
            case 0:
                p_0 = a[0] ^ b[0];  // p[0]
                p_1 = a[1] ^ b[1];  // p[1]
                p_2 = a[2] ^ b[2];  // p[2]
                p_3 = a[3] ^ b[3];  // p[3]
                p_4 = a[4] ^ b[4];  // p[4]
                p_5 = a[5] ^ b[5];  // p[5]
                p_6 = a[6] ^ b[6];  // p[6]
                p_7 = a[7] ^ b[7];  // p[7]
                p_8 = a[8] ^ b[8];  // p[8]
                p_9 = a[9] ^ b[9];  // p[9]
                p_10 = a[10] ^ b[10];  // p[10]
                p_11 = a[11] ^ b[11];  // p[11]
                p_12 = a[12] ^ b[12];  // p[12]
                p_13 = a[13] ^ b[13];  // p[13]
                p_14 = a[14] ^ b[14];  // p[14]
                p_15 = a[15] ^ b[15];  // p[15]
                p_16 = a[16] ^ b[16];  // p[16]
                p_17 = a[17] ^ b[17];  // p[17]
                p_18 = a[18] ^ b[18];  // p[18]
                p_19 = a[19] ^ b[19];  // p[19]
                p_20 = a[20] ^ b[20];  // p[20]
                p_21 = a[21] ^ b[21];  // p[21]
                p_22 = a[22] ^ b[22];  // p[22]
                p_23 = a[23] ^ b[23];  // p[23]
                p_24 = a[24] ^ b[24];  // p[24]
                p_25 = a[25] ^ b[25];  // p[25]
                p_26 = a[26] ^ b[26];  // p[26]
                p_27 = a[27] ^ b[27];  // p[27]
                p_28 = a[28] ^ b[28];  // p[28]
                p_29 = a[29] ^ b[29];  // p[29]
                p_30 = a[30] ^ b[30];  // p[30]
                p_31 = a[31] ^ b[31];  // p[31]
                p_1_p = p_1.zero_add(triples[42].a);  // p[1]', mask=a73
                p_1_p_1 = p_1.zero_add(triples[43].b);  // p[1]'_1, mask=b74
                p_2_p = p_2.zero_add(triples[27].a);  // p[2]', mask=a58
                p_2_p_1 = p_2.zero_add(triples[28].b);  // p[2]'_1, mask=b59
                p_3_p = p_3.zero_add(triples[28].a);  // p[3]', mask=a59
                p_4_p = p_4.zero_add(triples[25].a);  // p[4]', mask=a56
                p_4_p_1 = p_4.zero_add(triples[26].b);  // p[4]'_1, mask=b57
                p_5_p = p_5.zero_add(triples[26].a);  // p[5]', mask=a57
                p_6_p = p_6.zero_add(triples[23].a);  // p[6]', mask=a54
                p_6_p_1 = p_6.zero_add(triples[24].b);  // p[6]'_1, mask=b55
                p_7_p = p_7.zero_add(triples[24].a);  // p[7]', mask=a55
                p_8_p = p_8.zero_add(triples[21].a);  // p[8]', mask=a52
                p_8_p_1 = p_8.zero_add(triples[22].b);  // p[8]'_1, mask=b53
                p_9_p = p_9.zero_add(triples[22].a);  // p[9]', mask=a53
                p_10_p = p_10.zero_add(triples[19].a);  // p[10]', mask=a50
                p_10_p_1 = p_10.zero_add(triples[20].b);  // p[10]'_1, mask=b51
                p_11_p = p_11.zero_add(triples[20].a);  // p[11]', mask=a51
                p_12_p = p_12.zero_add(triples[17].a);  // p[12]', mask=a48
                p_12_p_1 = p_12.zero_add(triples[18].b);  // p[12]'_1, mask=b49
                p_13_p = p_13.zero_add(triples[18].a);  // p[13]', mask=a49
                p_14_p = p_14.zero_add(triples[15].a);  // p[14]', mask=a46
                p_14_p_1 = p_14.zero_add(triples[16].b);  // p[14]'_1, mask=b47
                p_15_p = p_15.zero_add(triples[16].a);  // p[15]', mask=a47
                p_16_p = p_16.zero_add(triples[13].a);  // p[16]', mask=a44
                p_16_p_1 = p_16.zero_add(triples[14].b);  // p[16]'_1, mask=b45
                p_17_p = p_17.zero_add(triples[14].a);  // p[17]', mask=a45
                p_18_p = p_18.zero_add(triples[11].a);  // p[18]', mask=a42
                p_18_p_1 = p_18.zero_add(triples[12].b);  // p[18]'_1, mask=b43
                p_19_p = p_19.zero_add(triples[12].a);  // p[19]', mask=a43
                p_20_p = p_20.zero_add(triples[9].a);  // p[20]', mask=a40
                p_20_p_1 = p_20.zero_add(triples[10].b);  // p[20]'_1, mask=b41
                p_21_p = p_21.zero_add(triples[10].a);  // p[21]', mask=a41
                p_22_p = p_22.zero_add(triples[7].a);  // p[22]', mask=a38
                p_22_p_1 = p_22.zero_add(triples[8].b);  // p[22]'_1, mask=b39
                p_23_p = p_23.zero_add(triples[8].a);  // p[23]', mask=a39
                p_24_p = p_24.zero_add(triples[5].a);  // p[24]', mask=a36
                p_24_p_1 = p_24.zero_add(triples[6].b);  // p[24]'_1, mask=b37
                p_25_p = p_25.zero_add(triples[6].a);  // p[25]', mask=a37
                p_26_p = p_26.zero_add(triples[3].a);  // p[26]', mask=a34
                p_26_p_1 = p_26.zero_add(triples[4].b);  // p[26]'_1, mask=b35
                p_27_p = p_27.zero_add(triples[4].a);  // p[27]', mask=a35
                p_28_p = p_28.zero_add(triples[1].a);  // p[28]', mask=a32
                p_28_p_1 = p_28.zero_add(triples[2].b);  // p[28]'_1, mask=b33
                p_29_p = p_29.zero_add(triples[2].a);  // p[29]', mask=a33
                p_30_p = p_30.zero_add(triples[0].a);  // p[30]', mask=a31
                // and_5: random_triples[2].a, random_triples[2].b, output mask=b58
                g_3 = a[3].prepare_and_reshared(b[3], triples[27].b, random_triples[2].b);  // and_5
                // and_9: random_triples[4].a, random_triples[4].b, output mask=b56
                g_5 = a[5].prepare_and_reshared(b[5], triples[25].b, random_triples[4].b);  // and_9
                // and_13: random_triples[6].a, random_triples[6].b, output mask=b54
                g_7 = a[7].prepare_and_reshared(b[7], triples[23].b, random_triples[6].b);  // and_13
                // and_17: random_triples[8].a, random_triples[8].b, output mask=b52
                g_9 = a[9].prepare_and_reshared(b[9], triples[21].b, random_triples[8].b);  // and_17
                // and_21: random_triples[10].a, random_triples[10].b, output mask=b50
                g_11 = a[11].prepare_and_reshared(b[11], triples[19].b, random_triples[10].b);  // and_21
                // and_25: random_triples[12].a, random_triples[12].b, output mask=b48
                g_13 = a[13].prepare_and_reshared(b[13], triples[17].b, random_triples[12].b);  // and_25
                // and_29: random_triples[14].a, random_triples[14].b, output mask=b46
                g_15 = a[15].prepare_and_reshared(b[15], triples[15].b, random_triples[14].b);  // and_29
                // and_33: random_triples[16].a, random_triples[16].b, output mask=b44
                g_17 = a[17].prepare_and_reshared(b[17], triples[13].b, random_triples[16].b);  // and_33
                // and_37: random_triples[18].a, random_triples[18].b, output mask=b42
                g_19 = a[19].prepare_and_reshared(b[19], triples[11].b, random_triples[18].b);  // and_37
                // and_41: random_triples[20].a, random_triples[20].b, output mask=b40
                g_21 = a[21].prepare_and_reshared(b[21], triples[9].b, random_triples[20].b);  // and_41
                // and_45: random_triples[22].a, random_triples[22].b, output mask=b38
                g_23 = a[23].prepare_and_reshared(b[23], triples[7].b, random_triples[22].b);  // and_45
                // and_49: random_triples[24].a, random_triples[24].b, output mask=b36
                g_25 = a[25].prepare_and_reshared(b[25], triples[5].b, random_triples[24].b);  // and_49
                // and_53: random_triples[26].a, random_triples[26].b, output mask=b34
                g_27 = a[27].prepare_and_reshared(b[27], triples[3].b, random_triples[26].b);  // and_53
                // and_57: random_triples[28].a, random_triples[28].b, output mask=b32
                g_29 = a[29].prepare_and_reshared(b[29], triples[1].b, random_triples[28].b);  // and_57
                // and_61: random_triples[30].a, random_triples[30].b, output mask=b31
                g_31 = a[31].prepare_and_reshared(b[31], triples[0].b, random_triples[30].b);  // and_61
                // and_67: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=a60
                p_L1_28 = p_29_p.prepare_and(p_28_p_1, triples[29].a, triples[2].c);  // and_67
                // and_70: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=a62
                p_L1_26 = p_27_p.prepare_and(p_26_p_1, triples[31].a, triples[4].c);  // and_70
                // and_73: a6=triples[6].a, b6=triples[6].b, c6=triples[6].c, output mask=b62
                p_L1_24 = p_25_p.prepare_and(p_24_p_1, triples[31].b, triples[6].c);  // and_73
                // and_76: a8=triples[8].a, b8=triples[8].b, c8=triples[8].c, output mask=a64
                p_L1_22 = p_23_p.prepare_and(p_22_p_1, triples[33].a, triples[8].c);  // and_76
                // and_79: a10=triples[10].a, b10=triples[10].b, c10=triples[10].c, output mask=b64
                p_L1_20 = p_21_p.prepare_and(p_20_p_1, triples[33].b, triples[10].c);  // and_79
                // and_82: a12=triples[12].a, b12=triples[12].b, c12=triples[12].c, output mask=a66
                p_L1_18 = p_19_p.prepare_and(p_18_p_1, triples[35].a, triples[12].c);  // and_82
                // and_85: a14=triples[14].a, b14=triples[14].b, c14=triples[14].c, output mask=b66
                p_L1_16 = p_17_p.prepare_and(p_16_p_1, triples[35].b, triples[14].c);  // and_85
                // and_88: a16=triples[16].a, b16=triples[16].b, c16=triples[16].c, output mask=a68
                p_L1_14 = p_15_p.prepare_and(p_14_p_1, triples[37].a, triples[16].c);  // and_88
                // and_91: a18=triples[18].a, b18=triples[18].b, c18=triples[18].c, output mask=b68
                p_L1_12 = p_13_p.prepare_and(p_12_p_1, triples[37].b, triples[18].c);  // and_91
                // and_94: a20=triples[20].a, b20=triples[20].b, c20=triples[20].c, output mask=a70
                p_L1_10 = p_11_p.prepare_and(p_10_p_1, triples[39].a, triples[20].c);  // and_94
                // and_97: a22=triples[22].a, b22=triples[22].b, c22=triples[22].c, output mask=b70
                p_L1_8 = p_9_p.prepare_and(p_8_p_1, triples[39].b, triples[22].c);  // and_97
                // and_100: a24=triples[24].a, b24=triples[24].b, c24=triples[24].c, output mask=a72
                p_L1_6 = p_7_p.prepare_and(p_6_p_1, triples[41].a, triples[24].c);  // and_100
                // and_103: a26=triples[26].a, b26=triples[26].b, c26=triples[26].c, output mask=b72
                p_L1_4 = p_5_p.prepare_and(p_4_p_1, triples[41].b, triples[26].c);  // and_103
                // and_106: a28=triples[28].a, b28=triples[28].b, c28=triples[28].c, output mask=a74
                p_L1_2 = p_3_p.prepare_and(p_2_p_1, triples[43].a, triples[28].c);  // and_106
                break;
            case 1:
                g_3.complete_and();
                g_5.complete_and();
                g_7.complete_and();
                g_9.complete_and();
                g_11.complete_and();
                g_13.complete_and();
                g_15.complete_and();
                g_17.complete_and();
                g_19.complete_and();
                g_21.complete_and();
                g_23.complete_and();
                g_25.complete_and();
                g_27.complete_and();
                g_29.complete_and();
                g_31.complete_and();
                p_L1_28.complete_and();
                p_L1_26.complete_and();
                p_L1_24.complete_and();
                p_L1_22.complete_and();
                p_L1_20.complete_and();
                p_L1_18.complete_and();
                p_L1_16.complete_and();
                p_L1_14.complete_and();
                p_L1_12.complete_and();
                p_L1_10.complete_and();
                p_L1_8.complete_and();
                p_L1_6.complete_and();
                p_L1_4.complete_and();
                p_L1_2.complete_and();
                p_L1_4_p = p_L1_4.zero_add(triples[40].a);  // p_L1[4]', mask=a71
                p_L1_8_p = p_L1_8.zero_add(triples[38].a);  // p_L1[8]', mask=a69
                p_L1_12_p = p_L1_12.zero_add(triples[36].a);  // p_L1[12]', mask=a67
                p_L1_16_p = p_L1_16.zero_add(triples[34].a);  // p_L1[16]', mask=a65
                p_L1_20_p = p_L1_20.zero_add(triples[32].a);  // p_L1[20]', mask=a63
                p_L1_24_p = p_L1_24.zero_add(triples[30].a);  // p_L1[24]', mask=a61
                // and_3: random_triples[1].a, random_triples[1].b, output mask=r118
                g_2 = a[2].prepare_and_reshared(b[2], r118, random_triples[1].b);  // and_3
                // and_104: a27=triples[27].a, b27=triples[27].b, c27=triples[27].c, output mask=(b73-r118)
                pg_L0_2_3 = p_2_p.prepare_and(g_3, FUNC_XOR(triples[42].b, r118), triples[27].c);  // and_104
                // and_7: random_triples[3].a, random_triples[3].b, output mask=r126
                g_4 = a[4].prepare_and_reshared(b[4], r126, random_triples[3].b);  // and_7
                // and_101: a25=triples[25].a, b25=triples[25].b, c25=triples[25].c, output mask=(r125-r126)
                pg_L0_4_5 = p_4_p.prepare_and(g_5, FUNC_XOR(r125, r126), triples[25].c);  // and_101
                // and_11: random_triples[5].a, random_triples[5].b, output mask=r117
                g_6 = a[6].prepare_and_reshared(b[6], r117, random_triples[5].b);  // and_11
                // and_98: a23=triples[23].a, b23=triples[23].b, c23=triples[23].c, output mask=(b71-r117)
                pg_L0_6_7 = p_6_p.prepare_and(g_7, FUNC_XOR(triples[40].b, r117), triples[23].c);  // and_98
                // and_15: random_triples[7].a, random_triples[7].b, output mask=r132
                g_8 = a[8].prepare_and_reshared(b[8], r132, random_triples[7].b);  // and_15
                // and_95: a21=triples[21].a, b21=triples[21].b, c21=triples[21].c, output mask=(r131-r132)
                pg_L0_8_9 = p_8_p.prepare_and(g_9, FUNC_XOR(r131, r132), triples[21].c);  // and_95
                // and_19: random_triples[9].a, random_triples[9].b, output mask=r116
                g_10 = a[10].prepare_and_reshared(b[10], r116, random_triples[9].b);  // and_19
                // and_92: a19=triples[19].a, b19=triples[19].b, c19=triples[19].c, output mask=(b69-r116)
                pg_L0_10_11 = p_10_p.prepare_and(g_11, FUNC_XOR(triples[38].b, r116), triples[19].c);  // and_92
                // and_23: random_triples[11].a, random_triples[11].b, output mask=r124
                g_12 = a[12].prepare_and_reshared(b[12], r124, random_triples[11].b);  // and_23
                // and_89: a17=triples[17].a, b17=triples[17].b, c17=triples[17].c, output mask=(r123-r124)
                pg_L0_12_13 = p_12_p.prepare_and(g_13, FUNC_XOR(r123, r124), triples[17].c);  // and_89
                // and_27: random_triples[13].a, random_triples[13].b, output mask=r115
                g_14 = a[14].prepare_and_reshared(b[14], r115, random_triples[13].b);  // and_27
                // and_86: a15=triples[15].a, b15=triples[15].b, c15=triples[15].c, output mask=(b67-r115)
                pg_L0_14_15 = p_14_p.prepare_and(g_15, FUNC_XOR(triples[36].b, r115), triples[15].c);  // and_86
                // and_31: random_triples[15].a, random_triples[15].b, output mask=r136
                g_16 = a[16].prepare_and_reshared(b[16], r136, random_triples[15].b);  // and_31
                // and_83: a13=triples[13].a, b13=triples[13].b, c13=triples[13].c, output mask=(r135-r136)
                pg_L0_16_17 = p_16_p.prepare_and(g_17, FUNC_XOR(r135, r136), triples[13].c);  // and_83
                // and_35: random_triples[17].a, random_triples[17].b, output mask=r114
                g_18 = a[18].prepare_and_reshared(b[18], r114, random_triples[17].b);  // and_35
                // and_80: a11=triples[11].a, b11=triples[11].b, c11=triples[11].c, output mask=(b65-r114)
                pg_L0_18_19 = p_18_p.prepare_and(g_19, FUNC_XOR(triples[34].b, r114), triples[11].c);  // and_80
                // and_39: random_triples[19].a, random_triples[19].b, output mask=r122
                g_20 = a[20].prepare_and_reshared(b[20], r122, random_triples[19].b);  // and_39
                // and_77: a9=triples[9].a, b9=triples[9].b, c9=triples[9].c, output mask=(r121-r122)
                pg_L0_20_21 = p_20_p.prepare_and(g_21, FUNC_XOR(r121, r122), triples[9].c);  // and_77
                // and_43: random_triples[21].a, random_triples[21].b, output mask=r113
                g_22 = a[22].prepare_and_reshared(b[22], r113, random_triples[21].b);  // and_43
                // and_74: a7=triples[7].a, b7=triples[7].b, c7=triples[7].c, output mask=(b63-r113)
                pg_L0_22_23 = p_22_p.prepare_and(g_23, FUNC_XOR(triples[32].b, r113), triples[7].c);  // and_74
                // and_47: random_triples[23].a, random_triples[23].b, output mask=r129
                g_24 = a[24].prepare_and_reshared(b[24], r129, random_triples[23].b);  // and_47
                // and_71: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=(r128-r129)
                pg_L0_24_25 = p_24_p.prepare_and(g_25, FUNC_XOR(r128, r129), triples[5].c);  // and_71
                // and_51: random_triples[25].a, random_triples[25].b, output mask=r112
                g_26 = a[26].prepare_and_reshared(b[26], r112, random_triples[25].b);  // and_51
                // and_68: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=(b61-r112)
                pg_L0_26_27 = p_26_p.prepare_and(g_27, FUNC_XOR(triples[30].b, r112), triples[3].c);  // and_68
                // and_55: random_triples[27].a, random_triples[27].b, output mask=r120
                g_28 = a[28].prepare_and_reshared(b[28], r120, random_triples[27].b);  // and_55
                // and_65: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=(r119-r120)
                pg_L0_28_29 = p_28_p.prepare_and(g_29, FUNC_XOR(r119, r120), triples[1].c);  // and_65
                // and_59: random_triples[29].a, random_triples[29].b, output mask=r111
                g_30 = a[30].prepare_and_reshared(b[30], r111, random_triples[29].b);  // and_59
                // and_63: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=(b60-r111)
                pg_L0_30_31 = p_30_p.prepare_and(g_31, FUNC_XOR(triples[29].b, r111), triples[0].c);  // and_63
                // and_111: a31=triples[31].a, b31=triples[31].b, c31=triples[31].c, output mask=a75
                p_L2_24 = p_L1_26.prepare_and(p_L1_24, triples[44].a, triples[31].c);  // and_111
                // and_114: a33=triples[33].a, b33=triples[33].b, c33=triples[33].c, output mask=a77
                p_L2_20 = p_L1_22.prepare_and(p_L1_20, triples[46].a, triples[33].c);  // and_114
                // and_117: a35=triples[35].a, b35=triples[35].b, c35=triples[35].c, output mask=b77
                p_L2_16 = p_L1_18.prepare_and(p_L1_16, triples[46].b, triples[35].c);  // and_117
                // and_120: a37=triples[37].a, b37=triples[37].b, c37=triples[37].c, output mask=a79
                p_L2_12 = p_L1_14.prepare_and(p_L1_12, triples[48].a, triples[37].c);  // and_120
                // and_123: a39=triples[39].a, b39=triples[39].b, c39=triples[39].c, output mask=b79
                p_L2_8 = p_L1_10.prepare_and(p_L1_8, triples[48].b, triples[39].c);  // and_123
                // and_126: a41=triples[41].a, b41=triples[41].b, c41=triples[41].c, output mask=a81
                p_L2_4 = p_L1_6.prepare_and(p_L1_4, triples[50].a, triples[41].c);  // and_126
                // and_129: a43=triples[43].a, b43=triples[43].b, c43=triples[43].c, output mask=b81
                p_L2_1 = p_L1_2.prepare_and(p_1_p_1, triples[50].b, triples[43].c);  // and_129
                break;
            case 2:
                g_2.complete_and();
                pg_L0_2_3.complete_and();
                g_L1_2 = g_2 ^ pg_L0_2_3;  // g_L1[2]
                g_4.complete_and();
                pg_L0_4_5.complete_and();
                g_L1_4 = g_4 ^ pg_L0_4_5;  // g_L1[4]
                g_6.complete_and();
                pg_L0_6_7.complete_and();
                g_L1_6 = g_6 ^ pg_L0_6_7;  // g_L1[6]
                g_8.complete_and();
                pg_L0_8_9.complete_and();
                g_L1_8 = g_8 ^ pg_L0_8_9;  // g_L1[8]
                g_10.complete_and();
                pg_L0_10_11.complete_and();
                g_L1_10 = g_10 ^ pg_L0_10_11;  // g_L1[10]
                g_12.complete_and();
                pg_L0_12_13.complete_and();
                g_L1_12 = g_12 ^ pg_L0_12_13;  // g_L1[12]
                g_14.complete_and();
                pg_L0_14_15.complete_and();
                g_L1_14 = g_14 ^ pg_L0_14_15;  // g_L1[14]
                g_16.complete_and();
                pg_L0_16_17.complete_and();
                g_L1_16 = g_16 ^ pg_L0_16_17;  // g_L1[16]
                g_18.complete_and();
                pg_L0_18_19.complete_and();
                g_L1_18 = g_18 ^ pg_L0_18_19;  // g_L1[18]
                g_20.complete_and();
                pg_L0_20_21.complete_and();
                g_L1_20 = g_20 ^ pg_L0_20_21;  // g_L1[20]
                g_22.complete_and();
                pg_L0_22_23.complete_and();
                g_L1_22 = g_22 ^ pg_L0_22_23;  // g_L1[22]
                g_24.complete_and();
                pg_L0_24_25.complete_and();
                g_L1_24 = g_24 ^ pg_L0_24_25;  // g_L1[24]
                g_26.complete_and();
                pg_L0_26_27.complete_and();
                g_L1_26 = g_26 ^ pg_L0_26_27;  // g_L1[26]
                g_28.complete_and();
                pg_L0_28_29.complete_and();
                g_L1_28 = g_28 ^ pg_L0_28_29;  // g_L1[28]
                g_30.complete_and();
                pg_L0_30_31.complete_and();
                g_L1_30 = g_30 ^ pg_L0_30_31;  // g_L1[30]
                p_L2_24.complete_and();
                p_L2_20.complete_and();
                p_L2_16.complete_and();
                p_L2_12.complete_and();
                p_L2_8.complete_and();
                p_L2_4.complete_and();
                p_L2_1.complete_and();
                p_L2_1_p = p_L2_1.zero_add(triples[49].a);  // p_L2[1]', mask=a80
                p_L2_8_p = p_L2_8.zero_add(triples[47].a);  // p_L2[8]', mask=a78
                p_L2_16_p = p_L2_16.zero_add(triples[45].a);  // p_L2[16]', mask=a76
                // and_1: random_triples[0].a, random_triples[0].b, output mask=r137
                g_1 = a[1].prepare_and_reshared(b[1], r137, random_triples[0].b);  // and_1
                // and_127: a42=triples[42].a, b42=triples[42].b, c42=triples[42].c, output mask=r138
                pg_L1_1_2 = p_1_p.prepare_and(g_L1_2, r138, triples[42].c);  // and_127
                // and_107: a29=triples[29].a, b29=triples[29].b, c29=triples[29].c, output mask=(b75-r119)
                pg_L1_28_30 = p_L1_28.prepare_and(g_L1_30, FUNC_XOR(triples[44].b, r119), triples[29].c);  // and_107
                // and_109: a30=triples[30].a, b30=triples[30].b, c30=triples[30].c, output mask=(r127-r128)
                pg_L1_24_26 = p_L1_24_p.prepare_and(g_L1_26, FUNC_XOR(r127, r128), triples[30].c);  // and_109
                // and_112: a32=triples[32].a, b32=triples[32].b, c32=triples[32].c, output mask=(b76-r121)
                pg_L1_20_22 = p_L1_20_p.prepare_and(g_L1_22, FUNC_XOR(triples[45].b, r121), triples[32].c);  // and_112
                // and_115: a34=triples[34].a, b34=triples[34].b, c34=triples[34].c, output mask=(r134-r135)
                pg_L1_16_18 = p_L1_16_p.prepare_and(g_L1_18, FUNC_XOR(r134, r135), triples[34].c);  // and_115
                // and_118: a36=triples[36].a, b36=triples[36].b, c36=triples[36].c, output mask=(b78-r123)
                pg_L1_12_14 = p_L1_12_p.prepare_and(g_L1_14, FUNC_XOR(triples[47].b, r123), triples[36].c);  // and_118
                // and_121: a38=triples[38].a, b38=triples[38].b, c38=triples[38].c, output mask=(r130-r131)
                pg_L1_8_10 = p_L1_8_p.prepare_and(g_L1_10, FUNC_XOR(r130, r131), triples[38].c);  // and_121
                // and_124: a40=triples[40].a, b40=triples[40].b, c40=triples[40].c, output mask=(b80-r125)
                pg_L1_4_6 = p_L1_4_p.prepare_and(g_L1_6, FUNC_XOR(triples[49].b, r125), triples[40].c);  // and_124
                // and_134: a46=triples[46].a, b46=triples[46].b, c46=triples[46].c, output mask=a82
                p_L3_16 = p_L2_20.prepare_and(p_L2_16, triples[51].a, triples[46].c);  // and_134
                // and_137: a48=triples[48].a, b48=triples[48].b, c48=triples[48].c, output mask=a84
                p_L3_8 = p_L2_12.prepare_and(p_L2_8, triples[53].a, triples[48].c);  // and_137
                // and_140: a50=triples[50].a, b50=triples[50].b, c50=triples[50].c, output mask=b84
                p_L3_1 = p_L2_4.prepare_and(p_L2_1, triples[53].b, triples[50].c);  // and_140
                break;
            case 3:
                g_1.complete_and();
                pg_L1_1_2.complete_and();
                g_L2_1 = g_1 ^ pg_L1_1_2;  // g_L2[1]
                pg_L1_28_30.complete_and();
                pg_L1_24_26.complete_and();
                pg_L1_20_22.complete_and();
                pg_L1_16_18.complete_and();
                pg_L1_12_14.complete_and();
                pg_L1_8_10.complete_and();
                pg_L1_4_6.complete_and();
                p_L3_16.complete_and();
                p_L3_8.complete_and();
                p_L3_1.complete_and();
                g_L2_4 = g_L1_4 ^ pg_L1_4_6;  // g_L2[4]
                p_L3_1_p = p_L3_1.zero_add(triples[52].a);  // p_L3[1]', mask=a83
                g_L2_8 = g_L1_8 ^ pg_L1_8_10;  // g_L2[8]
                g_L2_12 = g_L1_12 ^ pg_L1_12_14;  // g_L2[12]
                g_L2_16 = g_L1_16 ^ pg_L1_16_18;  // g_L2[16]
                g_L2_20 = g_L1_20 ^ pg_L1_20_22;  // g_L2[20]
                g_L2_24 = g_L1_24 ^ pg_L1_24_26;  // g_L2[24]
                g_L2_28 = g_L1_28 ^ pg_L1_28_30;  // g_L2[28]
                // and_130: a44=triples[44].a, b44=triples[44].b, c44=triples[44].c, output mask=(b82-r127)
                pg_L2_24_28 = p_L2_24.prepare_and(g_L2_28, FUNC_XOR(triples[51].b, r127), triples[44].c);  // and_130
                // and_132: a45=triples[45].a, b45=triples[45].b, c45=triples[45].c, output mask=(r133-r134)
                pg_L2_16_20 = p_L2_16_p.prepare_and(g_L2_20, FUNC_XOR(r133, r134), triples[45].c);  // and_132
                // and_135: a47=triples[47].a, b47=triples[47].b, c47=triples[47].c, output mask=(b83-r130)
                pg_L2_8_12 = p_L2_8_p.prepare_and(g_L2_12, FUNC_XOR(triples[52].b, r130), triples[47].c);  // and_135
                // and_138: a49=triples[49].a, b49=triples[49].b, c49=triples[49].c, output mask=r139
                pg_L2_1_4 = p_L2_1_p.prepare_and(g_L2_4, r139, triples[49].c);  // and_138
                // and_145: a53=triples[53].a, b53=triples[53].b, c53=triples[53].c, output mask=a85
                p_L4_1 = p_L3_8.prepare_and(p_L3_1, triples[54].a, triples[53].c);  // and_145
                break;
            case 4:
                pg_L2_24_28.complete_and();
                pg_L2_16_20.complete_and();
                pg_L2_8_12.complete_and();
                pg_L2_1_4.complete_and();
                p_L4_1.complete_and();
                g_L3_1 = g_L2_1 ^ pg_L2_1_4;  // g_L3[1]
                g_L3_8 = g_L2_8 ^ pg_L2_8_12;  // g_L3[8]
                g_L3_16 = g_L2_16 ^ pg_L2_16_20;  // g_L3[16]
                g_L3_24 = g_L2_24 ^ pg_L2_24_28;  // g_L3[24]
                // and_141: a51=triples[51].a, b51=triples[51].b, c51=triples[51].c, output mask=(b85-r133)
                pg_L3_16_24 = p_L3_16.prepare_and(g_L3_24, FUNC_XOR(triples[54].b, r133), triples[51].c);  // and_141
                // and_143: a52=triples[52].a, b52=triples[52].b, c52=triples[52].c, output mask=r140
                pg_L3_1_8 = p_L3_1_p.prepare_and(g_L3_8, r140, triples[52].c);  // and_143
                break;
            case 5:
                pg_L3_16_24.complete_and();
                pg_L3_1_8.complete_and();
                g_L4_1 = g_L3_1 ^ pg_L3_1_8;  // g_L4[1]
                g_L4_16 = g_L3_16 ^ pg_L3_16_24;  // g_L4[16]
                // and_146: a54=triples[54].a, b54=triples[54].b, c54=triples[54].c, output mask=r141
                pg_L4_1_16 = p_L4_1.prepare_and(g_L4_16, r141, triples[54].c);  // and_146
                break;
            case 6:
                pg_L4_1_16.complete_and();
                g_L5_1 = g_L4_1 ^ pg_L4_1_16;  // g_L5[1]
                msb = p_0 ^ g_L5_1;  // msb
                break;
        }
        level++;
    }
};
