FUNCTION_IDENTIFIER=76,176,276,87,187,287
MODELOWNER=-1
DATAOWNER=-1
PROTOCOL=4
PRE=1
BITLENGTH=32
DATTYPE=256
PROCESS_NUM=32
NUM_INPUTS=1
FRACTIONAL=5
SKIP_PRE=0,1
OPTIMIZED_BIT_INJECTION_RELU=0,1
FUSE_RELU_AVG=0,1
