FUNCTION_IDENTIFIER=87,187,287
MODELOWNER=-1
DATAOWNER=-1
BITLENGTH=32
DATTYPE=32
NUM_INPUTS=1
FRACTIONAL=5
PROTOCOL=5
PRE=1
SKIP_PRE=1
OPTIMIZED_BIT_INJECTION_RELU=1
FUSE_RELU_AVG=1
FUSE_CONV_BN=1
COMPRESS=0,1
A_KNOWN=0,1
