// Wire assignment code for PPA_MSB_4Way_AB family
// Generated by generate_hpp.py
#pragma once
#include <type_traits>
#include "../../../datatypes/k_bitset.hpp"
#include "../../../protocols/Protocols.h"

template <int k, typename Share, typename Enable = void>
class PPA_MSB_4Way_AB;

// Wire assignment code for PPA_MSB_4Way_AB (8-bit)
// Generated by generate_hpp.py
// Gates: AND2=1, AND3=4, AND4=2, AND_A=0, AND_RESHARED=3, XOR=14, ZERO_ADD=19
// Beaver triples: 1, Beaver3Tuples: 4, Beaver4Tuples: 2, RandomTriples: 3
template <int k, typename Share>
class PPA_MSB_4Way_AB<k, Share, typename std::enable_if<(k == 8)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 8;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& a;
    Bitset& b;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 1;
    triple<DATATYPE> triples[BeaverTripleCount];
    static constexpr int Beaver3TupleCount = 4;
    Beaver3Tuple<DATATYPE> beaver3_tuples[Beaver3TupleCount];
    static constexpr int Beaver4TupleCount = 2;
    Beaver4Tuple<DATATYPE> beaver4_tuples[Beaver4TupleCount];
    static constexpr int RandomTripleCount = 3;
    RandomMultiplication<DATATYPE> random_triples[RandomTripleCount];

    DATATYPE r23;
    DATATYPE r24;
    DATATYPE r25;
    DATATYPE r26;
    DATATYPE r27;
    DATATYPE r28;
    DATATYPE r29;

    Share a_3_p;
    Share a_4_p;
    Share a_6_p;
    Share a_7_p;
    Share b_3_p;
    Share b_4_p;
    Share b_6_p;
    Share b_7_p;
    Share g1_L0;
    Share g1_L1;
    Share g1_W3L1;
    Share p0;
    Share p1_L0;
    Share p1_L0_p;
    Share p1_L0_p_1;
    Share p1_L0_p_2;
    Share p1_L1;
    Share p1_L1_p;
    Share p1_L1_p_1;
    Share p1_W3L1;
    Share p1_W3L1_p;
    Share p1_W3L1_p_1;
    Share p2_L0;
    Share p2_L0_p;
    Share p2_L0_p_1;
    Share p2_W3L1;
    Share p2_W3L1_p;
    Share p3_L0;
    Share p3_L0_p;
    Share t1_L0;
    Share t1_L1;
    Share t1_W3L1;
    Share t2_L0;
    Share t2_L1;
    Share t2_W3L1;
    Share t3_L0;
    Share t3_L1;
    Share t3_W3L1;
    Share t4_L1;
    Share v_0;
    Share v_1;
    Share v_2;

  public:
    PPA_MSB_4Way_AB(Bitset& a_input, Bitset& b_input, Share& msb_output) : a(a_input), b(b_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            for (int i = 0; i < Beaver3TupleCount; ++i)
            {
                beaver3_tuples[i] = retrieveBeaver3Tuple<DATATYPE>();
            }
            for (int i = 0; i < Beaver4TupleCount; ++i)
            {
                beaver4_tuples[i] = retrieveBeaver4Tuple<DATATYPE>();
            }
            for (int i = 0; i < RandomTripleCount; ++i)
            {
                random_triples[i] = retrieveRandomMultiplication<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r23 = getRandomVal(PSELF);
            r24 = getRandomVal(PSELF);
            r25 = getRandomVal(PSELF);
            r26 = getRandomVal(PSELF);
            r27 = getRandomVal(PSELF);
            r28 = getRandomVal(PSELF);
            r29 = getRandomVal(PSELF);

        }
        a[2].reshare_a(random_triples[0].a);
        b[2].reshare_b(random_triples[0].a);
        a[5].reshare_a(random_triples[1].a);
        b[5].reshare_b(random_triples[1].a);
        a[1].reshare_a(random_triples[2].a);
        b[1].reshare_b(random_triples[2].a);
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 3; }
    bool is_done() const { return level > 2; }

    void compute_step()
    {
        switch(level) {
            case 0:
                p1_L0 = a[2] ^ b[2];  // p1_L0
                p2_L0 = a[3] ^ b[3];  // p2_L0
                p3_L0 = a[4] ^ b[4];  // p3_L0
                p1_W3L1 = a[5] ^ b[5];  // p1_W3L1
                p2_W3L1 = a[6] ^ b[6];  // p2_W3L1
                p1_L1 = a[1] ^ b[1];  // p1_L1
                p0 = a[0] ^ b[0];  // p0
#if RESHARE_OPT_SIM == 1
                a_3_p = a[3].zero_add_local(beaver3_tuples[0].b);  // mask pre-baked; no communication
#else
                a_3_p = a[3].zero_add(beaver3_tuples[0].b);  // a[3]', mask=b1
#endif
                a_4_p = a[4].zero_add(beaver4_tuples[0].c);  // a[4]', mask=c2
#if RESHARE_OPT_SIM == 1
                a_6_p = a[6].zero_add_local(beaver3_tuples[2].b);  // mask pre-baked; no communication
#else
                a_6_p = a[6].zero_add(beaver3_tuples[2].b);  // a[6]', mask=b5
#endif
                a_7_p = a[7].zero_add(beaver4_tuples[1].c);  // a[7]', mask=c6
#if RESHARE_OPT_SIM == 1
                b_3_p = b[3].zero_add_local(beaver3_tuples[0].c);  // mask pre-baked; no communication
#else
                b_3_p = b[3].zero_add(beaver3_tuples[0].c);  // b[3]', mask=c1
#endif
                b_4_p = b[4].zero_add(beaver4_tuples[0].d);  // b[4]', mask=d2
#if RESHARE_OPT_SIM == 1
                b_6_p = b[6].zero_add_local(beaver3_tuples[2].c);  // mask pre-baked; no communication
#else
                b_6_p = b[6].zero_add(beaver3_tuples[2].c);  // b[6]', mask=c5
#endif
                b_7_p = b[7].zero_add(beaver4_tuples[1].d);  // b[7]', mask=d6
                p1_L0_p = p1_L0.zero_add(beaver3_tuples[0].a);  // p1_L0', mask=a1
                p1_L0_p_1 = p1_L0.zero_add(beaver4_tuples[0].a);  // p1_L0'_1, mask=a2
                p1_L0_p_2 = p1_L0.zero_add(beaver3_tuples[1].a);  // p1_L0'_2, mask=a3
                p2_L0_p = p2_L0.zero_add(beaver4_tuples[0].b);  // p2_L0', mask=b2
                p2_L0_p_1 = p2_L0.zero_add(beaver3_tuples[1].b);  // p2_L0'_1, mask=b3
                p3_L0_p = p3_L0.zero_add(beaver3_tuples[1].c);  // p3_L0', mask=c3
                p1_W3L1_p = p1_W3L1.zero_add(beaver3_tuples[2].a);  // p1_W3L1', mask=a5
                p1_W3L1_p_1 = p1_W3L1.zero_add(beaver4_tuples[1].a);  // p1_W3L1'_1, mask=a6
                p2_W3L1_p = p2_W3L1.zero_add(beaver4_tuples[1].b);  // p2_W3L1', mask=b6
                p1_L1_p = p1_L1.zero_add(triples[0].a);  // p1_L1', mask=a8
                p1_L1_p_1 = p1_L1.zero_add(beaver3_tuples[3].a);  // p1_L1'_1, mask=a9
                // and_0: random_triples[0].a, random_triples[0].b, output mask=r24
                g1_L0 = a[2].prepare_dot_reshared(b[2], r24, random_triples[0].b);  // and_0
                // and3_2: a0=beaver3_tuples[0].a, b0=beaver3_tuples[0].b, c0=beaver3_tuples[0].c, output mask=(r23-r24)
                t1_L0 = p1_L0_p.prepare_dot3_and_assign(a_3_p, b_3_p, FUNC_XOR(r23, r24), beaver3_tuples[0]);  // and3_2
                // and4_4: a0=beaver4_tuples[0].a, b0=beaver4_tuples[0].b, c0=beaver4_tuples[0].c, d0=beaver4_tuples[0].d, output mask=(b8-r23)
                t2_L0 = p1_L0_p_1.prepare_dot4_and_assign(p2_L0_p, a_4_p, b_4_p, FUNC_XOR(triples[0].b, r23), beaver4_tuples[0]);  // and4_4
                t3_L0 = g1_L0 ^ t1_L0;  // t3_L0
                v_0 = t3_L0 ^ t2_L0;  // v[0]
                // and_9: random_triples[1].a, random_triples[1].b, output mask=r26
                g1_W3L1 = a[5].prepare_dot_reshared(b[5], r26, random_triples[1].b);  // and_9
                // and3_11: a2=beaver3_tuples[2].a, b2=beaver3_tuples[2].b, c2=beaver3_tuples[2].c, output mask=(r25-r26)
                t1_W3L1 = p1_W3L1_p.prepare_dot3_and_assign(a_6_p, b_6_p, FUNC_XOR(r25, r26), beaver3_tuples[2]);  // and3_11
                // and4_13: a1=beaver4_tuples[1].a, b1=beaver4_tuples[1].b, c1=beaver4_tuples[1].c, d1=beaver4_tuples[1].d, output mask=(c9-r25)
                t2_W3L1 = p1_W3L1_p_1.prepare_dot4_and_assign(p2_W3L1_p, a_7_p, b_7_p, FUNC_XOR(beaver3_tuples[3].c, r25), beaver4_tuples[1]);  // and4_13
                t3_W3L1 = g1_W3L1 ^ t1_W3L1;  // t3_W3L1
                v_2 = t3_W3L1 ^ t2_W3L1;  // v[2]
                break;
            case 1:
                // and_16: random_triples[2].a, random_triples[2].b, output mask=r27
                g1_L1 = a[1].prepare_dot_reshared(b[1], r27, random_triples[2].b);  // and_16
                // and_18: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=r28
                t1_L1 = p1_L1_p.prepare_dot_and_assign(v_0, r28, triples[0].c);  // and_18
                // and3_19: a3=beaver3_tuples[3].a, b3=beaver3_tuples[3].b, c3=beaver3_tuples[3].c, output mask=r29
                t2_L1 = p1_L1_p_1.prepare_dot3_and_assign(v_1, v_2, r29, beaver3_tuples[3]);  // and3_19
                t3_L1 = g1_L1 ^ t1_L1;  // t3_L1
                t4_L1 = t3_L1 ^ t2_L1;  // t4_L1
                break;
            case 2:
                msb = t4_L1 ^ p0;  // msb
                break;
        }
    }

    void aggregate_step()
    {
        switch(level) {
            case 0:
                v_0.mask_and_send_dot_without_remask();
                // and3_8: a1=beaver3_tuples[1].a, b1=beaver3_tuples[1].b, c1=beaver3_tuples[1].c, output mask=b9
                v_1 = p1_L0_p_2.prepare_and3_and_assign(p2_L0_p_1, p3_L0_p, beaver3_tuples[3].b, beaver3_tuples[1]);  // and3_8
                v_2.mask_and_send_dot_without_remask();
                break;
            case 1:
                t4_L1.mask_and_send_dot_without_remask();
                break;
            case 2:
                break;
        }
    }

    void collect_step()
    {
        switch(level) {
            case 0:
                v_0.complete_and();
                v_1.complete_and3();
                v_2.complete_and();
                break;
            case 1:
                t4_L1.complete_and();
                break;
            case 2:
                break;
        }
        level++;
    }
};

// Wire assignment code for PPA_MSB_4Way_AB (16-bit)
// Generated by generate_hpp.py
// Gates: AND2=1, AND3=9, AND4=10, AND_A=0, AND_RESHARED=5, XOR=30, ZERO_ADD=59
// Beaver triples: 1, Beaver3Tuples: 9, Beaver4Tuples: 10, RandomTriples: 5
template <int k, typename Share>
class PPA_MSB_4Way_AB<k, Share, typename std::enable_if<(k == 16)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 16;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& a;
    Bitset& b;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 1;
    triple<DATATYPE> triples[BeaverTripleCount];
    static constexpr int Beaver3TupleCount = 9;
    Beaver3Tuple<DATATYPE> beaver3_tuples[Beaver3TupleCount];
    static constexpr int Beaver4TupleCount = 10;
    Beaver4Tuple<DATATYPE> beaver4_tuples[Beaver4TupleCount];
    static constexpr int RandomTripleCount = 5;
    RandomMultiplication<DATATYPE> random_triples[RandomTripleCount];

    DATATYPE r70;
    DATATYPE r71;
    DATATYPE r72;
    DATATYPE r73;
    DATATYPE r74;
    DATATYPE r75;
    DATATYPE r76;
    DATATYPE r77;
    DATATYPE r78;
    DATATYPE r79;
    DATATYPE r80;
    DATATYPE r81;
    DATATYPE r82;
    DATATYPE r83;
    DATATYPE r84;

    Share B3G_10_12_g1;
    Share B3G_10_12_out;
    Share B3G_10_12_s1;
    Share B3G_10_12_t1;
    Share B3G_10_12_t2;
    Share B3G_1_3_g1;
    Share B3G_1_3_out;
    Share B3G_1_3_s1;
    Share B3G_1_3_t1;
    Share B3G_1_3_t2;
    Share B3G_4_6_g1;
    Share B3G_4_6_out;
    Share B3G_4_6_s1;
    Share B3G_4_6_t1;
    Share B3G_4_6_t2;
    Share B3G_7_9_g1;
    Share B3G_7_9_out;
    Share B3G_7_9_s1;
    Share B3G_7_9_t1;
    Share B3G_7_9_t2;
    Share B3P_1_3_out;
    Share B3P_1_3_out_p;
    Share B3P_1_3_out_p_1;
    Share B3P_4_6_out;
    Share B3P_4_6_out_p;
    Share B3P_7_9_out;
    Share W3L1_13_15_g1;
    Share W3L1_13_15_out;
    Share W3L1_13_15_s1;
    Share W3L1_13_15_t1;
    Share W3L1_13_15_t2;
    Share W5_s1;
    Share W5_s2;
    Share W5_s3;
    Share W5_s4;
    Share W5_t1;
    Share W5_t2;
    Share W5_t3;
    Share W5_t4;
    Share a_11_p;
    Share a_12_p;
    Share a_14_p;
    Share a_15_p;
    Share a_2_p;
    Share a_3_p;
    Share a_5_p;
    Share a_6_p;
    Share a_8_p;
    Share a_9_p;
    Share b_11_p;
    Share b_12_p;
    Share b_14_p;
    Share b_15_p;
    Share b_2_p;
    Share b_3_p;
    Share b_5_p;
    Share b_6_p;
    Share b_8_p;
    Share b_9_p;
    Share p0;
    Share p1234_1;
    Share p1234_2;
    Share p1234_3;
    Share p_10;
    Share p_10_p;
    Share p_10_p_1;
    Share p_10_p_2;
    Share p_11;
    Share p_11_p;
    Share p_11_p_1;
    Share p_12;
    Share p_12_p;
    Share p_13;
    Share p_13_p;
    Share p_13_p_1;
    Share p_14;
    Share p_14_p;
    Share p_1;
    Share p_1_p;
    Share p_1_p_1;
    Share p_1_p_2;
    Share p_1_p_3;
    Share p_2;
    Share p_2_p;
    Share p_2_p_1;
    Share p_2_p_2;
    Share p_3;
    Share p_3_p;
    Share p_3_p_1;
    Share p_4;
    Share p_4_p;
    Share p_4_p_1;
    Share p_4_p_2;
    Share p_4_p_3;
    Share p_5;
    Share p_5_p;
    Share p_5_p_1;
    Share p_5_p_2;
    Share p_6;
    Share p_6_p;
    Share p_6_p_1;
    Share p_7;
    Share p_7_p;
    Share p_7_p_1;
    Share p_7_p_2;
    Share p_7_p_3;
    Share p_8;
    Share p_8_p;
    Share p_8_p_1;
    Share p_8_p_2;
    Share p_9;
    Share p_9_p;
    Share p_9_p_1;

  public:
    PPA_MSB_4Way_AB(Bitset& a_input, Bitset& b_input, Share& msb_output) : a(a_input), b(b_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            for (int i = 0; i < Beaver3TupleCount; ++i)
            {
                beaver3_tuples[i] = retrieveBeaver3Tuple<DATATYPE>();
            }
            for (int i = 0; i < Beaver4TupleCount; ++i)
            {
                beaver4_tuples[i] = retrieveBeaver4Tuple<DATATYPE>();
            }
            for (int i = 0; i < RandomTripleCount; ++i)
            {
                random_triples[i] = retrieveRandomMultiplication<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r70 = getRandomVal(PSELF);
            r71 = getRandomVal(PSELF);
            r72 = getRandomVal(PSELF);
            r73 = getRandomVal(PSELF);
            r74 = getRandomVal(PSELF);
            r75 = getRandomVal(PSELF);
            r76 = getRandomVal(PSELF);
            r77 = getRandomVal(PSELF);
            r78 = getRandomVal(PSELF);
            r79 = getRandomVal(PSELF);
            r80 = getRandomVal(PSELF);
            r81 = getRandomVal(PSELF);
            r82 = getRandomVal(PSELF);
            r83 = getRandomVal(PSELF);
            r84 = getRandomVal(PSELF);

        }
        a[1].reshare_a(random_triples[0].a);
        b[1].reshare_b(random_triples[0].a);
        a[4].reshare_a(random_triples[1].a);
        b[4].reshare_b(random_triples[1].a);
        a[7].reshare_a(random_triples[2].a);
        b[7].reshare_b(random_triples[2].a);
        a[10].reshare_a(random_triples[3].a);
        b[10].reshare_b(random_triples[3].a);
        a[13].reshare_a(random_triples[4].a);
        b[13].reshare_b(random_triples[4].a);
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 3; }
    bool is_done() const { return level > 2; }

    void compute_step()
    {
        switch(level) {
            case 0:
                p_1 = a[1] ^ b[1];  // p[1]
                p_2 = a[2] ^ b[2];  // p[2]
                p_3 = a[3] ^ b[3];  // p[3]
                p_4 = a[4] ^ b[4];  // p[4]
                p_5 = a[5] ^ b[5];  // p[5]
                p_6 = a[6] ^ b[6];  // p[6]
                p_7 = a[7] ^ b[7];  // p[7]
                p_8 = a[8] ^ b[8];  // p[8]
                p_9 = a[9] ^ b[9];  // p[9]
                p_10 = a[10] ^ b[10];  // p[10]
                p_11 = a[11] ^ b[11];  // p[11]
                p_13 = a[13] ^ b[13];  // p[13]
                p_14 = a[14] ^ b[14];  // p[14]
                p_12 = a[12] ^ b[12];  // p[12]
                p0 = a[0] ^ b[0];  // p0
#if RESHARE_OPT_SIM == 1
                a_2_p = a[2].zero_add_local(beaver3_tuples[0].b);  // mask pre-baked; no communication
#else
                a_2_p = a[2].zero_add(beaver3_tuples[0].b);  // a[2]', mask=b1
#endif
                a_3_p = a[3].zero_add(beaver4_tuples[0].c);  // a[3]', mask=c2
#if RESHARE_OPT_SIM == 1
                a_5_p = a[5].zero_add_local(beaver3_tuples[2].b);  // mask pre-baked; no communication
#else
                a_5_p = a[5].zero_add(beaver3_tuples[2].b);  // a[5]', mask=b5
#endif
                a_6_p = a[6].zero_add(beaver4_tuples[1].c);  // a[6]', mask=c6
#if RESHARE_OPT_SIM == 1
                a_8_p = a[8].zero_add_local(beaver3_tuples[4].b);  // mask pre-baked; no communication
#else
                a_8_p = a[8].zero_add(beaver3_tuples[4].b);  // a[8]', mask=b9
#endif
                a_9_p = a[9].zero_add(beaver4_tuples[2].c);  // a[9]', mask=c10
#if RESHARE_OPT_SIM == 1
                a_11_p = a[11].zero_add_local(beaver3_tuples[6].b);  // mask pre-baked; no communication
#else
                a_11_p = a[11].zero_add(beaver3_tuples[6].b);  // a[11]', mask=b13
#endif
                a_12_p = a[12].zero_add(beaver4_tuples[3].c);  // a[12]', mask=c14
#if RESHARE_OPT_SIM == 1
                a_14_p = a[14].zero_add_local(beaver3_tuples[7].b);  // mask pre-baked; no communication
#else
                a_14_p = a[14].zero_add(beaver3_tuples[7].b);  // a[14]', mask=b16
#endif
                a_15_p = a[15].zero_add(beaver4_tuples[4].c);  // a[15]', mask=c17
#if RESHARE_OPT_SIM == 1
                b_2_p = b[2].zero_add_local(beaver3_tuples[0].c);  // mask pre-baked; no communication
#else
                b_2_p = b[2].zero_add(beaver3_tuples[0].c);  // b[2]', mask=c1
#endif
                b_3_p = b[3].zero_add(beaver4_tuples[0].d);  // b[3]', mask=d2
#if RESHARE_OPT_SIM == 1
                b_5_p = b[5].zero_add_local(beaver3_tuples[2].c);  // mask pre-baked; no communication
#else
                b_5_p = b[5].zero_add(beaver3_tuples[2].c);  // b[5]', mask=c5
#endif
                b_6_p = b[6].zero_add(beaver4_tuples[1].d);  // b[6]', mask=d6
#if RESHARE_OPT_SIM == 1
                b_8_p = b[8].zero_add_local(beaver3_tuples[4].c);  // mask pre-baked; no communication
#else
                b_8_p = b[8].zero_add(beaver3_tuples[4].c);  // b[8]', mask=c9
#endif
                b_9_p = b[9].zero_add(beaver4_tuples[2].d);  // b[9]', mask=d10
#if RESHARE_OPT_SIM == 1
                b_11_p = b[11].zero_add_local(beaver3_tuples[6].c);  // mask pre-baked; no communication
#else
                b_11_p = b[11].zero_add(beaver3_tuples[6].c);  // b[11]', mask=c13
#endif
                b_12_p = b[12].zero_add(beaver4_tuples[3].d);  // b[12]', mask=d14
#if RESHARE_OPT_SIM == 1
                b_14_p = b[14].zero_add_local(beaver3_tuples[7].c);  // mask pre-baked; no communication
#else
                b_14_p = b[14].zero_add(beaver3_tuples[7].c);  // b[14]', mask=c16
#endif
                b_15_p = b[15].zero_add(beaver4_tuples[4].d);  // b[15]', mask=d17
                p_1_p = p_1.zero_add(beaver3_tuples[0].a);  // p[1]', mask=a1
                p_1_p_1 = p_1.zero_add(beaver4_tuples[0].a);  // p[1]'_1, mask=a2
                p_1_p_2 = p_1.zero_add(beaver3_tuples[1].a);  // p[1]'_2, mask=a3
                p_1_p_3 = p_1.zero_add(beaver4_tuples[5].a);  // p[1]'_3, mask=a18
                p_2_p = p_2.zero_add(beaver4_tuples[0].b);  // p[2]', mask=b2
                p_2_p_1 = p_2.zero_add(beaver3_tuples[1].b);  // p[2]'_1, mask=b3
                p_2_p_2 = p_2.zero_add(beaver4_tuples[5].b);  // p[2]'_2, mask=b18
                p_3_p = p_3.zero_add(beaver3_tuples[1].c);  // p[3]', mask=c3
                p_3_p_1 = p_3.zero_add(beaver4_tuples[5].c);  // p[3]'_1, mask=c18
                p_4_p = p_4.zero_add(beaver3_tuples[2].a);  // p[4]', mask=a5
                p_4_p_1 = p_4.zero_add(beaver4_tuples[1].a);  // p[4]'_1, mask=a6
                p_4_p_2 = p_4.zero_add(beaver3_tuples[3].a);  // p[4]'_2, mask=a7
                p_4_p_3 = p_4.zero_add(beaver4_tuples[5].d);  // p[4]'_3, mask=d18
                p_5_p = p_5.zero_add(beaver4_tuples[1].b);  // p[5]', mask=b6
                p_5_p_1 = p_5.zero_add(beaver3_tuples[3].b);  // p[5]'_1, mask=b7
                p_5_p_2 = p_5.zero_add(beaver4_tuples[6].a);  // p[5]'_2, mask=a19
                p_6_p = p_6.zero_add(beaver3_tuples[3].c);  // p[6]', mask=c7
                p_6_p_1 = p_6.zero_add(beaver4_tuples[6].b);  // p[6]'_1, mask=b19
                p_7_p = p_7.zero_add(beaver3_tuples[4].a);  // p[7]', mask=a9
                p_7_p_1 = p_7.zero_add(beaver4_tuples[2].a);  // p[7]'_1, mask=a10
                p_7_p_2 = p_7.zero_add(beaver3_tuples[5].a);  // p[7]'_2, mask=a11
                p_7_p_3 = p_7.zero_add(beaver4_tuples[6].c);  // p[7]'_3, mask=c19
                p_8_p = p_8.zero_add(beaver4_tuples[2].b);  // p[8]', mask=b10
                p_8_p_1 = p_8.zero_add(beaver3_tuples[5].b);  // p[8]'_1, mask=b11
                p_8_p_2 = p_8.zero_add(beaver4_tuples[6].d);  // p[8]'_2, mask=d19
                p_9_p = p_9.zero_add(beaver3_tuples[5].c);  // p[9]', mask=c11
                p_9_p_1 = p_9.zero_add(beaver4_tuples[7].a);  // p[9]'_1, mask=a20
                p_10_p = p_10.zero_add(beaver3_tuples[6].a);  // p[10]', mask=a13
                p_10_p_1 = p_10.zero_add(beaver4_tuples[3].a);  // p[10]'_1, mask=a14
                p_10_p_2 = p_10.zero_add(beaver4_tuples[7].b);  // p[10]'_2, mask=b20
                p_11_p = p_11.zero_add(beaver4_tuples[3].b);  // p[11]', mask=b14
                p_11_p_1 = p_11.zero_add(beaver4_tuples[7].c);  // p[11]'_1, mask=c20
                p_13_p = p_13.zero_add(beaver3_tuples[7].a);  // p[13]', mask=a16
                p_13_p_1 = p_13.zero_add(beaver4_tuples[4].a);  // p[13]'_1, mask=a17
                p_14_p = p_14.zero_add(beaver4_tuples[4].b);  // p[14]', mask=b17
                p_12_p = p_12.zero_add(beaver4_tuples[7].d);  // p[12]', mask=d20
                // and_0: random_triples[0].a, random_triples[0].b, output mask=r78
                B3G_1_3_g1 = a[1].prepare_dot_reshared(b[1], r78, random_triples[0].b);  // and_0
                // and3_2: a0=beaver3_tuples[0].a, b0=beaver3_tuples[0].b, c0=beaver3_tuples[0].c, output mask=r79
                B3G_1_3_t1 = p_1_p.prepare_dot3_and_assign(a_2_p, b_2_p, r79, beaver3_tuples[0]);  // and3_2
                // and4_4: a0=beaver4_tuples[0].a, b0=beaver4_tuples[0].b, c0=beaver4_tuples[0].c, d0=beaver4_tuples[0].d, output mask=r80
                B3G_1_3_t2 = p_1_p_1.prepare_dot4_and_assign(p_2_p, a_3_p, b_3_p, r80, beaver4_tuples[0]);  // and4_4
                B3G_1_3_s1 = B3G_1_3_g1 ^ B3G_1_3_t1;  // B3G_1_3_s1
                B3G_1_3_out = B3G_1_3_s1 ^ B3G_1_3_t2;  // B3G_1_3_out
                // and_9: random_triples[1].a, random_triples[1].b, output mask=r71
                B3G_4_6_g1 = a[4].prepare_dot_reshared(b[4], r71, random_triples[1].b);  // and_9
                // and3_11: a2=beaver3_tuples[2].a, b2=beaver3_tuples[2].b, c2=beaver3_tuples[2].c, output mask=(r70-r71)
                B3G_4_6_t1 = p_4_p.prepare_dot3_and_assign(a_5_p, b_5_p, FUNC_XOR(r70, r71), beaver3_tuples[2]);  // and3_11
                // and4_13: a1=beaver4_tuples[1].a, b1=beaver4_tuples[1].b, c1=beaver4_tuples[1].c, d1=beaver4_tuples[1].d, output mask=(b21-r70)
                B3G_4_6_t2 = p_4_p_1.prepare_dot4_and_assign(p_5_p, a_6_p, b_6_p, FUNC_XOR(triples[0].b, r70), beaver4_tuples[1]);  // and4_13
                B3G_4_6_s1 = B3G_4_6_g1 ^ B3G_4_6_t1;  // B3G_4_6_s1
                B3G_4_6_out = B3G_4_6_s1 ^ B3G_4_6_t2;  // B3G_4_6_out
                // and_18: random_triples[2].a, random_triples[2].b, output mask=r73
                B3G_7_9_g1 = a[7].prepare_dot_reshared(b[7], r73, random_triples[2].b);  // and_18
                // and3_20: a4=beaver3_tuples[4].a, b4=beaver3_tuples[4].b, c4=beaver3_tuples[4].c, output mask=(r72-r73)
                B3G_7_9_t1 = p_7_p.prepare_dot3_and_assign(a_8_p, b_8_p, FUNC_XOR(r72, r73), beaver3_tuples[4]);  // and3_20
                // and4_22: a2=beaver4_tuples[2].a, b2=beaver4_tuples[2].b, c2=beaver4_tuples[2].c, d2=beaver4_tuples[2].d, output mask=(c22-r72)
                B3G_7_9_t2 = p_7_p_1.prepare_dot4_and_assign(p_8_p, a_9_p, b_9_p, FUNC_XOR(beaver3_tuples[8].c, r72), beaver4_tuples[2]);  // and4_22
                B3G_7_9_s1 = B3G_7_9_g1 ^ B3G_7_9_t1;  // B3G_7_9_s1
                B3G_7_9_out = B3G_7_9_s1 ^ B3G_7_9_t2;  // B3G_7_9_out
                // and_27: random_triples[3].a, random_triples[3].b, output mask=r75
                B3G_10_12_g1 = a[10].prepare_dot_reshared(b[10], r75, random_triples[3].b);  // and_27
                // and3_29: a6=beaver3_tuples[6].a, b6=beaver3_tuples[6].b, c6=beaver3_tuples[6].c, output mask=(r74-r75)
                B3G_10_12_t1 = p_10_p.prepare_dot3_and_assign(a_11_p, b_11_p, FUNC_XOR(r74, r75), beaver3_tuples[6]);  // and3_29
                // and4_31: a3=beaver4_tuples[3].a, b3=beaver4_tuples[3].b, c3=beaver4_tuples[3].c, d3=beaver4_tuples[3].d, output mask=(d23-r74)
                B3G_10_12_t2 = p_10_p_1.prepare_dot4_and_assign(p_11_p, a_12_p, b_12_p, FUNC_XOR(beaver4_tuples[8].d, r74), beaver4_tuples[3]);  // and4_31
                B3G_10_12_s1 = B3G_10_12_g1 ^ B3G_10_12_t1;  // B3G_10_12_s1
                B3G_10_12_out = B3G_10_12_s1 ^ B3G_10_12_t2;  // B3G_10_12_out
                // and_34: random_triples[4].a, random_triples[4].b, output mask=r77
                W3L1_13_15_g1 = a[13].prepare_dot_reshared(b[13], r77, random_triples[4].b);  // and_34
                // and3_36: a7=beaver3_tuples[7].a, b7=beaver3_tuples[7].b, c7=beaver3_tuples[7].c, output mask=(r76-r77)
                W3L1_13_15_t1 = p_13_p.prepare_dot3_and_assign(a_14_p, b_14_p, FUNC_XOR(r76, r77), beaver3_tuples[7]);  // and3_36
                // and4_38: a4=beaver4_tuples[4].a, b4=beaver4_tuples[4].b, c4=beaver4_tuples[4].c, d4=beaver4_tuples[4].d, output mask=(d24-r76)
                W3L1_13_15_t2 = p_13_p_1.prepare_dot4_and_assign(p_14_p, a_15_p, b_15_p, FUNC_XOR(beaver4_tuples[9].d, r76), beaver4_tuples[4]);  // and4_38
                W3L1_13_15_s1 = W3L1_13_15_g1 ^ W3L1_13_15_t1;  // W3L1_13_15_s1
                W3L1_13_15_out = W3L1_13_15_s1 ^ W3L1_13_15_t2;  // W3L1_13_15_out
                break;
            case 1:
                B3P_1_3_out_p = B3P_1_3_out.zero_add(triples[0].a);  // B3P_1_3_out', mask=a21
                B3P_1_3_out_p_1 = B3P_1_3_out.zero_add(beaver3_tuples[8].a);  // B3P_1_3_out'_1, mask=a22
                B3P_4_6_out_p = B3P_4_6_out.zero_add(beaver3_tuples[8].b);  // B3P_4_6_out', mask=b22
                // and_45: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=r81
                W5_t1 = B3P_1_3_out_p.prepare_dot_and_assign(B3G_4_6_out, r81, triples[0].c);  // and_45
                // and3_46: a8=beaver3_tuples[8].a, b8=beaver3_tuples[8].b, c8=beaver3_tuples[8].c, output mask=r82
                W5_t2 = B3P_1_3_out_p_1.prepare_dot3_and_assign(B3P_4_6_out_p, B3G_7_9_out, r82, beaver3_tuples[8]);  // and3_46
                // and4_47: a8=beaver4_tuples[8].a, b8=beaver4_tuples[8].b, c8=beaver4_tuples[8].c, d8=beaver4_tuples[8].d, output mask=r83
                W5_t3 = B3P_1_3_out.prepare_dot4_and_assign(B3P_4_6_out, B3P_7_9_out, B3G_10_12_out, r83, beaver4_tuples[8]);  // and4_47
                // and4_48: a9=beaver4_tuples[9].a, b9=beaver4_tuples[9].b, c9=beaver4_tuples[9].c, d9=beaver4_tuples[9].d, output mask=r84
                W5_t4 = p1234_1.prepare_dot4_and_assign(p1234_2, p1234_3, W3L1_13_15_out, r84, beaver4_tuples[9]);  // and4_48
                W5_s1 = W5_t1 ^ W5_t2;  // W5_s1
                W5_s2 = W5_s1 ^ W5_t3;  // W5_s2
                W5_s3 = W5_s2 ^ W5_t4;  // W5_s3
                break;
            case 2:
                W5_s4 = W5_s3 ^ B3G_1_3_out;  // W5_s4
                msb = W5_s4 ^ p0;  // msb
                break;
        }
    }

    void aggregate_step()
    {
        switch(level) {
            case 0:
                B3G_1_3_out.mask_and_send_dot_without_remask();
                // and3_8: a1=beaver3_tuples[1].a, b1=beaver3_tuples[1].b, c1=beaver3_tuples[1].c, output mask=a23
                B3P_1_3_out = p_1_p_2.prepare_and3_and_assign(p_2_p_1, p_3_p, beaver4_tuples[8].a, beaver3_tuples[1]);  // and3_8
                B3G_4_6_out.mask_and_send_dot_without_remask();
                // and3_17: a3=beaver3_tuples[3].a, b3=beaver3_tuples[3].b, c3=beaver3_tuples[3].c, output mask=b23
                B3P_4_6_out = p_4_p_2.prepare_and3_and_assign(p_5_p_1, p_6_p, beaver4_tuples[8].b, beaver3_tuples[3]);  // and3_17
                B3G_7_9_out.mask_and_send_dot_without_remask();
                // and3_26: a5=beaver3_tuples[5].a, b5=beaver3_tuples[5].b, c5=beaver3_tuples[5].c, output mask=c23
                B3P_7_9_out = p_7_p_2.prepare_and3_and_assign(p_8_p_1, p_9_p, beaver4_tuples[8].c, beaver3_tuples[5]);  // and3_26
                B3G_10_12_out.mask_and_send_dot_without_remask();
                W3L1_13_15_out.mask_and_send_dot_without_remask();
                // and4_41: a5=beaver4_tuples[5].a, b5=beaver4_tuples[5].b, c5=beaver4_tuples[5].c, d5=beaver4_tuples[5].d, output mask=a24
                p1234_1 = p_1_p_3.prepare_and4_and_assign(p_2_p_2, p_3_p_1, p_4_p_3, beaver4_tuples[9].a, beaver4_tuples[5]);  // and4_41
                // and4_42: a6=beaver4_tuples[6].a, b6=beaver4_tuples[6].b, c6=beaver4_tuples[6].c, d6=beaver4_tuples[6].d, output mask=b24
                p1234_2 = p_5_p_2.prepare_and4_and_assign(p_6_p_1, p_7_p_3, p_8_p_2, beaver4_tuples[9].b, beaver4_tuples[6]);  // and4_42
                // and4_44: a7=beaver4_tuples[7].a, b7=beaver4_tuples[7].b, c7=beaver4_tuples[7].c, d7=beaver4_tuples[7].d, output mask=c24
                p1234_3 = p_9_p_1.prepare_and4_and_assign(p_10_p_2, p_11_p_1, p_12_p, beaver4_tuples[9].c, beaver4_tuples[7]);  // and4_44
                break;
            case 1:
                W5_s3.mask_and_send_dot_without_remask();
                break;
            case 2:
                break;
        }
    }

    void collect_step()
    {
        switch(level) {
            case 0:
                B3G_1_3_out.complete_and();
                B3P_1_3_out.complete_and3();
                B3G_4_6_out.complete_and();
                B3P_4_6_out.complete_and3();
                B3G_7_9_out.complete_and();
                B3P_7_9_out.complete_and3();
                B3G_10_12_out.complete_and();
                W3L1_13_15_out.complete_and();
                p1234_1.complete_and4();
                p1234_2.complete_and4();
                p1234_3.complete_and4();
                break;
            case 1:
                W5_s3.complete_and();
                break;
            case 2:
                break;
        }
        level++;
    }
};

// Wire assignment code for PPA_MSB_4Way_AB (32-bit)
// Generated by generate_hpp.py
// Gates: AND2=4, AND3=24, AND4=13, AND_A=0, AND_RESHARED=11, XOR=62, ZERO_ADD=111
// Beaver triples: 4, Beaver3Tuples: 24, Beaver4Tuples: 13, RandomTriples: 11
template <int k, typename Share>
class PPA_MSB_4Way_AB<k, Share, typename std::enable_if<(k == 32)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 32;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& a;
    Bitset& b;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 4;
    triple<DATATYPE> triples[BeaverTripleCount];
    static constexpr int Beaver3TupleCount = 24;
    Beaver3Tuple<DATATYPE> beaver3_tuples[Beaver3TupleCount];
    static constexpr int Beaver4TupleCount = 13;
    Beaver4Tuple<DATATYPE> beaver4_tuples[Beaver4TupleCount];
    static constexpr int RandomTripleCount = 11;
    RandomMultiplication<DATATYPE> random_triples[RandomTripleCount];

    DATATYPE r133;
    DATATYPE r134;
    DATATYPE r135;
    DATATYPE r136;
    DATATYPE r137;
    DATATYPE r138;
    DATATYPE r139;
    DATATYPE r140;
    DATATYPE r141;
    DATATYPE r142;
    DATATYPE r143;
    DATATYPE r144;
    DATATYPE r145;
    DATATYPE r146;
    DATATYPE r147;
    DATATYPE r148;
    DATATYPE r149;
    DATATYPE r150;
    DATATYPE r151;
    DATATYPE r152;
    DATATYPE r153;
    DATATYPE r154;
    DATATYPE r155;
    DATATYPE r156;
    DATATYPE r157;
    DATATYPE r158;
    DATATYPE r159;
    DATATYPE r160;
    DATATYPE r161;
    DATATYPE r162;
    DATATYPE r163;

    Share B3G_10_12_g1;
    Share B3G_10_12_out;
    Share B3G_10_12_s1;
    Share B3G_10_12_t1;
    Share B3G_10_12_t2;
    Share B3G_13_15_g1;
    Share B3G_13_15_out;
    Share B3G_13_15_s1;
    Share B3G_13_15_t1;
    Share B3G_13_15_t2;
    Share B3G_16_18_g1;
    Share B3G_16_18_out;
    Share B3G_16_18_s1;
    Share B3G_16_18_t1;
    Share B3G_16_18_t2;
    Share B3G_19_21_g1;
    Share B3G_19_21_out;
    Share B3G_19_21_s1;
    Share B3G_19_21_t1;
    Share B3G_19_21_t2;
    Share B3G_1_3_g1;
    Share B3G_1_3_out;
    Share B3G_1_3_s1;
    Share B3G_1_3_t1;
    Share B3G_1_3_t2;
    Share B3G_23_25_g1;
    Share B3G_23_25_out;
    Share B3G_23_25_s1;
    Share B3G_23_25_t1;
    Share B3G_23_25_t2;
    Share B3G_26_28_g1;
    Share B3G_26_28_out;
    Share B3G_26_28_s1;
    Share B3G_26_28_t1;
    Share B3G_26_28_t2;
    Share B3G_4_6_g1;
    Share B3G_4_6_out;
    Share B3G_4_6_s1;
    Share B3G_4_6_t1;
    Share B3G_4_6_t2;
    Share B3G_7_9_g1;
    Share B3G_7_9_out;
    Share B3G_7_9_s1;
    Share B3G_7_9_t1;
    Share B3G_7_9_t2;
    Share B3P_10_12_out;
    Share B3P_10_12_out_p;
    Share B3P_10_12_out_p_1;
    Share B3P_10_12_out_p_2;
    Share B3P_13_15_out;
    Share B3P_13_15_out_p;
    Share B3P_13_15_out_p_1;
    Share B3P_16_18_out;
    Share B3P_16_18_out_p;
    Share B3P_19_21_out;
    Share B3P_1_3_out;
    Share B3P_1_3_out_p;
    Share B3P_1_3_out_p_1;
    Share B3P_23_25_out;
    Share B3P_23_25_out_p;
    Share B3P_26_28_out;
    Share B3P_4_6_out;
    Share B3P_4_6_out_p;
    Share B3P_7_9_out;
    Share L1_B3G_out;
    Share L1_B3G_s1;
    Share L1_B3G_t1;
    Share L1_B3G_t2;
    Share L1_B3P_out;
    Share L1_B3P_out_p;
    Share L1_B4G_out;
    Share L1_B4G_s1;
    Share L1_B4G_s2;
    Share L1_B4G_t1;
    Share L1_B4G_t2;
    Share L1_B4G_t3;
    Share L1_B4P_out;
    Share L1_W4S_g1;
    Share L1_W4S_out;
    Share L1_W4S_s1;
    Share L1_W4S_s2;
    Share L1_W4S_t1;
    Share L1_W4S_t2;
    Share L1_W4S_t3;
    Share L2_W3_s1;
    Share L2_W3_s2;
    Share L2_W3_t1;
    Share L2_W3_t2;
    Share W3L1_29_31_g1;
    Share W3L1_29_31_out;
    Share W3L1_29_31_s1;
    Share W3L1_29_31_t1;
    Share W3L1_29_31_t2;
    Share a_11_p;
    Share a_12_p;
    Share a_14_p;
    Share a_15_p;
    Share a_17_p;
    Share a_18_p;
    Share a_20_p;
    Share a_21_p;
    Share a_24_p;
    Share a_25_p;
    Share a_27_p;
    Share a_28_p;
    Share a_2_p;
    Share a_30_p;
    Share a_31_p;
    Share a_3_p;
    Share a_5_p;
    Share a_6_p;
    Share a_8_p;
    Share a_9_p;
    Share b_11_p;
    Share b_12_p;
    Share b_14_p;
    Share b_15_p;
    Share b_17_p;
    Share b_18_p;
    Share b_20_p;
    Share b_21_p;
    Share b_24_p;
    Share b_25_p;
    Share b_27_p;
    Share b_28_p;
    Share b_2_p;
    Share b_30_p;
    Share b_31_p;
    Share b_3_p;
    Share b_5_p;
    Share b_6_p;
    Share b_8_p;
    Share b_9_p;
    Share p0;
    Share p_10;
    Share p_10_p;
    Share p_10_p_1;
    Share p_10_p_2;
    Share p_11;
    Share p_11_p;
    Share p_11_p_1;
    Share p_12;
    Share p_12_p;
    Share p_13;
    Share p_13_p;
    Share p_13_p_1;
    Share p_13_p_2;
    Share p_14;
    Share p_14_p;
    Share p_14_p_1;
    Share p_15;
    Share p_15_p;
    Share p_16;
    Share p_16_p;
    Share p_16_p_1;
    Share p_16_p_2;
    Share p_17;
    Share p_17_p;
    Share p_17_p_1;
    Share p_18;
    Share p_18_p;
    Share p_19;
    Share p_19_p;
    Share p_19_p_1;
    Share p_19_p_2;
    Share p_1;
    Share p_1_p;
    Share p_1_p_1;
    Share p_1_p_2;
    Share p_20;
    Share p_20_p;
    Share p_20_p_1;
    Share p_21;
    Share p_21_p;
    Share p_22;
    Share p_22_p;
    Share p_22_p_1;
    Share p_22_p_2;
    Share p_23;
    Share p_23_p;
    Share p_23_p_1;
    Share p_23_p_2;
    Share p_24;
    Share p_24_p;
    Share p_24_p_1;
    Share p_25;
    Share p_25_p;
    Share p_26;
    Share p_26_p;
    Share p_26_p_1;
    Share p_26_p_2;
    Share p_27;
    Share p_27_p;
    Share p_27_p_1;
    Share p_28;
    Share p_28_p;
    Share p_29;
    Share p_29_p;
    Share p_29_p_1;
    Share p_2;
    Share p_2_p;
    Share p_2_p_1;
    Share p_30;
    Share p_30_p;
    Share p_3;
    Share p_3_p;
    Share p_4;
    Share p_4_p;
    Share p_4_p_1;
    Share p_4_p_2;
    Share p_5;
    Share p_5_p;
    Share p_5_p_1;
    Share p_6;
    Share p_6_p;
    Share p_7;
    Share p_7_p;
    Share p_7_p_1;
    Share p_7_p_2;
    Share p_8;
    Share p_8_p;
    Share p_8_p_1;
    Share p_9;
    Share p_9_p;

  public:
    PPA_MSB_4Way_AB(Bitset& a_input, Bitset& b_input, Share& msb_output) : a(a_input), b(b_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            for (int i = 0; i < Beaver3TupleCount; ++i)
            {
                beaver3_tuples[i] = retrieveBeaver3Tuple<DATATYPE>();
            }
            for (int i = 0; i < Beaver4TupleCount; ++i)
            {
                beaver4_tuples[i] = retrieveBeaver4Tuple<DATATYPE>();
            }
            for (int i = 0; i < RandomTripleCount; ++i)
            {
                random_triples[i] = retrieveRandomMultiplication<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r133 = getRandomVal(PSELF);
            r134 = getRandomVal(PSELF);
            r135 = getRandomVal(PSELF);
            r136 = getRandomVal(PSELF);
            r137 = getRandomVal(PSELF);
            r138 = getRandomVal(PSELF);
            r139 = getRandomVal(PSELF);
            r140 = getRandomVal(PSELF);
            r141 = getRandomVal(PSELF);
            r142 = getRandomVal(PSELF);
            r143 = getRandomVal(PSELF);
            r144 = getRandomVal(PSELF);
            r145 = getRandomVal(PSELF);
            r146 = getRandomVal(PSELF);
            r147 = getRandomVal(PSELF);
            r148 = getRandomVal(PSELF);
            r149 = getRandomVal(PSELF);
            r150 = getRandomVal(PSELF);
            r151 = getRandomVal(PSELF);
            r152 = getRandomVal(PSELF);
            r153 = getRandomVal(PSELF);
            r154 = getRandomVal(PSELF);
            r155 = getRandomVal(PSELF);
            r156 = getRandomVal(PSELF);
            r157 = getRandomVal(PSELF);
            r158 = getRandomVal(PSELF);
            r159 = getRandomVal(PSELF);
            r160 = getRandomVal(PSELF);
            r161 = getRandomVal(PSELF);
            r162 = getRandomVal(PSELF);
            r163 = getRandomVal(PSELF);

        }
        a[1].reshare_a(random_triples[0].a);
        b[1].reshare_b(random_triples[0].a);
        a[4].reshare_a(random_triples[1].a);
        b[4].reshare_b(random_triples[1].a);
        a[7].reshare_a(random_triples[2].a);
        b[7].reshare_b(random_triples[2].a);
        a[10].reshare_a(random_triples[3].a);
        b[10].reshare_b(random_triples[3].a);
        a[13].reshare_a(random_triples[4].a);
        b[13].reshare_b(random_triples[4].a);
        a[16].reshare_a(random_triples[5].a);
        b[16].reshare_b(random_triples[5].a);
        a[19].reshare_a(random_triples[6].a);
        b[19].reshare_b(random_triples[6].a);
        a[23].reshare_a(random_triples[7].a);
        b[23].reshare_b(random_triples[7].a);
        a[26].reshare_a(random_triples[8].a);
        b[26].reshare_b(random_triples[8].a);
        a[29].reshare_a(random_triples[9].a);
        b[29].reshare_b(random_triples[9].a);
        a[22].reshare_a(random_triples[10].a);
        b[22].reshare_b(random_triples[10].a);
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 4; }
    bool is_done() const { return level > 3; }

    void compute_step()
    {
        switch(level) {
            case 0:
                p_1 = a[1] ^ b[1];  // p[1]
                p_2 = a[2] ^ b[2];  // p[2]
                p_3 = a[3] ^ b[3];  // p[3]
                p_4 = a[4] ^ b[4];  // p[4]
                p_5 = a[5] ^ b[5];  // p[5]
                p_6 = a[6] ^ b[6];  // p[6]
                p_7 = a[7] ^ b[7];  // p[7]
                p_8 = a[8] ^ b[8];  // p[8]
                p_9 = a[9] ^ b[9];  // p[9]
                p_10 = a[10] ^ b[10];  // p[10]
                p_11 = a[11] ^ b[11];  // p[11]
                p_12 = a[12] ^ b[12];  // p[12]
                p_13 = a[13] ^ b[13];  // p[13]
                p_14 = a[14] ^ b[14];  // p[14]
                p_15 = a[15] ^ b[15];  // p[15]
                p_16 = a[16] ^ b[16];  // p[16]
                p_17 = a[17] ^ b[17];  // p[17]
                p_18 = a[18] ^ b[18];  // p[18]
                p_19 = a[19] ^ b[19];  // p[19]
                p_20 = a[20] ^ b[20];  // p[20]
                p_21 = a[21] ^ b[21];  // p[21]
                p_23 = a[23] ^ b[23];  // p[23]
                p_24 = a[24] ^ b[24];  // p[24]
                p_25 = a[25] ^ b[25];  // p[25]
                p_26 = a[26] ^ b[26];  // p[26]
                p_27 = a[27] ^ b[27];  // p[27]
                p_28 = a[28] ^ b[28];  // p[28]
                p_29 = a[29] ^ b[29];  // p[29]
                p_30 = a[30] ^ b[30];  // p[30]
                p_22 = a[22] ^ b[22];  // p[22]
                p0 = a[0] ^ b[0];  // p0
#if RESHARE_OPT_SIM == 1
                a_2_p = a[2].zero_add_local(beaver3_tuples[0].b);  // mask pre-baked; no communication
#else
                a_2_p = a[2].zero_add(beaver3_tuples[0].b);  // a[2]', mask=b1
#endif
                a_3_p = a[3].zero_add(beaver4_tuples[0].c);  // a[3]', mask=c2
#if RESHARE_OPT_SIM == 1
                a_5_p = a[5].zero_add_local(beaver3_tuples[2].b);  // mask pre-baked; no communication
#else
                a_5_p = a[5].zero_add(beaver3_tuples[2].b);  // a[5]', mask=b5
#endif
                a_6_p = a[6].zero_add(beaver4_tuples[1].c);  // a[6]', mask=c6
#if RESHARE_OPT_SIM == 1
                a_8_p = a[8].zero_add_local(beaver3_tuples[4].b);  // mask pre-baked; no communication
#else
                a_8_p = a[8].zero_add(beaver3_tuples[4].b);  // a[8]', mask=b9
#endif
                a_9_p = a[9].zero_add(beaver4_tuples[2].c);  // a[9]', mask=c10
#if RESHARE_OPT_SIM == 1
                a_11_p = a[11].zero_add_local(beaver3_tuples[6].b);  // mask pre-baked; no communication
#else
                a_11_p = a[11].zero_add(beaver3_tuples[6].b);  // a[11]', mask=b13
#endif
                a_12_p = a[12].zero_add(beaver4_tuples[3].c);  // a[12]', mask=c14
#if RESHARE_OPT_SIM == 1
                a_14_p = a[14].zero_add_local(beaver3_tuples[8].b);  // mask pre-baked; no communication
#else
                a_14_p = a[14].zero_add(beaver3_tuples[8].b);  // a[14]', mask=b17
#endif
                a_15_p = a[15].zero_add(beaver4_tuples[4].c);  // a[15]', mask=c18
#if RESHARE_OPT_SIM == 1
                a_17_p = a[17].zero_add_local(beaver3_tuples[10].b);  // mask pre-baked; no communication
#else
                a_17_p = a[17].zero_add(beaver3_tuples[10].b);  // a[17]', mask=b21
#endif
                a_18_p = a[18].zero_add(beaver4_tuples[5].c);  // a[18]', mask=c22
#if RESHARE_OPT_SIM == 1
                a_20_p = a[20].zero_add_local(beaver3_tuples[12].b);  // mask pre-baked; no communication
#else
                a_20_p = a[20].zero_add(beaver3_tuples[12].b);  // a[20]', mask=b25
#endif
                a_21_p = a[21].zero_add(beaver4_tuples[6].c);  // a[21]', mask=c26
#if RESHARE_OPT_SIM == 1
                a_24_p = a[24].zero_add_local(beaver3_tuples[14].b);  // mask pre-baked; no communication
#else
                a_24_p = a[24].zero_add(beaver3_tuples[14].b);  // a[24]', mask=b29
#endif
                a_25_p = a[25].zero_add(beaver4_tuples[7].c);  // a[25]', mask=c30
#if RESHARE_OPT_SIM == 1
                a_27_p = a[27].zero_add_local(beaver3_tuples[16].b);  // mask pre-baked; no communication
#else
                a_27_p = a[27].zero_add(beaver3_tuples[16].b);  // a[27]', mask=b33
#endif
                a_28_p = a[28].zero_add(beaver4_tuples[8].c);  // a[28]', mask=c34
#if RESHARE_OPT_SIM == 1
                a_30_p = a[30].zero_add_local(beaver3_tuples[18].b);  // mask pre-baked; no communication
#else
                a_30_p = a[30].zero_add(beaver3_tuples[18].b);  // a[30]', mask=b37
#endif
                a_31_p = a[31].zero_add(beaver4_tuples[9].c);  // a[31]', mask=c38
#if RESHARE_OPT_SIM == 1
                b_2_p = b[2].zero_add_local(beaver3_tuples[0].c);  // mask pre-baked; no communication
#else
                b_2_p = b[2].zero_add(beaver3_tuples[0].c);  // b[2]', mask=c1
#endif
                b_3_p = b[3].zero_add(beaver4_tuples[0].d);  // b[3]', mask=d2
#if RESHARE_OPT_SIM == 1
                b_5_p = b[5].zero_add_local(beaver3_tuples[2].c);  // mask pre-baked; no communication
#else
                b_5_p = b[5].zero_add(beaver3_tuples[2].c);  // b[5]', mask=c5
#endif
                b_6_p = b[6].zero_add(beaver4_tuples[1].d);  // b[6]', mask=d6
#if RESHARE_OPT_SIM == 1
                b_8_p = b[8].zero_add_local(beaver3_tuples[4].c);  // mask pre-baked; no communication
#else
                b_8_p = b[8].zero_add(beaver3_tuples[4].c);  // b[8]', mask=c9
#endif
                b_9_p = b[9].zero_add(beaver4_tuples[2].d);  // b[9]', mask=d10
#if RESHARE_OPT_SIM == 1
                b_11_p = b[11].zero_add_local(beaver3_tuples[6].c);  // mask pre-baked; no communication
#else
                b_11_p = b[11].zero_add(beaver3_tuples[6].c);  // b[11]', mask=c13
#endif
                b_12_p = b[12].zero_add(beaver4_tuples[3].d);  // b[12]', mask=d14
#if RESHARE_OPT_SIM == 1
                b_14_p = b[14].zero_add_local(beaver3_tuples[8].c);  // mask pre-baked; no communication
#else
                b_14_p = b[14].zero_add(beaver3_tuples[8].c);  // b[14]', mask=c17
#endif
                b_15_p = b[15].zero_add(beaver4_tuples[4].d);  // b[15]', mask=d18
#if RESHARE_OPT_SIM == 1
                b_17_p = b[17].zero_add_local(beaver3_tuples[10].c);  // mask pre-baked; no communication
#else
                b_17_p = b[17].zero_add(beaver3_tuples[10].c);  // b[17]', mask=c21
#endif
                b_18_p = b[18].zero_add(beaver4_tuples[5].d);  // b[18]', mask=d22
#if RESHARE_OPT_SIM == 1
                b_20_p = b[20].zero_add_local(beaver3_tuples[12].c);  // mask pre-baked; no communication
#else
                b_20_p = b[20].zero_add(beaver3_tuples[12].c);  // b[20]', mask=c25
#endif
                b_21_p = b[21].zero_add(beaver4_tuples[6].d);  // b[21]', mask=d26
#if RESHARE_OPT_SIM == 1
                b_24_p = b[24].zero_add_local(beaver3_tuples[14].c);  // mask pre-baked; no communication
#else
                b_24_p = b[24].zero_add(beaver3_tuples[14].c);  // b[24]', mask=c29
#endif
                b_25_p = b[25].zero_add(beaver4_tuples[7].d);  // b[25]', mask=d30
#if RESHARE_OPT_SIM == 1
                b_27_p = b[27].zero_add_local(beaver3_tuples[16].c);  // mask pre-baked; no communication
#else
                b_27_p = b[27].zero_add(beaver3_tuples[16].c);  // b[27]', mask=c33
#endif
                b_28_p = b[28].zero_add(beaver4_tuples[8].d);  // b[28]', mask=d34
#if RESHARE_OPT_SIM == 1
                b_30_p = b[30].zero_add_local(beaver3_tuples[18].c);  // mask pre-baked; no communication
#else
                b_30_p = b[30].zero_add(beaver3_tuples[18].c);  // b[30]', mask=c37
#endif
                b_31_p = b[31].zero_add(beaver4_tuples[9].d);  // b[31]', mask=d38
                p_1_p = p_1.zero_add(beaver3_tuples[0].a);  // p[1]', mask=a1
                p_1_p_1 = p_1.zero_add(beaver4_tuples[0].a);  // p[1]'_1, mask=a2
                p_1_p_2 = p_1.zero_add(beaver3_tuples[1].a);  // p[1]'_2, mask=a3
                p_2_p = p_2.zero_add(beaver4_tuples[0].b);  // p[2]', mask=b2
                p_2_p_1 = p_2.zero_add(beaver3_tuples[1].b);  // p[2]'_1, mask=b3
                p_3_p = p_3.zero_add(beaver3_tuples[1].c);  // p[3]', mask=c3
                p_4_p = p_4.zero_add(beaver3_tuples[2].a);  // p[4]', mask=a5
                p_4_p_1 = p_4.zero_add(beaver4_tuples[1].a);  // p[4]'_1, mask=a6
                p_4_p_2 = p_4.zero_add(beaver3_tuples[3].a);  // p[4]'_2, mask=a7
                p_5_p = p_5.zero_add(beaver4_tuples[1].b);  // p[5]', mask=b6
                p_5_p_1 = p_5.zero_add(beaver3_tuples[3].b);  // p[5]'_1, mask=b7
                p_6_p = p_6.zero_add(beaver3_tuples[3].c);  // p[6]', mask=c7
                p_7_p = p_7.zero_add(beaver3_tuples[4].a);  // p[7]', mask=a9
                p_7_p_1 = p_7.zero_add(beaver4_tuples[2].a);  // p[7]'_1, mask=a10
                p_7_p_2 = p_7.zero_add(beaver3_tuples[5].a);  // p[7]'_2, mask=a11
                p_8_p = p_8.zero_add(beaver4_tuples[2].b);  // p[8]', mask=b10
                p_8_p_1 = p_8.zero_add(beaver3_tuples[5].b);  // p[8]'_1, mask=b11
                p_9_p = p_9.zero_add(beaver3_tuples[5].c);  // p[9]', mask=c11
                p_10_p = p_10.zero_add(beaver3_tuples[6].a);  // p[10]', mask=a13
                p_10_p_1 = p_10.zero_add(beaver4_tuples[3].a);  // p[10]'_1, mask=a14
                p_10_p_2 = p_10.zero_add(beaver3_tuples[7].a);  // p[10]'_2, mask=a15
                p_11_p = p_11.zero_add(beaver4_tuples[3].b);  // p[11]', mask=b14
                p_11_p_1 = p_11.zero_add(beaver3_tuples[7].b);  // p[11]'_1, mask=b15
                p_12_p = p_12.zero_add(beaver3_tuples[7].c);  // p[12]', mask=c15
                p_13_p = p_13.zero_add(beaver3_tuples[8].a);  // p[13]', mask=a17
                p_13_p_1 = p_13.zero_add(beaver4_tuples[4].a);  // p[13]'_1, mask=a18
                p_13_p_2 = p_13.zero_add(beaver3_tuples[9].a);  // p[13]'_2, mask=a19
                p_14_p = p_14.zero_add(beaver4_tuples[4].b);  // p[14]', mask=b18
                p_14_p_1 = p_14.zero_add(beaver3_tuples[9].b);  // p[14]'_1, mask=b19
                p_15_p = p_15.zero_add(beaver3_tuples[9].c);  // p[15]', mask=c19
                p_16_p = p_16.zero_add(beaver3_tuples[10].a);  // p[16]', mask=a21
                p_16_p_1 = p_16.zero_add(beaver4_tuples[5].a);  // p[16]'_1, mask=a22
                p_16_p_2 = p_16.zero_add(beaver3_tuples[11].a);  // p[16]'_2, mask=a23
                p_17_p = p_17.zero_add(beaver4_tuples[5].b);  // p[17]', mask=b22
                p_17_p_1 = p_17.zero_add(beaver3_tuples[11].b);  // p[17]'_1, mask=b23
                p_18_p = p_18.zero_add(beaver3_tuples[11].c);  // p[18]', mask=c23
                p_19_p = p_19.zero_add(beaver3_tuples[12].a);  // p[19]', mask=a25
                p_19_p_1 = p_19.zero_add(beaver4_tuples[6].a);  // p[19]'_1, mask=a26
                p_19_p_2 = p_19.zero_add(beaver3_tuples[13].a);  // p[19]'_2, mask=a27
                p_20_p = p_20.zero_add(beaver4_tuples[6].b);  // p[20]', mask=b26
                p_20_p_1 = p_20.zero_add(beaver3_tuples[13].b);  // p[20]'_1, mask=b27
                p_21_p = p_21.zero_add(beaver3_tuples[13].c);  // p[21]', mask=c27
                p_23_p = p_23.zero_add(beaver3_tuples[14].a);  // p[23]', mask=a29
                p_23_p_1 = p_23.zero_add(beaver4_tuples[7].a);  // p[23]'_1, mask=a30
                p_23_p_2 = p_23.zero_add(beaver3_tuples[15].a);  // p[23]'_2, mask=a31
                p_24_p = p_24.zero_add(beaver4_tuples[7].b);  // p[24]', mask=b30
                p_24_p_1 = p_24.zero_add(beaver3_tuples[15].b);  // p[24]'_1, mask=b31
                p_25_p = p_25.zero_add(beaver3_tuples[15].c);  // p[25]', mask=c31
                p_26_p = p_26.zero_add(beaver3_tuples[16].a);  // p[26]', mask=a33
                p_26_p_1 = p_26.zero_add(beaver4_tuples[8].a);  // p[26]'_1, mask=a34
                p_26_p_2 = p_26.zero_add(beaver3_tuples[17].a);  // p[26]'_2, mask=a35
                p_27_p = p_27.zero_add(beaver4_tuples[8].b);  // p[27]', mask=b34
                p_27_p_1 = p_27.zero_add(beaver3_tuples[17].b);  // p[27]'_1, mask=b35
                p_28_p = p_28.zero_add(beaver3_tuples[17].c);  // p[28]', mask=c35
                p_29_p = p_29.zero_add(beaver3_tuples[18].a);  // p[29]', mask=a37
                p_29_p_1 = p_29.zero_add(beaver4_tuples[9].a);  // p[29]'_1, mask=a38
                p_30_p = p_30.zero_add(beaver4_tuples[9].b);  // p[30]', mask=b38
                p_22_p = p_22.zero_add(triples[2].a);  // p[22]', mask=a47
                p_22_p_1 = p_22.zero_add(beaver3_tuples[22].a);  // p[22]'_1, mask=a48
                p_22_p_2 = p_22.zero_add(beaver4_tuples[12].a);  // p[22]'_2, mask=a49
                // and_0: random_triples[0].a, random_triples[0].b, output mask=r157
                B3G_1_3_g1 = a[1].prepare_dot_reshared(b[1], r157, random_triples[0].b);  // and_0
                // and3_2: a0=beaver3_tuples[0].a, b0=beaver3_tuples[0].b, c0=beaver3_tuples[0].c, output mask=r158
                B3G_1_3_t1 = p_1_p.prepare_dot3_and_assign(a_2_p, b_2_p, r158, beaver3_tuples[0]);  // and3_2
                // and4_4: a0=beaver4_tuples[0].a, b0=beaver4_tuples[0].b, c0=beaver4_tuples[0].c, d0=beaver4_tuples[0].d, output mask=r159
                B3G_1_3_t2 = p_1_p_1.prepare_dot4_and_assign(p_2_p, a_3_p, b_3_p, r159, beaver4_tuples[0]);  // and4_4
                B3G_1_3_s1 = B3G_1_3_g1 ^ B3G_1_3_t1;  // B3G_1_3_s1
                B3G_1_3_out = B3G_1_3_s1 ^ B3G_1_3_t2;  // B3G_1_3_out
                // and_9: random_triples[1].a, random_triples[1].b, output mask=r134
                B3G_4_6_g1 = a[4].prepare_dot_reshared(b[4], r134, random_triples[1].b);  // and_9
                // and3_11: a2=beaver3_tuples[2].a, b2=beaver3_tuples[2].b, c2=beaver3_tuples[2].c, output mask=(r133-r134)
                B3G_4_6_t1 = p_4_p.prepare_dot3_and_assign(a_5_p, b_5_p, FUNC_XOR(r133, r134), beaver3_tuples[2]);  // and3_11
                // and4_13: a1=beaver4_tuples[1].a, b1=beaver4_tuples[1].b, c1=beaver4_tuples[1].c, d1=beaver4_tuples[1].d, output mask=(b39-r133)
                B3G_4_6_t2 = p_4_p_1.prepare_dot4_and_assign(p_5_p, a_6_p, b_6_p, FUNC_XOR(triples[0].b, r133), beaver4_tuples[1]);  // and4_13
                B3G_4_6_s1 = B3G_4_6_g1 ^ B3G_4_6_t1;  // B3G_4_6_s1
                B3G_4_6_out = B3G_4_6_s1 ^ B3G_4_6_t2;  // B3G_4_6_out
                // and_18: random_triples[2].a, random_triples[2].b, output mask=r136
                B3G_7_9_g1 = a[7].prepare_dot_reshared(b[7], r136, random_triples[2].b);  // and_18
                // and3_20: a4=beaver3_tuples[4].a, b4=beaver3_tuples[4].b, c4=beaver3_tuples[4].c, output mask=(r135-r136)
                B3G_7_9_t1 = p_7_p.prepare_dot3_and_assign(a_8_p, b_8_p, FUNC_XOR(r135, r136), beaver3_tuples[4]);  // and3_20
                // and4_22: a2=beaver4_tuples[2].a, b2=beaver4_tuples[2].b, c2=beaver4_tuples[2].c, d2=beaver4_tuples[2].d, output mask=(c40-r135)
                B3G_7_9_t2 = p_7_p_1.prepare_dot4_and_assign(p_8_p, a_9_p, b_9_p, FUNC_XOR(beaver3_tuples[19].c, r135), beaver4_tuples[2]);  // and4_22
                B3G_7_9_s1 = B3G_7_9_g1 ^ B3G_7_9_t1;  // B3G_7_9_s1
                B3G_7_9_out = B3G_7_9_s1 ^ B3G_7_9_t2;  // B3G_7_9_out
                // and_27: random_triples[3].a, random_triples[3].b, output mask=r151
                B3G_10_12_g1 = a[10].prepare_dot_reshared(b[10], r151, random_triples[3].b);  // and_27
                // and3_29: a6=beaver3_tuples[6].a, b6=beaver3_tuples[6].b, c6=beaver3_tuples[6].c, output mask=(r150-r151)
                B3G_10_12_t1 = p_10_p.prepare_dot3_and_assign(a_11_p, b_11_p, FUNC_XOR(r150, r151), beaver3_tuples[6]);  // and3_29
                // and4_31: a3=beaver4_tuples[3].a, b3=beaver4_tuples[3].b, c3=beaver4_tuples[3].c, d3=beaver4_tuples[3].d, output mask=((b50-r149)-r150)
                B3G_10_12_t2 = p_10_p_1.prepare_dot4_and_assign(p_11_p, a_12_p, b_12_p, FUNC_XOR(FUNC_XOR(triples[3].b, r149), r150), beaver4_tuples[3]);  // and4_31
                B3G_10_12_s1 = B3G_10_12_g1 ^ B3G_10_12_t1;  // B3G_10_12_s1
                B3G_10_12_out = B3G_10_12_s1 ^ B3G_10_12_t2;  // B3G_10_12_out
                // and_36: random_triples[4].a, random_triples[4].b, output mask=r138
                B3G_13_15_g1 = a[13].prepare_dot_reshared(b[13], r138, random_triples[4].b);  // and_36
                // and3_38: a8=beaver3_tuples[8].a, b8=beaver3_tuples[8].b, c8=beaver3_tuples[8].c, output mask=(r137-r138)
                B3G_13_15_t1 = p_13_p.prepare_dot3_and_assign(a_14_p, b_14_p, FUNC_XOR(r137, r138), beaver3_tuples[8]);  // and3_38
                // and4_40: a4=beaver4_tuples[4].a, b4=beaver4_tuples[4].b, c4=beaver4_tuples[4].c, d4=beaver4_tuples[4].d, output mask=(b42-r137)
                B3G_13_15_t2 = p_13_p_1.prepare_dot4_and_assign(p_14_p, a_15_p, b_15_p, FUNC_XOR(triples[1].b, r137), beaver4_tuples[4]);  // and4_40
                B3G_13_15_s1 = B3G_13_15_g1 ^ B3G_13_15_t1;  // B3G_13_15_s1
                B3G_13_15_out = B3G_13_15_s1 ^ B3G_13_15_t2;  // B3G_13_15_out
                // and_45: random_triples[5].a, random_triples[5].b, output mask=r140
                B3G_16_18_g1 = a[16].prepare_dot_reshared(b[16], r140, random_triples[5].b);  // and_45
                // and3_47: a10=beaver3_tuples[10].a, b10=beaver3_tuples[10].b, c10=beaver3_tuples[10].c, output mask=(r139-r140)
                B3G_16_18_t1 = p_16_p.prepare_dot3_and_assign(a_17_p, b_17_p, FUNC_XOR(r139, r140), beaver3_tuples[10]);  // and3_47
                // and4_49: a5=beaver4_tuples[5].a, b5=beaver4_tuples[5].b, c5=beaver4_tuples[5].c, d5=beaver4_tuples[5].d, output mask=(c43-r139)
                B3G_16_18_t2 = p_16_p_1.prepare_dot4_and_assign(p_17_p, a_18_p, b_18_p, FUNC_XOR(beaver3_tuples[21].c, r139), beaver4_tuples[5]);  // and4_49
                B3G_16_18_s1 = B3G_16_18_g1 ^ B3G_16_18_t1;  // B3G_16_18_s1
                B3G_16_18_out = B3G_16_18_s1 ^ B3G_16_18_t2;  // B3G_16_18_out
                // and_54: random_triples[6].a, random_triples[6].b, output mask=r142
                B3G_19_21_g1 = a[19].prepare_dot_reshared(b[19], r142, random_triples[6].b);  // and_54
                // and3_56: a12=beaver3_tuples[12].a, b12=beaver3_tuples[12].b, c12=beaver3_tuples[12].c, output mask=(r141-r142)
                B3G_19_21_t1 = p_19_p.prepare_dot3_and_assign(a_20_p, b_20_p, FUNC_XOR(r141, r142), beaver3_tuples[12]);  // and3_56
                // and4_58: a6=beaver4_tuples[6].a, b6=beaver4_tuples[6].b, c6=beaver4_tuples[6].c, d6=beaver4_tuples[6].d, output mask=(d44-r141)
                B3G_19_21_t2 = p_19_p_1.prepare_dot4_and_assign(p_20_p, a_21_p, b_21_p, FUNC_XOR(beaver4_tuples[10].d, r141), beaver4_tuples[6]);  // and4_58
                B3G_19_21_s1 = B3G_19_21_g1 ^ B3G_19_21_t1;  // B3G_19_21_s1
                B3G_19_21_out = B3G_19_21_s1 ^ B3G_19_21_t2;  // B3G_19_21_out
                // and_63: random_triples[7].a, random_triples[7].b, output mask=r144
                B3G_23_25_g1 = a[23].prepare_dot_reshared(b[23], r144, random_triples[7].b);  // and_63
                // and3_65: a14=beaver3_tuples[14].a, b14=beaver3_tuples[14].b, c14=beaver3_tuples[14].c, output mask=(r143-r144)
                B3G_23_25_t1 = p_23_p.prepare_dot3_and_assign(a_24_p, b_24_p, FUNC_XOR(r143, r144), beaver3_tuples[14]);  // and3_65
                // and4_67: a7=beaver4_tuples[7].a, b7=beaver4_tuples[7].b, c7=beaver4_tuples[7].c, d7=beaver4_tuples[7].d, output mask=(b47-r143)
                B3G_23_25_t2 = p_23_p_1.prepare_dot4_and_assign(p_24_p, a_25_p, b_25_p, FUNC_XOR(triples[2].b, r143), beaver4_tuples[7]);  // and4_67
                B3G_23_25_s1 = B3G_23_25_g1 ^ B3G_23_25_t1;  // B3G_23_25_s1
                B3G_23_25_out = B3G_23_25_s1 ^ B3G_23_25_t2;  // B3G_23_25_out
                // and_72: random_triples[8].a, random_triples[8].b, output mask=r146
                B3G_26_28_g1 = a[26].prepare_dot_reshared(b[26], r146, random_triples[8].b);  // and_72
                // and3_74: a16=beaver3_tuples[16].a, b16=beaver3_tuples[16].b, c16=beaver3_tuples[16].c, output mask=(r145-r146)
                B3G_26_28_t1 = p_26_p.prepare_dot3_and_assign(a_27_p, b_27_p, FUNC_XOR(r145, r146), beaver3_tuples[16]);  // and3_74
                // and4_76: a8=beaver4_tuples[8].a, b8=beaver4_tuples[8].b, c8=beaver4_tuples[8].c, d8=beaver4_tuples[8].d, output mask=(c48-r145)
                B3G_26_28_t2 = p_26_p_1.prepare_dot4_and_assign(p_27_p, a_28_p, b_28_p, FUNC_XOR(beaver3_tuples[22].c, r145), beaver4_tuples[8]);  // and4_76
                B3G_26_28_s1 = B3G_26_28_g1 ^ B3G_26_28_t1;  // B3G_26_28_s1
                B3G_26_28_out = B3G_26_28_s1 ^ B3G_26_28_t2;  // B3G_26_28_out
                // and_81: random_triples[9].a, random_triples[9].b, output mask=r148
                W3L1_29_31_g1 = a[29].prepare_dot_reshared(b[29], r148, random_triples[9].b);  // and_81
                // and3_83: a18=beaver3_tuples[18].a, b18=beaver3_tuples[18].b, c18=beaver3_tuples[18].c, output mask=(r147-r148)
                W3L1_29_31_t1 = p_29_p.prepare_dot3_and_assign(a_30_p, b_30_p, FUNC_XOR(r147, r148), beaver3_tuples[18]);  // and3_83
                // and4_85: a9=beaver4_tuples[9].a, b9=beaver4_tuples[9].b, c9=beaver4_tuples[9].c, d9=beaver4_tuples[9].d, output mask=(d49-r147)
                W3L1_29_31_t2 = p_29_p_1.prepare_dot4_and_assign(p_30_p, a_31_p, b_31_p, FUNC_XOR(beaver4_tuples[12].d, r147), beaver4_tuples[9]);  // and4_85
                W3L1_29_31_s1 = W3L1_29_31_g1 ^ W3L1_29_31_t1;  // W3L1_29_31_s1
                W3L1_29_31_out = W3L1_29_31_s1 ^ W3L1_29_31_t2;  // W3L1_29_31_out
                break;
            case 1:
                B3P_1_3_out_p = B3P_1_3_out.zero_add(triples[0].a);  // B3P_1_3_out', mask=a39
                B3P_1_3_out_p_1 = B3P_1_3_out.zero_add(beaver3_tuples[19].a);  // B3P_1_3_out'_1, mask=a40
                B3P_4_6_out_p = B3P_4_6_out.zero_add(beaver3_tuples[19].b);  // B3P_4_6_out', mask=b40
                B3P_10_12_out_p = B3P_10_12_out.zero_add(triples[1].a);  // B3P_10_12_out', mask=a42
                B3P_10_12_out_p_1 = B3P_10_12_out.zero_add(beaver3_tuples[21].a);  // B3P_10_12_out'_1, mask=a43
                B3P_10_12_out_p_2 = B3P_10_12_out.zero_add(beaver4_tuples[10].a);  // B3P_10_12_out'_2, mask=a44
                B3P_13_15_out_p = B3P_13_15_out.zero_add(beaver3_tuples[21].b);  // B3P_13_15_out', mask=b43
                B3P_13_15_out_p_1 = B3P_13_15_out.zero_add(beaver4_tuples[10].b);  // B3P_13_15_out'_1, mask=b44
                B3P_16_18_out_p = B3P_16_18_out.zero_add(beaver4_tuples[10].c);  // B3P_16_18_out', mask=c44
                B3P_23_25_out_p = B3P_23_25_out.zero_add(beaver3_tuples[22].b);  // B3P_23_25_out', mask=b48
                // and_88: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=r160
                L1_B3G_t1 = B3P_1_3_out_p.prepare_dot_and_assign(B3G_4_6_out, r160, triples[0].c);  // and_88
                // and3_89: a19=beaver3_tuples[19].a, b19=beaver3_tuples[19].b, c19=beaver3_tuples[19].c, output mask=r161
                L1_B3G_t2 = B3P_1_3_out_p_1.prepare_dot3_and_assign(B3P_4_6_out_p, B3G_7_9_out, r161, beaver3_tuples[19]);  // and3_89
                L1_B3G_s1 = L1_B3G_t1 ^ L1_B3G_t2;  // L1_B3G_s1
                // and_93: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=r153
                L1_B4G_t1 = B3P_10_12_out_p.prepare_dot_and_assign(B3G_13_15_out, r153, triples[1].c);  // and_93
                // and3_94: a21=beaver3_tuples[21].a, b21=beaver3_tuples[21].b, c21=beaver3_tuples[21].c, output mask=(r152-r153)
                L1_B4G_t2 = B3P_10_12_out_p_1.prepare_dot3_and_assign(B3P_13_15_out_p, B3G_16_18_out, FUNC_XOR(r152, r153), beaver3_tuples[21]);  // and3_94
                // and4_95: a10=beaver4_tuples[10].a, b10=beaver4_tuples[10].b, c10=beaver4_tuples[10].c, d10=beaver4_tuples[10].d, output mask=(r149-r152)
                L1_B4G_t3 = B3P_10_12_out_p_2.prepare_dot4_and_assign(B3P_13_15_out_p_1, B3P_16_18_out_p, B3G_19_21_out, FUNC_XOR(r149, r152), beaver4_tuples[10]);  // and4_95
                L1_B4G_s1 = L1_B4G_t1 ^ L1_B4G_t2;  // L1_B4G_s1
                L1_B4G_s2 = L1_B4G_s1 ^ L1_B4G_t3;  // L1_B4G_s2
                // and_100: random_triples[10].a, random_triples[10].b, output mask=r156
                L1_W4S_g1 = a[22].prepare_dot_reshared(b[22], r156, random_triples[10].b);  // and_100
                // and_102: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=(r155-r156)
                L1_W4S_t1 = p_22_p.prepare_dot_and_assign(B3G_23_25_out, FUNC_XOR(r155, r156), triples[2].c);  // and_102
                // and3_103: a22=beaver3_tuples[22].a, b22=beaver3_tuples[22].b, c22=beaver3_tuples[22].c, output mask=(r154-r155)
                L1_W4S_t2 = p_22_p_1.prepare_dot3_and_assign(B3P_23_25_out_p, B3G_26_28_out, FUNC_XOR(r154, r155), beaver3_tuples[22]);  // and3_103
                // and4_104: a12=beaver4_tuples[12].a, b12=beaver4_tuples[12].b, c12=beaver4_tuples[12].c, d12=beaver4_tuples[12].d, output mask=(c51-r154)
                L1_W4S_t3 = p_22_p_2.prepare_dot4_and_assign(B3P_23_25_out, B3P_26_28_out, W3L1_29_31_out, FUNC_XOR(beaver3_tuples[23].c, r154), beaver4_tuples[12]);  // and4_104
                L1_W4S_s1 = L1_W4S_g1 ^ L1_W4S_t1;  // L1_W4S_s1
                L1_W4S_s2 = L1_W4S_s1 ^ L1_W4S_t2;  // L1_W4S_s2
                L1_W4S_out = L1_W4S_s2 ^ L1_W4S_t3;  // L1_W4S_out
                break;
            case 2:
                L1_B3P_out_p = L1_B3P_out.zero_add(triples[3].a);  // L1_B3P_out', mask=a50
                L1_B3G_out = L1_B3G_s1 ^ B3G_1_3_out;  // L1_B3G_out
                L1_B4G_out = L1_B4G_s2 ^ B3G_10_12_out;  // L1_B4G_out
                // and_108: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=r162
                L2_W3_t1 = L1_B3P_out_p.prepare_dot_and_assign(L1_B4G_out, r162, triples[3].c);  // and_108
                // and3_109: a23=beaver3_tuples[23].a, b23=beaver3_tuples[23].b, c23=beaver3_tuples[23].c, output mask=r163
                L2_W3_t2 = L1_B3P_out.prepare_dot3_and_assign(L1_B4P_out, L1_W4S_out, r163, beaver3_tuples[23]);  // and3_109
                L2_W3_s1 = L2_W3_t1 ^ L2_W3_t2;  // L2_W3_s1
                break;
            case 3:
                L2_W3_s2 = L2_W3_s1 ^ L1_B3G_out;  // L2_W3_s2
                msb = L2_W3_s2 ^ p0;  // msb
                break;
        }
    }

    void aggregate_step()
    {
        switch(level) {
            case 0:
                B3G_1_3_out.mask_and_send_dot_without_remask();
                // and3_8: a1=beaver3_tuples[1].a, b1=beaver3_tuples[1].b, c1=beaver3_tuples[1].c, output mask=a41
                B3P_1_3_out = p_1_p_2.prepare_and3_and_assign(p_2_p_1, p_3_p, beaver3_tuples[20].a, beaver3_tuples[1]);  // and3_8
                B3G_4_6_out.mask_and_send_dot_without_remask();
                // and3_17: a3=beaver3_tuples[3].a, b3=beaver3_tuples[3].b, c3=beaver3_tuples[3].c, output mask=b41
                B3P_4_6_out = p_4_p_2.prepare_and3_and_assign(p_5_p_1, p_6_p, beaver3_tuples[20].b, beaver3_tuples[3]);  // and3_17
                B3G_7_9_out.mask_and_send_dot_without_remask();
                // and3_26: a5=beaver3_tuples[5].a, b5=beaver3_tuples[5].b, c5=beaver3_tuples[5].c, output mask=c41
                B3P_7_9_out = p_7_p_2.prepare_and3_and_assign(p_8_p_1, p_9_p, beaver3_tuples[20].c, beaver3_tuples[5]);  // and3_26
                B3G_10_12_out.mask_and_send_dot_without_remask();
                // and3_35: a7=beaver3_tuples[7].a, b7=beaver3_tuples[7].b, c7=beaver3_tuples[7].c, output mask=a45
                B3P_10_12_out = p_10_p_2.prepare_and3_and_assign(p_11_p_1, p_12_p, beaver4_tuples[11].a, beaver3_tuples[7]);  // and3_35
                B3G_13_15_out.mask_and_send_dot_without_remask();
                // and3_44: a9=beaver3_tuples[9].a, b9=beaver3_tuples[9].b, c9=beaver3_tuples[9].c, output mask=b45
                B3P_13_15_out = p_13_p_2.prepare_and3_and_assign(p_14_p_1, p_15_p, beaver4_tuples[11].b, beaver3_tuples[9]);  // and3_44
                B3G_16_18_out.mask_and_send_dot_without_remask();
                // and3_53: a11=beaver3_tuples[11].a, b11=beaver3_tuples[11].b, c11=beaver3_tuples[11].c, output mask=c45
                B3P_16_18_out = p_16_p_2.prepare_and3_and_assign(p_17_p_1, p_18_p, beaver4_tuples[11].c, beaver3_tuples[11]);  // and3_53
                B3G_19_21_out.mask_and_send_dot_without_remask();
                // and3_62: a13=beaver3_tuples[13].a, b13=beaver3_tuples[13].b, c13=beaver3_tuples[13].c, output mask=d45
                B3P_19_21_out = p_19_p_2.prepare_and3_and_assign(p_20_p_1, p_21_p, beaver4_tuples[11].d, beaver3_tuples[13]);  // and3_62
                B3G_23_25_out.mask_and_send_dot_without_remask();
                // and3_71: a15=beaver3_tuples[15].a, b15=beaver3_tuples[15].b, c15=beaver3_tuples[15].c, output mask=b49
                B3P_23_25_out = p_23_p_2.prepare_and3_and_assign(p_24_p_1, p_25_p, beaver4_tuples[12].b, beaver3_tuples[15]);  // and3_71
                B3G_26_28_out.mask_and_send_dot_without_remask();
                // and3_80: a17=beaver3_tuples[17].a, b17=beaver3_tuples[17].b, c17=beaver3_tuples[17].c, output mask=c49
                B3P_26_28_out = p_26_p_2.prepare_and3_and_assign(p_27_p_1, p_28_p, beaver4_tuples[12].c, beaver3_tuples[17]);  // and3_80
                W3L1_29_31_out.mask_and_send_dot_without_remask();
                break;
            case 1:
                L1_B3G_s1.mask_and_send_dot_without_remask();
                // and3_92: a20=beaver3_tuples[20].a, b20=beaver3_tuples[20].b, c20=beaver3_tuples[20].c, output mask=a51
                L1_B3P_out = B3P_1_3_out.prepare_and3_and_assign(B3P_4_6_out, B3P_7_9_out, beaver3_tuples[23].a, beaver3_tuples[20]);  // and3_92
                L1_B4G_s2.mask_and_send_dot_without_remask();
                // and4_99: a11=beaver4_tuples[11].a, b11=beaver4_tuples[11].b, c11=beaver4_tuples[11].c, d11=beaver4_tuples[11].d, output mask=b51
                L1_B4P_out = B3P_10_12_out.prepare_and4_and_assign(B3P_13_15_out, B3P_16_18_out, B3P_19_21_out, beaver3_tuples[23].b, beaver4_tuples[11]);  // and4_99
                L1_W4S_out.mask_and_send_dot_without_remask();
                break;
            case 2:
                L2_W3_s1.mask_and_send_dot_without_remask();
                break;
            case 3:
                break;
        }
    }

    void collect_step()
    {
        switch(level) {
            case 0:
                B3G_1_3_out.complete_and();
                B3P_1_3_out.complete_and3();
                B3G_4_6_out.complete_and();
                B3P_4_6_out.complete_and3();
                B3G_7_9_out.complete_and();
                B3P_7_9_out.complete_and3();
                B3G_10_12_out.complete_and();
                B3P_10_12_out.complete_and3();
                B3G_13_15_out.complete_and();
                B3P_13_15_out.complete_and3();
                B3G_16_18_out.complete_and();
                B3P_16_18_out.complete_and3();
                B3G_19_21_out.complete_and();
                B3P_19_21_out.complete_and3();
                B3G_23_25_out.complete_and();
                B3P_23_25_out.complete_and3();
                B3G_26_28_out.complete_and();
                B3P_26_28_out.complete_and3();
                W3L1_29_31_out.complete_and();
                break;
            case 1:
                L1_B3G_s1.complete_and();
                L1_B3P_out.complete_and3();
                L1_B4G_s2.complete_and();
                L1_B4P_out.complete_and4();
                L1_W4S_out.complete_and();
                break;
            case 2:
                L2_W3_s1.complete_and();
                break;
            case 3:
                break;
        }
        level++;
    }
};