// Wire assignment code for RCA_MSB_A_AB family
// Generated by generate_hpp.py
#pragma once
#include <type_traits>
#include "../../../datatypes/k_bitset.hpp"
#include "../../../protocols/Protocols.h"

template <int k, typename Share, typename Enable = void>
class RCA_MSB_A_AB;

// Wire assignment code for RCA_MSB_A_AB (8-bit)
// Generated by generate_hpp.py
// Gates: AND2=6, AND3=0, AND4=0, AND_A=1, AND_RESHARED=0, XOR=20, ZERO_ADD=6
// Beaver triples: 6, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 0
template <int k, typename Share>
class RCA_MSB_A_AB<k, Share, typename std::enable_if<(k == 8)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 8;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& x;
    Bitset& y;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 6;
    triple<DATATYPE> triples[BeaverTripleCount];

    DATATYPE r13;

    Share carry_1;
    Share carry_2;
    Share carry_3;
    Share carry_4;
    Share carry_5;
    Share carry_6;
    Share carry_7;
    Share carry_t_1;
    Share carry_t_2;
    Share carry_t_3;
    Share carry_t_4;
    Share carry_t_5;
    Share carry_t_6;
    Share cx_1;
    Share cx_2;
    Share cx_3;
    Share cx_4;
    Share cx_5;
    Share cx_6;
    Share cy_1;
    Share cy_1_p;
    Share cy_2;
    Share cy_2_p;
    Share cy_3;
    Share cy_3_p;
    Share cy_4;
    Share cy_4_p;
    Share cy_5;
    Share cy_5_p;
    Share cy_6;
    Share cy_6_p;
    Share t_xy_msb;

  public:
    RCA_MSB_A_AB(Bitset& x_input, Bitset& y_input, Share& msb_output) : x(x_input), y(y_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r13 = getRandomVal(PSELF);

        }
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 8; }
    bool is_done() const { return level > 7; }

    void step()
    {
        switch(level) {
            case 0:
                t_xy_msb = x[0] ^ y[0];  // t_xy_msb
                carry_7 = x[7].mult_a_known_to_evaluators(y[7]);  // and_a_0
                carry_7.prepare_remask(FUNC_XOR(triples[0].a, x[6].get_mask()));
                break;
            case 1:
                carry_7.complete_remask();
                cx_6 = carry_7 ^ x[6];  // cx[6]
                cy_6 = carry_7 ^ y[6];  // cy[6]
                cy_6_p = cy_6.zero_add(triples[0].b);  // cy[6]', mask=b0
                // and_3: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=((a1-f(x[5]))-(a0-f(x[6])))
                carry_t_6 = cx_6.prepare_and(cy_6_p, FUNC_XOR(FUNC_XOR(triples[1].a, x[5].get_mask()), FUNC_XOR(triples[0].a, x[6].get_mask())), triples[0].c);  // and_3
                break;
            case 2:
                carry_t_6.complete_and();
                carry_6 = carry_t_6 ^ carry_7;  // carry[6]
                cx_5 = carry_6 ^ x[5];  // cx[5]
                cy_5 = carry_6 ^ y[5];  // cy[5]
                cy_5_p = cy_5.zero_add(triples[1].b);  // cy[5]', mask=b1
                // and_7: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=((a2-f(x[4]))-(a1-f(x[5])))
                carry_t_5 = cx_5.prepare_and(cy_5_p, FUNC_XOR(FUNC_XOR(triples[2].a, x[4].get_mask()), FUNC_XOR(triples[1].a, x[5].get_mask())), triples[1].c);  // and_7
                break;
            case 3:
                carry_t_5.complete_and();
                carry_5 = carry_t_5 ^ carry_6;  // carry[5]
                cx_4 = carry_5 ^ x[4];  // cx[4]
                cy_4 = carry_5 ^ y[4];  // cy[4]
                cy_4_p = cy_4.zero_add(triples[2].b);  // cy[4]', mask=b2
                // and_11: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=((a3-f(x[3]))-(a2-f(x[4])))
                carry_t_4 = cx_4.prepare_and(cy_4_p, FUNC_XOR(FUNC_XOR(triples[3].a, x[3].get_mask()), FUNC_XOR(triples[2].a, x[4].get_mask())), triples[2].c);  // and_11
                break;
            case 4:
                carry_t_4.complete_and();
                carry_4 = carry_t_4 ^ carry_5;  // carry[4]
                cx_3 = carry_4 ^ x[3];  // cx[3]
                cy_3 = carry_4 ^ y[3];  // cy[3]
                cy_3_p = cy_3.zero_add(triples[3].b);  // cy[3]', mask=b3
                // and_15: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=((a4-f(x[2]))-(a3-f(x[3])))
                carry_t_3 = cx_3.prepare_and(cy_3_p, FUNC_XOR(FUNC_XOR(triples[4].a, x[2].get_mask()), FUNC_XOR(triples[3].a, x[3].get_mask())), triples[3].c);  // and_15
                break;
            case 5:
                carry_t_3.complete_and();
                carry_3 = carry_t_3 ^ carry_4;  // carry[3]
                cx_2 = carry_3 ^ x[2];  // cx[2]
                cy_2 = carry_3 ^ y[2];  // cy[2]
                cy_2_p = cy_2.zero_add(triples[4].b);  // cy[2]', mask=b4
                // and_19: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=((a5-f(x[1]))-(a4-f(x[2])))
                carry_t_2 = cx_2.prepare_and(cy_2_p, FUNC_XOR(FUNC_XOR(triples[5].a, x[1].get_mask()), FUNC_XOR(triples[4].a, x[2].get_mask())), triples[4].c);  // and_19
                break;
            case 6:
                carry_t_2.complete_and();
                carry_2 = carry_t_2 ^ carry_3;  // carry[2]
                cx_1 = carry_2 ^ x[1];  // cx[1]
                cy_1 = carry_2 ^ y[1];  // cy[1]
                cy_1_p = cy_1.zero_add(triples[5].b);  // cy[1]', mask=b5
                // and_23: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=r13
                carry_t_1 = cx_1.prepare_and(cy_1_p, r13, triples[5].c);  // and_23
                break;
            case 7:
                carry_t_1.complete_and();
                carry_1 = carry_t_1 ^ carry_2;  // carry[1]
                msb = t_xy_msb ^ carry_1;  // msb
                break;
        }
        level++;
    }
};

// Wire assignment code for RCA_MSB_A_AB (16-bit)
// Generated by generate_hpp.py
// Gates: AND2=14, AND3=0, AND4=0, AND_A=1, AND_RESHARED=0, XOR=44, ZERO_ADD=14
// Beaver triples: 14, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 0
template <int k, typename Share>
class RCA_MSB_A_AB<k, Share, typename std::enable_if<(k == 16)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 16;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& x;
    Bitset& y;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 14;
    triple<DATATYPE> triples[BeaverTripleCount];

    DATATYPE r29;

    Share carry_10;
    Share carry_11;
    Share carry_12;
    Share carry_13;
    Share carry_14;
    Share carry_15;
    Share carry_1;
    Share carry_2;
    Share carry_3;
    Share carry_4;
    Share carry_5;
    Share carry_6;
    Share carry_7;
    Share carry_8;
    Share carry_9;
    Share carry_t_10;
    Share carry_t_11;
    Share carry_t_12;
    Share carry_t_13;
    Share carry_t_14;
    Share carry_t_1;
    Share carry_t_2;
    Share carry_t_3;
    Share carry_t_4;
    Share carry_t_5;
    Share carry_t_6;
    Share carry_t_7;
    Share carry_t_8;
    Share carry_t_9;
    Share cx_10;
    Share cx_11;
    Share cx_12;
    Share cx_13;
    Share cx_14;
    Share cx_1;
    Share cx_2;
    Share cx_3;
    Share cx_4;
    Share cx_5;
    Share cx_6;
    Share cx_7;
    Share cx_8;
    Share cx_9;
    Share cy_10;
    Share cy_10_p;
    Share cy_11;
    Share cy_11_p;
    Share cy_12;
    Share cy_12_p;
    Share cy_13;
    Share cy_13_p;
    Share cy_14;
    Share cy_14_p;
    Share cy_1;
    Share cy_1_p;
    Share cy_2;
    Share cy_2_p;
    Share cy_3;
    Share cy_3_p;
    Share cy_4;
    Share cy_4_p;
    Share cy_5;
    Share cy_5_p;
    Share cy_6;
    Share cy_6_p;
    Share cy_7;
    Share cy_7_p;
    Share cy_8;
    Share cy_8_p;
    Share cy_9;
    Share cy_9_p;
    Share t_xy_msb;

  public:
    RCA_MSB_A_AB(Bitset& x_input, Bitset& y_input, Share& msb_output) : x(x_input), y(y_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r29 = getRandomVal(PSELF);

        }
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 16; }
    bool is_done() const { return level > 15; }

    void step()
    {
        switch(level) {
            case 0:
                t_xy_msb = x[0] ^ y[0];  // t_xy_msb
                carry_15 = x[15].mult_a_known_to_evaluators(y[15]);  // and_a_0
                carry_15.prepare_remask(FUNC_XOR(triples[0].a, x[14].get_mask()));
                break;
            case 1:
                carry_15.complete_remask();
                cx_14 = carry_15 ^ x[14];  // cx[14]
                cy_14 = carry_15 ^ y[14];  // cy[14]
                cy_14_p = cy_14.zero_add(triples[0].b);  // cy[14]', mask=b0
                // and_3: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=((a1-f(x[13]))-(a0-f(x[14])))
                carry_t_14 = cx_14.prepare_and(cy_14_p, FUNC_XOR(FUNC_XOR(triples[1].a, x[13].get_mask()), FUNC_XOR(triples[0].a, x[14].get_mask())), triples[0].c);  // and_3
                break;
            case 2:
                carry_t_14.complete_and();
                carry_14 = carry_t_14 ^ carry_15;  // carry[14]
                cx_13 = carry_14 ^ x[13];  // cx[13]
                cy_13 = carry_14 ^ y[13];  // cy[13]
                cy_13_p = cy_13.zero_add(triples[1].b);  // cy[13]', mask=b1
                // and_7: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=((a2-f(x[12]))-(a1-f(x[13])))
                carry_t_13 = cx_13.prepare_and(cy_13_p, FUNC_XOR(FUNC_XOR(triples[2].a, x[12].get_mask()), FUNC_XOR(triples[1].a, x[13].get_mask())), triples[1].c);  // and_7
                break;
            case 3:
                carry_t_13.complete_and();
                carry_13 = carry_t_13 ^ carry_14;  // carry[13]
                cx_12 = carry_13 ^ x[12];  // cx[12]
                cy_12 = carry_13 ^ y[12];  // cy[12]
                cy_12_p = cy_12.zero_add(triples[2].b);  // cy[12]', mask=b2
                // and_11: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=((a3-f(x[11]))-(a2-f(x[12])))
                carry_t_12 = cx_12.prepare_and(cy_12_p, FUNC_XOR(FUNC_XOR(triples[3].a, x[11].get_mask()), FUNC_XOR(triples[2].a, x[12].get_mask())), triples[2].c);  // and_11
                break;
            case 4:
                carry_t_12.complete_and();
                carry_12 = carry_t_12 ^ carry_13;  // carry[12]
                cx_11 = carry_12 ^ x[11];  // cx[11]
                cy_11 = carry_12 ^ y[11];  // cy[11]
                cy_11_p = cy_11.zero_add(triples[3].b);  // cy[11]', mask=b3
                // and_15: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=((a4-f(x[10]))-(a3-f(x[11])))
                carry_t_11 = cx_11.prepare_and(cy_11_p, FUNC_XOR(FUNC_XOR(triples[4].a, x[10].get_mask()), FUNC_XOR(triples[3].a, x[11].get_mask())), triples[3].c);  // and_15
                break;
            case 5:
                carry_t_11.complete_and();
                carry_11 = carry_t_11 ^ carry_12;  // carry[11]
                cx_10 = carry_11 ^ x[10];  // cx[10]
                cy_10 = carry_11 ^ y[10];  // cy[10]
                cy_10_p = cy_10.zero_add(triples[4].b);  // cy[10]', mask=b4
                // and_19: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=((a5-f(x[9]))-(a4-f(x[10])))
                carry_t_10 = cx_10.prepare_and(cy_10_p, FUNC_XOR(FUNC_XOR(triples[5].a, x[9].get_mask()), FUNC_XOR(triples[4].a, x[10].get_mask())), triples[4].c);  // and_19
                break;
            case 6:
                carry_t_10.complete_and();
                carry_10 = carry_t_10 ^ carry_11;  // carry[10]
                cx_9 = carry_10 ^ x[9];  // cx[9]
                cy_9 = carry_10 ^ y[9];  // cy[9]
                cy_9_p = cy_9.zero_add(triples[5].b);  // cy[9]', mask=b5
                // and_23: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=((a6-f(x[8]))-(a5-f(x[9])))
                carry_t_9 = cx_9.prepare_and(cy_9_p, FUNC_XOR(FUNC_XOR(triples[6].a, x[8].get_mask()), FUNC_XOR(triples[5].a, x[9].get_mask())), triples[5].c);  // and_23
                break;
            case 7:
                carry_t_9.complete_and();
                carry_9 = carry_t_9 ^ carry_10;  // carry[9]
                cx_8 = carry_9 ^ x[8];  // cx[8]
                cy_8 = carry_9 ^ y[8];  // cy[8]
                cy_8_p = cy_8.zero_add(triples[6].b);  // cy[8]', mask=b6
                // and_27: a6=triples[6].a, b6=triples[6].b, c6=triples[6].c, output mask=((a7-f(x[7]))-(a6-f(x[8])))
                carry_t_8 = cx_8.prepare_and(cy_8_p, FUNC_XOR(FUNC_XOR(triples[7].a, x[7].get_mask()), FUNC_XOR(triples[6].a, x[8].get_mask())), triples[6].c);  // and_27
                break;
            case 8:
                carry_t_8.complete_and();
                carry_8 = carry_t_8 ^ carry_9;  // carry[8]
                cx_7 = carry_8 ^ x[7];  // cx[7]
                cy_7 = carry_8 ^ y[7];  // cy[7]
                cy_7_p = cy_7.zero_add(triples[7].b);  // cy[7]', mask=b7
                // and_31: a7=triples[7].a, b7=triples[7].b, c7=triples[7].c, output mask=((a8-f(x[6]))-(a7-f(x[7])))
                carry_t_7 = cx_7.prepare_and(cy_7_p, FUNC_XOR(FUNC_XOR(triples[8].a, x[6].get_mask()), FUNC_XOR(triples[7].a, x[7].get_mask())), triples[7].c);  // and_31
                break;
            case 9:
                carry_t_7.complete_and();
                carry_7 = carry_t_7 ^ carry_8;  // carry[7]
                cx_6 = carry_7 ^ x[6];  // cx[6]
                cy_6 = carry_7 ^ y[6];  // cy[6]
                cy_6_p = cy_6.zero_add(triples[8].b);  // cy[6]', mask=b8
                // and_35: a8=triples[8].a, b8=triples[8].b, c8=triples[8].c, output mask=((a9-f(x[5]))-(a8-f(x[6])))
                carry_t_6 = cx_6.prepare_and(cy_6_p, FUNC_XOR(FUNC_XOR(triples[9].a, x[5].get_mask()), FUNC_XOR(triples[8].a, x[6].get_mask())), triples[8].c);  // and_35
                break;
            case 10:
                carry_t_6.complete_and();
                carry_6 = carry_t_6 ^ carry_7;  // carry[6]
                cx_5 = carry_6 ^ x[5];  // cx[5]
                cy_5 = carry_6 ^ y[5];  // cy[5]
                cy_5_p = cy_5.zero_add(triples[9].b);  // cy[5]', mask=b9
                // and_39: a9=triples[9].a, b9=triples[9].b, c9=triples[9].c, output mask=((a10-f(x[4]))-(a9-f(x[5])))
                carry_t_5 = cx_5.prepare_and(cy_5_p, FUNC_XOR(FUNC_XOR(triples[10].a, x[4].get_mask()), FUNC_XOR(triples[9].a, x[5].get_mask())), triples[9].c);  // and_39
                break;
            case 11:
                carry_t_5.complete_and();
                carry_5 = carry_t_5 ^ carry_6;  // carry[5]
                cx_4 = carry_5 ^ x[4];  // cx[4]
                cy_4 = carry_5 ^ y[4];  // cy[4]
                cy_4_p = cy_4.zero_add(triples[10].b);  // cy[4]', mask=b10
                // and_43: a10=triples[10].a, b10=triples[10].b, c10=triples[10].c, output mask=((a11-f(x[3]))-(a10-f(x[4])))
                carry_t_4 = cx_4.prepare_and(cy_4_p, FUNC_XOR(FUNC_XOR(triples[11].a, x[3].get_mask()), FUNC_XOR(triples[10].a, x[4].get_mask())), triples[10].c);  // and_43
                break;
            case 12:
                carry_t_4.complete_and();
                carry_4 = carry_t_4 ^ carry_5;  // carry[4]
                cx_3 = carry_4 ^ x[3];  // cx[3]
                cy_3 = carry_4 ^ y[3];  // cy[3]
                cy_3_p = cy_3.zero_add(triples[11].b);  // cy[3]', mask=b11
                // and_47: a11=triples[11].a, b11=triples[11].b, c11=triples[11].c, output mask=((a12-f(x[2]))-(a11-f(x[3])))
                carry_t_3 = cx_3.prepare_and(cy_3_p, FUNC_XOR(FUNC_XOR(triples[12].a, x[2].get_mask()), FUNC_XOR(triples[11].a, x[3].get_mask())), triples[11].c);  // and_47
                break;
            case 13:
                carry_t_3.complete_and();
                carry_3 = carry_t_3 ^ carry_4;  // carry[3]
                cx_2 = carry_3 ^ x[2];  // cx[2]
                cy_2 = carry_3 ^ y[2];  // cy[2]
                cy_2_p = cy_2.zero_add(triples[12].b);  // cy[2]', mask=b12
                // and_51: a12=triples[12].a, b12=triples[12].b, c12=triples[12].c, output mask=((a13-f(x[1]))-(a12-f(x[2])))
                carry_t_2 = cx_2.prepare_and(cy_2_p, FUNC_XOR(FUNC_XOR(triples[13].a, x[1].get_mask()), FUNC_XOR(triples[12].a, x[2].get_mask())), triples[12].c);  // and_51
                break;
            case 14:
                carry_t_2.complete_and();
                carry_2 = carry_t_2 ^ carry_3;  // carry[2]
                cx_1 = carry_2 ^ x[1];  // cx[1]
                cy_1 = carry_2 ^ y[1];  // cy[1]
                cy_1_p = cy_1.zero_add(triples[13].b);  // cy[1]', mask=b13
                // and_55: a13=triples[13].a, b13=triples[13].b, c13=triples[13].c, output mask=r29
                carry_t_1 = cx_1.prepare_and(cy_1_p, r29, triples[13].c);  // and_55
                break;
            case 15:
                carry_t_1.complete_and();
                carry_1 = carry_t_1 ^ carry_2;  // carry[1]
                msb = t_xy_msb ^ carry_1;  // msb
                break;
        }
        level++;
    }
};

// Wire assignment code for RCA_MSB_A_AB (32-bit)
// Generated by generate_hpp.py
// Gates: AND2=30, AND3=0, AND4=0, AND_A=1, AND_RESHARED=0, XOR=92, ZERO_ADD=30
// Beaver triples: 30, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 0
template <int k, typename Share>
class RCA_MSB_A_AB<k, Share, typename std::enable_if<(k == 32)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 32;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& x;
    Bitset& y;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 30;
    triple<DATATYPE> triples[BeaverTripleCount];

    DATATYPE r61;

    Share carry_10;
    Share carry_11;
    Share carry_12;
    Share carry_13;
    Share carry_14;
    Share carry_15;
    Share carry_16;
    Share carry_17;
    Share carry_18;
    Share carry_19;
    Share carry_1;
    Share carry_20;
    Share carry_21;
    Share carry_22;
    Share carry_23;
    Share carry_24;
    Share carry_25;
    Share carry_26;
    Share carry_27;
    Share carry_28;
    Share carry_29;
    Share carry_2;
    Share carry_30;
    Share carry_31;
    Share carry_3;
    Share carry_4;
    Share carry_5;
    Share carry_6;
    Share carry_7;
    Share carry_8;
    Share carry_9;
    Share carry_t_10;
    Share carry_t_11;
    Share carry_t_12;
    Share carry_t_13;
    Share carry_t_14;
    Share carry_t_15;
    Share carry_t_16;
    Share carry_t_17;
    Share carry_t_18;
    Share carry_t_19;
    Share carry_t_1;
    Share carry_t_20;
    Share carry_t_21;
    Share carry_t_22;
    Share carry_t_23;
    Share carry_t_24;
    Share carry_t_25;
    Share carry_t_26;
    Share carry_t_27;
    Share carry_t_28;
    Share carry_t_29;
    Share carry_t_2;
    Share carry_t_30;
    Share carry_t_3;
    Share carry_t_4;
    Share carry_t_5;
    Share carry_t_6;
    Share carry_t_7;
    Share carry_t_8;
    Share carry_t_9;
    Share cx_10;
    Share cx_11;
    Share cx_12;
    Share cx_13;
    Share cx_14;
    Share cx_15;
    Share cx_16;
    Share cx_17;
    Share cx_18;
    Share cx_19;
    Share cx_1;
    Share cx_20;
    Share cx_21;
    Share cx_22;
    Share cx_23;
    Share cx_24;
    Share cx_25;
    Share cx_26;
    Share cx_27;
    Share cx_28;
    Share cx_29;
    Share cx_2;
    Share cx_30;
    Share cx_3;
    Share cx_4;
    Share cx_5;
    Share cx_6;
    Share cx_7;
    Share cx_8;
    Share cx_9;
    Share cy_10;
    Share cy_10_p;
    Share cy_11;
    Share cy_11_p;
    Share cy_12;
    Share cy_12_p;
    Share cy_13;
    Share cy_13_p;
    Share cy_14;
    Share cy_14_p;
    Share cy_15;
    Share cy_15_p;
    Share cy_16;
    Share cy_16_p;
    Share cy_17;
    Share cy_17_p;
    Share cy_18;
    Share cy_18_p;
    Share cy_19;
    Share cy_19_p;
    Share cy_1;
    Share cy_1_p;
    Share cy_20;
    Share cy_20_p;
    Share cy_21;
    Share cy_21_p;
    Share cy_22;
    Share cy_22_p;
    Share cy_23;
    Share cy_23_p;
    Share cy_24;
    Share cy_24_p;
    Share cy_25;
    Share cy_25_p;
    Share cy_26;
    Share cy_26_p;
    Share cy_27;
    Share cy_27_p;
    Share cy_28;
    Share cy_28_p;
    Share cy_29;
    Share cy_29_p;
    Share cy_2;
    Share cy_2_p;
    Share cy_30;
    Share cy_30_p;
    Share cy_3;
    Share cy_3_p;
    Share cy_4;
    Share cy_4_p;
    Share cy_5;
    Share cy_5_p;
    Share cy_6;
    Share cy_6_p;
    Share cy_7;
    Share cy_7_p;
    Share cy_8;
    Share cy_8_p;
    Share cy_9;
    Share cy_9_p;
    Share t_xy_msb;

  public:
    RCA_MSB_A_AB(Bitset& x_input, Bitset& y_input, Share& msb_output) : x(x_input), y(y_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                // CUT_FRACTIONAL_BITS_OPT: the shortcut stops after case 31-FRACTIONAL, so triple
                // slots >= 30-FRACTIONAL are never used by any executed gate - and the INIT phase
                // (which counts per CALLED gate) allocated accordingly. Retrieval must match.
                if (!(CUT_FRAC_SUPPORTED && g_cut_frac_active) || i < 30 - FRACTIONAL)
                    triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r61 = getRandomVal(PSELF);

        }
    }

    // CUT_FRACTIONAL_BITS_OPT (see the reshared RCA): under TRUNC_DELAYED == 0 the top FRACTIONAL
    // slices are redundant - stop the carry chain at the boundary slice and read the MSB there.
    static constexpr bool CUT_FRAC_SUPPORTED = (FRACTIONAL >= 1 && FRACTIONAL <= 29);
    static constexpr int CUT_FRAC_STOP_CASE = 31 - FRACTIONAL;  // meaningless (unused) when !CUT_FRAC_SUPPORTED

    int get_rounds() const { return level; }
    int get_total_rounds() const { return (CUT_FRAC_SUPPORTED && g_cut_frac_active) ? CUT_FRAC_STOP_CASE + 1 : 32; }
    bool is_done() const { return (CUT_FRAC_SUPPORTED && g_cut_frac_active) ? level > CUT_FRAC_STOP_CASE : level > 31; }

    void step()
    {
        switch(level) {
            case 0:
                t_xy_msb = x[0] ^ y[0];  // t_xy_msb
                carry_31 = x[31].mult_a_known_to_evaluators(y[31]);  // and_a_0
                carry_31.prepare_remask(FUNC_XOR(triples[0].a, x[30].get_mask()));
                break;
            case 1:
                carry_31.complete_remask();
                cx_30 = carry_31 ^ x[30];  // cx[30]
                cy_30 = carry_31 ^ y[30];  // cy[30]
                cy_30_p = cy_30.zero_add(triples[0].b);  // cy[30]', mask=b0
                // and_3: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=((a1-f(x[29]))-(a0-f(x[30])))
                carry_t_30 = cx_30.prepare_and(cy_30_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 29) ? r61 : (FUNC_XOR(FUNC_XOR(triples[1].a, x[29].get_mask()), FUNC_XOR(triples[0].a, x[30].get_mask()))), triples[0].c);  // and_3
                break;
            case 2:
                carry_t_30.complete_and();
                carry_30 = carry_t_30 ^ carry_31;  // carry[30]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 29)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[29] ^ y[29] ^ carry_30;
                    break;
                }
                cx_29 = carry_30 ^ x[29];  // cx[29]
                cy_29 = carry_30 ^ y[29];  // cy[29]
                cy_29_p = cy_29.zero_add(triples[1].b);  // cy[29]', mask=b1
                // and_7: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=((a2-f(x[28]))-(a1-f(x[29])))
                carry_t_29 = cx_29.prepare_and(cy_29_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 28) ? r61 : (FUNC_XOR(FUNC_XOR(triples[2].a, x[28].get_mask()), FUNC_XOR(triples[1].a, x[29].get_mask()))), triples[1].c);  // and_7
                break;
            case 3:
                carry_t_29.complete_and();
                carry_29 = carry_t_29 ^ carry_30;  // carry[29]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 28)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[28] ^ y[28] ^ carry_29;
                    break;
                }
                cx_28 = carry_29 ^ x[28];  // cx[28]
                cy_28 = carry_29 ^ y[28];  // cy[28]
                cy_28_p = cy_28.zero_add(triples[2].b);  // cy[28]', mask=b2
                // and_11: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=((a3-f(x[27]))-(a2-f(x[28])))
                carry_t_28 = cx_28.prepare_and(cy_28_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 27) ? r61 : (FUNC_XOR(FUNC_XOR(triples[3].a, x[27].get_mask()), FUNC_XOR(triples[2].a, x[28].get_mask()))), triples[2].c);  // and_11
                break;
            case 4:
                carry_t_28.complete_and();
                carry_28 = carry_t_28 ^ carry_29;  // carry[28]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 27)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[27] ^ y[27] ^ carry_28;
                    break;
                }
                cx_27 = carry_28 ^ x[27];  // cx[27]
                cy_27 = carry_28 ^ y[27];  // cy[27]
                cy_27_p = cy_27.zero_add(triples[3].b);  // cy[27]', mask=b3
                // and_15: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=((a4-f(x[26]))-(a3-f(x[27])))
                carry_t_27 = cx_27.prepare_and(cy_27_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 26) ? r61 : (FUNC_XOR(FUNC_XOR(triples[4].a, x[26].get_mask()), FUNC_XOR(triples[3].a, x[27].get_mask()))), triples[3].c);  // and_15
                break;
            case 5:
                carry_t_27.complete_and();
                carry_27 = carry_t_27 ^ carry_28;  // carry[27]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 26)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[26] ^ y[26] ^ carry_27;
                    break;
                }
                cx_26 = carry_27 ^ x[26];  // cx[26]
                cy_26 = carry_27 ^ y[26];  // cy[26]
                cy_26_p = cy_26.zero_add(triples[4].b);  // cy[26]', mask=b4
                // and_19: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=((a5-f(x[25]))-(a4-f(x[26])))
                carry_t_26 = cx_26.prepare_and(cy_26_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 25) ? r61 : (FUNC_XOR(FUNC_XOR(triples[5].a, x[25].get_mask()), FUNC_XOR(triples[4].a, x[26].get_mask()))), triples[4].c);  // and_19
                break;
            case 6:
                carry_t_26.complete_and();
                carry_26 = carry_t_26 ^ carry_27;  // carry[26]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 25)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[25] ^ y[25] ^ carry_26;
                    break;
                }
                cx_25 = carry_26 ^ x[25];  // cx[25]
                cy_25 = carry_26 ^ y[25];  // cy[25]
                cy_25_p = cy_25.zero_add(triples[5].b);  // cy[25]', mask=b5
                // and_23: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=((a6-f(x[24]))-(a5-f(x[25])))
                carry_t_25 = cx_25.prepare_and(cy_25_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 24) ? r61 : (FUNC_XOR(FUNC_XOR(triples[6].a, x[24].get_mask()), FUNC_XOR(triples[5].a, x[25].get_mask()))), triples[5].c);  // and_23
                break;
            case 7:
                carry_t_25.complete_and();
                carry_25 = carry_t_25 ^ carry_26;  // carry[25]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 24)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[24] ^ y[24] ^ carry_25;
                    break;
                }
                cx_24 = carry_25 ^ x[24];  // cx[24]
                cy_24 = carry_25 ^ y[24];  // cy[24]
                cy_24_p = cy_24.zero_add(triples[6].b);  // cy[24]', mask=b6
                // and_27: a6=triples[6].a, b6=triples[6].b, c6=triples[6].c, output mask=((a7-f(x[23]))-(a6-f(x[24])))
                carry_t_24 = cx_24.prepare_and(cy_24_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 23) ? r61 : (FUNC_XOR(FUNC_XOR(triples[7].a, x[23].get_mask()), FUNC_XOR(triples[6].a, x[24].get_mask()))), triples[6].c);  // and_27
                break;
            case 8:
                carry_t_24.complete_and();
                carry_24 = carry_t_24 ^ carry_25;  // carry[24]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 23)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[23] ^ y[23] ^ carry_24;
                    break;
                }
                cx_23 = carry_24 ^ x[23];  // cx[23]
                cy_23 = carry_24 ^ y[23];  // cy[23]
                cy_23_p = cy_23.zero_add(triples[7].b);  // cy[23]', mask=b7
                // and_31: a7=triples[7].a, b7=triples[7].b, c7=triples[7].c, output mask=((a8-f(x[22]))-(a7-f(x[23])))
                carry_t_23 = cx_23.prepare_and(cy_23_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 22) ? r61 : (FUNC_XOR(FUNC_XOR(triples[8].a, x[22].get_mask()), FUNC_XOR(triples[7].a, x[23].get_mask()))), triples[7].c);  // and_31
                break;
            case 9:
                carry_t_23.complete_and();
                carry_23 = carry_t_23 ^ carry_24;  // carry[23]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 22)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[22] ^ y[22] ^ carry_23;
                    break;
                }
                cx_22 = carry_23 ^ x[22];  // cx[22]
                cy_22 = carry_23 ^ y[22];  // cy[22]
                cy_22_p = cy_22.zero_add(triples[8].b);  // cy[22]', mask=b8
                // and_35: a8=triples[8].a, b8=triples[8].b, c8=triples[8].c, output mask=((a9-f(x[21]))-(a8-f(x[22])))
                carry_t_22 = cx_22.prepare_and(cy_22_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 21) ? r61 : (FUNC_XOR(FUNC_XOR(triples[9].a, x[21].get_mask()), FUNC_XOR(triples[8].a, x[22].get_mask()))), triples[8].c);  // and_35
                break;
            case 10:
                carry_t_22.complete_and();
                carry_22 = carry_t_22 ^ carry_23;  // carry[22]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 21)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[21] ^ y[21] ^ carry_22;
                    break;
                }
                cx_21 = carry_22 ^ x[21];  // cx[21]
                cy_21 = carry_22 ^ y[21];  // cy[21]
                cy_21_p = cy_21.zero_add(triples[9].b);  // cy[21]', mask=b9
                // and_39: a9=triples[9].a, b9=triples[9].b, c9=triples[9].c, output mask=((a10-f(x[20]))-(a9-f(x[21])))
                carry_t_21 = cx_21.prepare_and(cy_21_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 20) ? r61 : (FUNC_XOR(FUNC_XOR(triples[10].a, x[20].get_mask()), FUNC_XOR(triples[9].a, x[21].get_mask()))), triples[9].c);  // and_39
                break;
            case 11:
                carry_t_21.complete_and();
                carry_21 = carry_t_21 ^ carry_22;  // carry[21]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 20)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[20] ^ y[20] ^ carry_21;
                    break;
                }
                cx_20 = carry_21 ^ x[20];  // cx[20]
                cy_20 = carry_21 ^ y[20];  // cy[20]
                cy_20_p = cy_20.zero_add(triples[10].b);  // cy[20]', mask=b10
                // and_43: a10=triples[10].a, b10=triples[10].b, c10=triples[10].c, output mask=((a11-f(x[19]))-(a10-f(x[20])))
                carry_t_20 = cx_20.prepare_and(cy_20_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 19) ? r61 : (FUNC_XOR(FUNC_XOR(triples[11].a, x[19].get_mask()), FUNC_XOR(triples[10].a, x[20].get_mask()))), triples[10].c);  // and_43
                break;
            case 12:
                carry_t_20.complete_and();
                carry_20 = carry_t_20 ^ carry_21;  // carry[20]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 19)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[19] ^ y[19] ^ carry_20;
                    break;
                }
                cx_19 = carry_20 ^ x[19];  // cx[19]
                cy_19 = carry_20 ^ y[19];  // cy[19]
                cy_19_p = cy_19.zero_add(triples[11].b);  // cy[19]', mask=b11
                // and_47: a11=triples[11].a, b11=triples[11].b, c11=triples[11].c, output mask=((a12-f(x[18]))-(a11-f(x[19])))
                carry_t_19 = cx_19.prepare_and(cy_19_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 18) ? r61 : (FUNC_XOR(FUNC_XOR(triples[12].a, x[18].get_mask()), FUNC_XOR(triples[11].a, x[19].get_mask()))), triples[11].c);  // and_47
                break;
            case 13:
                carry_t_19.complete_and();
                carry_19 = carry_t_19 ^ carry_20;  // carry[19]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 18)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[18] ^ y[18] ^ carry_19;
                    break;
                }
                cx_18 = carry_19 ^ x[18];  // cx[18]
                cy_18 = carry_19 ^ y[18];  // cy[18]
                cy_18_p = cy_18.zero_add(triples[12].b);  // cy[18]', mask=b12
                // and_51: a12=triples[12].a, b12=triples[12].b, c12=triples[12].c, output mask=((a13-f(x[17]))-(a12-f(x[18])))
                carry_t_18 = cx_18.prepare_and(cy_18_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 17) ? r61 : (FUNC_XOR(FUNC_XOR(triples[13].a, x[17].get_mask()), FUNC_XOR(triples[12].a, x[18].get_mask()))), triples[12].c);  // and_51
                break;
            case 14:
                carry_t_18.complete_and();
                carry_18 = carry_t_18 ^ carry_19;  // carry[18]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 17)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[17] ^ y[17] ^ carry_18;
                    break;
                }
                cx_17 = carry_18 ^ x[17];  // cx[17]
                cy_17 = carry_18 ^ y[17];  // cy[17]
                cy_17_p = cy_17.zero_add(triples[13].b);  // cy[17]', mask=b13
                // and_55: a13=triples[13].a, b13=triples[13].b, c13=triples[13].c, output mask=((a14-f(x[16]))-(a13-f(x[17])))
                carry_t_17 = cx_17.prepare_and(cy_17_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 16) ? r61 : (FUNC_XOR(FUNC_XOR(triples[14].a, x[16].get_mask()), FUNC_XOR(triples[13].a, x[17].get_mask()))), triples[13].c);  // and_55
                break;
            case 15:
                carry_t_17.complete_and();
                carry_17 = carry_t_17 ^ carry_18;  // carry[17]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 16)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[16] ^ y[16] ^ carry_17;
                    break;
                }
                cx_16 = carry_17 ^ x[16];  // cx[16]
                cy_16 = carry_17 ^ y[16];  // cy[16]
                cy_16_p = cy_16.zero_add(triples[14].b);  // cy[16]', mask=b14
                // and_59: a14=triples[14].a, b14=triples[14].b, c14=triples[14].c, output mask=((a15-f(x[15]))-(a14-f(x[16])))
                carry_t_16 = cx_16.prepare_and(cy_16_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 15) ? r61 : (FUNC_XOR(FUNC_XOR(triples[15].a, x[15].get_mask()), FUNC_XOR(triples[14].a, x[16].get_mask()))), triples[14].c);  // and_59
                break;
            case 16:
                carry_t_16.complete_and();
                carry_16 = carry_t_16 ^ carry_17;  // carry[16]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 15)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[15] ^ y[15] ^ carry_16;
                    break;
                }
                cx_15 = carry_16 ^ x[15];  // cx[15]
                cy_15 = carry_16 ^ y[15];  // cy[15]
                cy_15_p = cy_15.zero_add(triples[15].b);  // cy[15]', mask=b15
                // and_63: a15=triples[15].a, b15=triples[15].b, c15=triples[15].c, output mask=((a16-f(x[14]))-(a15-f(x[15])))
                carry_t_15 = cx_15.prepare_and(cy_15_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 14) ? r61 : (FUNC_XOR(FUNC_XOR(triples[16].a, x[14].get_mask()), FUNC_XOR(triples[15].a, x[15].get_mask()))), triples[15].c);  // and_63
                break;
            case 17:
                carry_t_15.complete_and();
                carry_15 = carry_t_15 ^ carry_16;  // carry[15]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 14)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[14] ^ y[14] ^ carry_15;
                    break;
                }
                cx_14 = carry_15 ^ x[14];  // cx[14]
                cy_14 = carry_15 ^ y[14];  // cy[14]
                cy_14_p = cy_14.zero_add(triples[16].b);  // cy[14]', mask=b16
                // and_67: a16=triples[16].a, b16=triples[16].b, c16=triples[16].c, output mask=((a17-f(x[13]))-(a16-f(x[14])))
                carry_t_14 = cx_14.prepare_and(cy_14_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 13) ? r61 : (FUNC_XOR(FUNC_XOR(triples[17].a, x[13].get_mask()), FUNC_XOR(triples[16].a, x[14].get_mask()))), triples[16].c);  // and_67
                break;
            case 18:
                carry_t_14.complete_and();
                carry_14 = carry_t_14 ^ carry_15;  // carry[14]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 13)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[13] ^ y[13] ^ carry_14;
                    break;
                }
                cx_13 = carry_14 ^ x[13];  // cx[13]
                cy_13 = carry_14 ^ y[13];  // cy[13]
                cy_13_p = cy_13.zero_add(triples[17].b);  // cy[13]', mask=b17
                // and_71: a17=triples[17].a, b17=triples[17].b, c17=triples[17].c, output mask=((a18-f(x[12]))-(a17-f(x[13])))
                carry_t_13 = cx_13.prepare_and(cy_13_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 12) ? r61 : (FUNC_XOR(FUNC_XOR(triples[18].a, x[12].get_mask()), FUNC_XOR(triples[17].a, x[13].get_mask()))), triples[17].c);  // and_71
                break;
            case 19:
                carry_t_13.complete_and();
                carry_13 = carry_t_13 ^ carry_14;  // carry[13]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 12)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[12] ^ y[12] ^ carry_13;
                    break;
                }
                cx_12 = carry_13 ^ x[12];  // cx[12]
                cy_12 = carry_13 ^ y[12];  // cy[12]
                cy_12_p = cy_12.zero_add(triples[18].b);  // cy[12]', mask=b18
                // and_75: a18=triples[18].a, b18=triples[18].b, c18=triples[18].c, output mask=((a19-f(x[11]))-(a18-f(x[12])))
                carry_t_12 = cx_12.prepare_and(cy_12_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 11) ? r61 : (FUNC_XOR(FUNC_XOR(triples[19].a, x[11].get_mask()), FUNC_XOR(triples[18].a, x[12].get_mask()))), triples[18].c);  // and_75
                break;
            case 20:
                carry_t_12.complete_and();
                carry_12 = carry_t_12 ^ carry_13;  // carry[12]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 11)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[11] ^ y[11] ^ carry_12;
                    break;
                }
                cx_11 = carry_12 ^ x[11];  // cx[11]
                cy_11 = carry_12 ^ y[11];  // cy[11]
                cy_11_p = cy_11.zero_add(triples[19].b);  // cy[11]', mask=b19
                // and_79: a19=triples[19].a, b19=triples[19].b, c19=triples[19].c, output mask=((a20-f(x[10]))-(a19-f(x[11])))
                carry_t_11 = cx_11.prepare_and(cy_11_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 10) ? r61 : (FUNC_XOR(FUNC_XOR(triples[20].a, x[10].get_mask()), FUNC_XOR(triples[19].a, x[11].get_mask()))), triples[19].c);  // and_79
                break;
            case 21:
                carry_t_11.complete_and();
                carry_11 = carry_t_11 ^ carry_12;  // carry[11]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 10)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[10] ^ y[10] ^ carry_11;
                    break;
                }
                cx_10 = carry_11 ^ x[10];  // cx[10]
                cy_10 = carry_11 ^ y[10];  // cy[10]
                cy_10_p = cy_10.zero_add(triples[20].b);  // cy[10]', mask=b20
                // and_83: a20=triples[20].a, b20=triples[20].b, c20=triples[20].c, output mask=((a21-f(x[9]))-(a20-f(x[10])))
                carry_t_10 = cx_10.prepare_and(cy_10_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 9) ? r61 : (FUNC_XOR(FUNC_XOR(triples[21].a, x[9].get_mask()), FUNC_XOR(triples[20].a, x[10].get_mask()))), triples[20].c);  // and_83
                break;
            case 22:
                carry_t_10.complete_and();
                carry_10 = carry_t_10 ^ carry_11;  // carry[10]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 9)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[9] ^ y[9] ^ carry_10;
                    break;
                }
                cx_9 = carry_10 ^ x[9];  // cx[9]
                cy_9 = carry_10 ^ y[9];  // cy[9]
                cy_9_p = cy_9.zero_add(triples[21].b);  // cy[9]', mask=b21
                // and_87: a21=triples[21].a, b21=triples[21].b, c21=triples[21].c, output mask=((a22-f(x[8]))-(a21-f(x[9])))
                carry_t_9 = cx_9.prepare_and(cy_9_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 8) ? r61 : (FUNC_XOR(FUNC_XOR(triples[22].a, x[8].get_mask()), FUNC_XOR(triples[21].a, x[9].get_mask()))), triples[21].c);  // and_87
                break;
            case 23:
                carry_t_9.complete_and();
                carry_9 = carry_t_9 ^ carry_10;  // carry[9]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 8)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[8] ^ y[8] ^ carry_9;
                    break;
                }
                cx_8 = carry_9 ^ x[8];  // cx[8]
                cy_8 = carry_9 ^ y[8];  // cy[8]
                cy_8_p = cy_8.zero_add(triples[22].b);  // cy[8]', mask=b22
                // and_91: a22=triples[22].a, b22=triples[22].b, c22=triples[22].c, output mask=((a23-f(x[7]))-(a22-f(x[8])))
                carry_t_8 = cx_8.prepare_and(cy_8_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 7) ? r61 : (FUNC_XOR(FUNC_XOR(triples[23].a, x[7].get_mask()), FUNC_XOR(triples[22].a, x[8].get_mask()))), triples[22].c);  // and_91
                break;
            case 24:
                carry_t_8.complete_and();
                carry_8 = carry_t_8 ^ carry_9;  // carry[8]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 7)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[7] ^ y[7] ^ carry_8;
                    break;
                }
                cx_7 = carry_8 ^ x[7];  // cx[7]
                cy_7 = carry_8 ^ y[7];  // cy[7]
                cy_7_p = cy_7.zero_add(triples[23].b);  // cy[7]', mask=b23
                // and_95: a23=triples[23].a, b23=triples[23].b, c23=triples[23].c, output mask=((a24-f(x[6]))-(a23-f(x[7])))
                carry_t_7 = cx_7.prepare_and(cy_7_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 6) ? r61 : (FUNC_XOR(FUNC_XOR(triples[24].a, x[6].get_mask()), FUNC_XOR(triples[23].a, x[7].get_mask()))), triples[23].c);  // and_95
                break;
            case 25:
                carry_t_7.complete_and();
                carry_7 = carry_t_7 ^ carry_8;  // carry[7]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 6)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[6] ^ y[6] ^ carry_7;
                    break;
                }
                cx_6 = carry_7 ^ x[6];  // cx[6]
                cy_6 = carry_7 ^ y[6];  // cy[6]
                cy_6_p = cy_6.zero_add(triples[24].b);  // cy[6]', mask=b24
                // and_99: a24=triples[24].a, b24=triples[24].b, c24=triples[24].c, output mask=((a25-f(x[5]))-(a24-f(x[6])))
                carry_t_6 = cx_6.prepare_and(cy_6_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 5) ? r61 : (FUNC_XOR(FUNC_XOR(triples[25].a, x[5].get_mask()), FUNC_XOR(triples[24].a, x[6].get_mask()))), triples[24].c);  // and_99
                break;
            case 26:
                carry_t_6.complete_and();
                carry_6 = carry_t_6 ^ carry_7;  // carry[6]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 5)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[5] ^ y[5] ^ carry_6;
                    break;
                }
                cx_5 = carry_6 ^ x[5];  // cx[5]
                cy_5 = carry_6 ^ y[5];  // cy[5]
                cy_5_p = cy_5.zero_add(triples[25].b);  // cy[5]', mask=b25
                // and_103: a25=triples[25].a, b25=triples[25].b, c25=triples[25].c, output mask=((a26-f(x[4]))-(a25-f(x[5])))
                carry_t_5 = cx_5.prepare_and(cy_5_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 4) ? r61 : (FUNC_XOR(FUNC_XOR(triples[26].a, x[4].get_mask()), FUNC_XOR(triples[25].a, x[5].get_mask()))), triples[25].c);  // and_103
                break;
            case 27:
                carry_t_5.complete_and();
                carry_5 = carry_t_5 ^ carry_6;  // carry[5]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 4)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[4] ^ y[4] ^ carry_5;
                    break;
                }
                cx_4 = carry_5 ^ x[4];  // cx[4]
                cy_4 = carry_5 ^ y[4];  // cy[4]
                cy_4_p = cy_4.zero_add(triples[26].b);  // cy[4]', mask=b26
                // and_107: a26=triples[26].a, b26=triples[26].b, c26=triples[26].c, output mask=((a27-f(x[3]))-(a26-f(x[4])))
                carry_t_4 = cx_4.prepare_and(cy_4_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 3) ? r61 : (FUNC_XOR(FUNC_XOR(triples[27].a, x[3].get_mask()), FUNC_XOR(triples[26].a, x[4].get_mask()))), triples[26].c);  // and_107
                break;
            case 28:
                carry_t_4.complete_and();
                carry_4 = carry_t_4 ^ carry_5;  // carry[4]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 3)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[3] ^ y[3] ^ carry_4;
                    break;
                }
                cx_3 = carry_4 ^ x[3];  // cx[3]
                cy_3 = carry_4 ^ y[3];  // cy[3]
                cy_3_p = cy_3.zero_add(triples[27].b);  // cy[3]', mask=b27
                // and_111: a27=triples[27].a, b27=triples[27].b, c27=triples[27].c, output mask=((a28-f(x[2]))-(a27-f(x[3])))
                carry_t_3 = cx_3.prepare_and(cy_3_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 2) ? r61 : (FUNC_XOR(FUNC_XOR(triples[28].a, x[2].get_mask()), FUNC_XOR(triples[27].a, x[3].get_mask()))), triples[27].c);  // and_111
                break;
            case 29:
                carry_t_3.complete_and();
                carry_3 = carry_t_3 ^ carry_4;  // carry[3]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 2)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[2] ^ y[2] ^ carry_3;
                    break;
                }
                cx_2 = carry_3 ^ x[2];  // cx[2]
                cy_2 = carry_3 ^ y[2];  // cy[2]
                cy_2_p = cy_2.zero_add(triples[28].b);  // cy[2]', mask=b28
                // and_115: a28=triples[28].a, b28=triples[28].b, c28=triples[28].c, output mask=((a29-f(x[1]))-(a28-f(x[2])))
                carry_t_2 = cx_2.prepare_and(cy_2_p, (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 1) ? r61 : (FUNC_XOR(FUNC_XOR(triples[29].a, x[1].get_mask()), FUNC_XOR(triples[28].a, x[2].get_mask()))), triples[28].c);  // and_115
                break;
            case 30:
                carry_t_2.complete_and();
                carry_2 = carry_t_2 ^ carry_3;  // carry[2]
                if (CUT_FRAC_SUPPORTED && g_cut_frac_active && FRACTIONAL == 1)
                {
                    // CUT: boundary-slice sum bit already equals the true MSB (top slices redundant)
                    msb = x[1] ^ y[1] ^ carry_2;
                    break;
                }
                cx_1 = carry_2 ^ x[1];  // cx[1]
                cy_1 = carry_2 ^ y[1];  // cy[1]
                cy_1_p = cy_1.zero_add(triples[29].b);  // cy[1]', mask=b29
                // and_119: a29=triples[29].a, b29=triples[29].b, c29=triples[29].c, output mask=r61
                carry_t_1 = cx_1.prepare_and(cy_1_p, r61, triples[29].c);  // and_119
                break;
            case 31:
                carry_t_1.complete_and();
                carry_1 = carry_t_1 ^ carry_2;  // carry[1]
                msb = t_xy_msb ^ carry_1;  // msb
                break;
        }
        level++;
    }
};

// 64-bit: generated by scripts/circuits/gen_64bit_adders.py (generate_hpp.py, LLM_TEST); the cut runs the narrow
// adders of narrow64/ instead of identity-substituting this circuit.
// Wire assignment code for RCA_MSB_A_AB (64-bit)
// Generated by generate_hpp.py
// Gates: AND2=62, AND3=0, AND4=0, AND_A=1, AND_RESHARED=0, XOR=188, ZERO_ADD=62
// Beaver triples: 62, Beaver3Tuples: 0, Beaver4Tuples: 0, RandomTriples: 0
template <int k, typename Share>
class RCA_MSB_A_AB<k, Share, typename std::enable_if<(k == 64)>::type>
{
  private:
    static constexpr int BIT_WIDTH = 64;
    using Bitset = sbitset_t<BIT_WIDTH, Share>;

    Bitset& x;
    Bitset& y;
    Share& msb;
    int level;
    static constexpr int BeaverTripleCount = 62;
    triple<DATATYPE> triples[BeaverTripleCount];

    DATATYPE r125;

    Share carry_10;
    Share carry_11;
    Share carry_12;
    Share carry_13;
    Share carry_14;
    Share carry_15;
    Share carry_16;
    Share carry_17;
    Share carry_18;
    Share carry_19;
    Share carry_1;
    Share carry_20;
    Share carry_21;
    Share carry_22;
    Share carry_23;
    Share carry_24;
    Share carry_25;
    Share carry_26;
    Share carry_27;
    Share carry_28;
    Share carry_29;
    Share carry_2;
    Share carry_30;
    Share carry_31;
    Share carry_32;
    Share carry_33;
    Share carry_34;
    Share carry_35;
    Share carry_36;
    Share carry_37;
    Share carry_38;
    Share carry_39;
    Share carry_3;
    Share carry_40;
    Share carry_41;
    Share carry_42;
    Share carry_43;
    Share carry_44;
    Share carry_45;
    Share carry_46;
    Share carry_47;
    Share carry_48;
    Share carry_49;
    Share carry_4;
    Share carry_50;
    Share carry_51;
    Share carry_52;
    Share carry_53;
    Share carry_54;
    Share carry_55;
    Share carry_56;
    Share carry_57;
    Share carry_58;
    Share carry_59;
    Share carry_5;
    Share carry_60;
    Share carry_61;
    Share carry_62;
    Share carry_63;
    Share carry_6;
    Share carry_7;
    Share carry_8;
    Share carry_9;
    Share carry_t_10;
    Share carry_t_11;
    Share carry_t_12;
    Share carry_t_13;
    Share carry_t_14;
    Share carry_t_15;
    Share carry_t_16;
    Share carry_t_17;
    Share carry_t_18;
    Share carry_t_19;
    Share carry_t_1;
    Share carry_t_20;
    Share carry_t_21;
    Share carry_t_22;
    Share carry_t_23;
    Share carry_t_24;
    Share carry_t_25;
    Share carry_t_26;
    Share carry_t_27;
    Share carry_t_28;
    Share carry_t_29;
    Share carry_t_2;
    Share carry_t_30;
    Share carry_t_31;
    Share carry_t_32;
    Share carry_t_33;
    Share carry_t_34;
    Share carry_t_35;
    Share carry_t_36;
    Share carry_t_37;
    Share carry_t_38;
    Share carry_t_39;
    Share carry_t_3;
    Share carry_t_40;
    Share carry_t_41;
    Share carry_t_42;
    Share carry_t_43;
    Share carry_t_44;
    Share carry_t_45;
    Share carry_t_46;
    Share carry_t_47;
    Share carry_t_48;
    Share carry_t_49;
    Share carry_t_4;
    Share carry_t_50;
    Share carry_t_51;
    Share carry_t_52;
    Share carry_t_53;
    Share carry_t_54;
    Share carry_t_55;
    Share carry_t_56;
    Share carry_t_57;
    Share carry_t_58;
    Share carry_t_59;
    Share carry_t_5;
    Share carry_t_60;
    Share carry_t_61;
    Share carry_t_62;
    Share carry_t_6;
    Share carry_t_7;
    Share carry_t_8;
    Share carry_t_9;
    Share cx_10;
    Share cx_11;
    Share cx_12;
    Share cx_13;
    Share cx_14;
    Share cx_15;
    Share cx_16;
    Share cx_17;
    Share cx_18;
    Share cx_19;
    Share cx_1;
    Share cx_20;
    Share cx_21;
    Share cx_22;
    Share cx_23;
    Share cx_24;
    Share cx_25;
    Share cx_26;
    Share cx_27;
    Share cx_28;
    Share cx_29;
    Share cx_2;
    Share cx_30;
    Share cx_31;
    Share cx_32;
    Share cx_33;
    Share cx_34;
    Share cx_35;
    Share cx_36;
    Share cx_37;
    Share cx_38;
    Share cx_39;
    Share cx_3;
    Share cx_40;
    Share cx_41;
    Share cx_42;
    Share cx_43;
    Share cx_44;
    Share cx_45;
    Share cx_46;
    Share cx_47;
    Share cx_48;
    Share cx_49;
    Share cx_4;
    Share cx_50;
    Share cx_51;
    Share cx_52;
    Share cx_53;
    Share cx_54;
    Share cx_55;
    Share cx_56;
    Share cx_57;
    Share cx_58;
    Share cx_59;
    Share cx_5;
    Share cx_60;
    Share cx_61;
    Share cx_62;
    Share cx_6;
    Share cx_7;
    Share cx_8;
    Share cx_9;
    Share cy_10;
    Share cy_10_p;
    Share cy_11;
    Share cy_11_p;
    Share cy_12;
    Share cy_12_p;
    Share cy_13;
    Share cy_13_p;
    Share cy_14;
    Share cy_14_p;
    Share cy_15;
    Share cy_15_p;
    Share cy_16;
    Share cy_16_p;
    Share cy_17;
    Share cy_17_p;
    Share cy_18;
    Share cy_18_p;
    Share cy_19;
    Share cy_19_p;
    Share cy_1;
    Share cy_1_p;
    Share cy_20;
    Share cy_20_p;
    Share cy_21;
    Share cy_21_p;
    Share cy_22;
    Share cy_22_p;
    Share cy_23;
    Share cy_23_p;
    Share cy_24;
    Share cy_24_p;
    Share cy_25;
    Share cy_25_p;
    Share cy_26;
    Share cy_26_p;
    Share cy_27;
    Share cy_27_p;
    Share cy_28;
    Share cy_28_p;
    Share cy_29;
    Share cy_29_p;
    Share cy_2;
    Share cy_2_p;
    Share cy_30;
    Share cy_30_p;
    Share cy_31;
    Share cy_31_p;
    Share cy_32;
    Share cy_32_p;
    Share cy_33;
    Share cy_33_p;
    Share cy_34;
    Share cy_34_p;
    Share cy_35;
    Share cy_35_p;
    Share cy_36;
    Share cy_36_p;
    Share cy_37;
    Share cy_37_p;
    Share cy_38;
    Share cy_38_p;
    Share cy_39;
    Share cy_39_p;
    Share cy_3;
    Share cy_3_p;
    Share cy_40;
    Share cy_40_p;
    Share cy_41;
    Share cy_41_p;
    Share cy_42;
    Share cy_42_p;
    Share cy_43;
    Share cy_43_p;
    Share cy_44;
    Share cy_44_p;
    Share cy_45;
    Share cy_45_p;
    Share cy_46;
    Share cy_46_p;
    Share cy_47;
    Share cy_47_p;
    Share cy_48;
    Share cy_48_p;
    Share cy_49;
    Share cy_49_p;
    Share cy_4;
    Share cy_4_p;
    Share cy_50;
    Share cy_50_p;
    Share cy_51;
    Share cy_51_p;
    Share cy_52;
    Share cy_52_p;
    Share cy_53;
    Share cy_53_p;
    Share cy_54;
    Share cy_54_p;
    Share cy_55;
    Share cy_55_p;
    Share cy_56;
    Share cy_56_p;
    Share cy_57;
    Share cy_57_p;
    Share cy_58;
    Share cy_58_p;
    Share cy_59;
    Share cy_59_p;
    Share cy_5;
    Share cy_5_p;
    Share cy_60;
    Share cy_60_p;
    Share cy_61;
    Share cy_61_p;
    Share cy_62;
    Share cy_62_p;
    Share cy_6;
    Share cy_6_p;
    Share cy_7;
    Share cy_7_p;
    Share cy_8;
    Share cy_8_p;
    Share cy_9;
    Share cy_9_p;
    Share t_xy_msb;

  public:
    RCA_MSB_A_AB(Bitset& x_input, Bitset& y_input, Share& msb_output) : x(x_input), y(y_input), msb(msb_output), level(0)
    {
        if (current_phase != PHASE_INIT)
        {
            for (int i = 0; i < BeaverTripleCount; ++i)
            {
                triples[i] = retrieveBooleanTriple<DATATYPE>();
            }
            // Random mask values (shared across mask expressions)
            r125 = getRandomVal(PSELF);

        }
    }

    int get_rounds() const { return level; }
    int get_total_rounds() const { return 64; }
    bool is_done() const { return level > 63; }

    void step()
    {
        switch(level) {
            case 0:
                t_xy_msb = x[0] ^ y[0];  // t_xy_msb
                carry_63 = x[63].mult_a_known_to_evaluators(y[63]);  // and_a_0
                carry_63.prepare_remask(FUNC_XOR(triples[0].a, x[62].get_mask()));
                break;
            case 1:
                carry_63.complete_remask();
                cx_62 = carry_63 ^ x[62];  // cx[62]
                cy_62 = carry_63 ^ y[62];  // cy[62]
                cy_62_p = cy_62.zero_add(triples[0].b);  // cy[62]', mask=b0
                // and_3: a0=triples[0].a, b0=triples[0].b, c0=triples[0].c, output mask=((a1-f(x[61]))-(a0-f(x[62])))
                carry_t_62 = cx_62.prepare_and(cy_62_p, FUNC_XOR(FUNC_XOR(triples[1].a, x[61].get_mask()), FUNC_XOR(triples[0].a, x[62].get_mask())), triples[0].c);  // and_3
                break;
            case 2:
                carry_t_62.complete_and();
                carry_62 = carry_t_62 ^ carry_63;  // carry[62]
                cx_61 = carry_62 ^ x[61];  // cx[61]
                cy_61 = carry_62 ^ y[61];  // cy[61]
                cy_61_p = cy_61.zero_add(triples[1].b);  // cy[61]', mask=b1
                // and_7: a1=triples[1].a, b1=triples[1].b, c1=triples[1].c, output mask=((a2-f(x[60]))-(a1-f(x[61])))
                carry_t_61 = cx_61.prepare_and(cy_61_p, FUNC_XOR(FUNC_XOR(triples[2].a, x[60].get_mask()), FUNC_XOR(triples[1].a, x[61].get_mask())), triples[1].c);  // and_7
                break;
            case 3:
                carry_t_61.complete_and();
                carry_61 = carry_t_61 ^ carry_62;  // carry[61]
                cx_60 = carry_61 ^ x[60];  // cx[60]
                cy_60 = carry_61 ^ y[60];  // cy[60]
                cy_60_p = cy_60.zero_add(triples[2].b);  // cy[60]', mask=b2
                // and_11: a2=triples[2].a, b2=triples[2].b, c2=triples[2].c, output mask=((a3-f(x[59]))-(a2-f(x[60])))
                carry_t_60 = cx_60.prepare_and(cy_60_p, FUNC_XOR(FUNC_XOR(triples[3].a, x[59].get_mask()), FUNC_XOR(triples[2].a, x[60].get_mask())), triples[2].c);  // and_11
                break;
            case 4:
                carry_t_60.complete_and();
                carry_60 = carry_t_60 ^ carry_61;  // carry[60]
                cx_59 = carry_60 ^ x[59];  // cx[59]
                cy_59 = carry_60 ^ y[59];  // cy[59]
                cy_59_p = cy_59.zero_add(triples[3].b);  // cy[59]', mask=b3
                // and_15: a3=triples[3].a, b3=triples[3].b, c3=triples[3].c, output mask=((a4-f(x[58]))-(a3-f(x[59])))
                carry_t_59 = cx_59.prepare_and(cy_59_p, FUNC_XOR(FUNC_XOR(triples[4].a, x[58].get_mask()), FUNC_XOR(triples[3].a, x[59].get_mask())), triples[3].c);  // and_15
                break;
            case 5:
                carry_t_59.complete_and();
                carry_59 = carry_t_59 ^ carry_60;  // carry[59]
                cx_58 = carry_59 ^ x[58];  // cx[58]
                cy_58 = carry_59 ^ y[58];  // cy[58]
                cy_58_p = cy_58.zero_add(triples[4].b);  // cy[58]', mask=b4
                // and_19: a4=triples[4].a, b4=triples[4].b, c4=triples[4].c, output mask=((a5-f(x[57]))-(a4-f(x[58])))
                carry_t_58 = cx_58.prepare_and(cy_58_p, FUNC_XOR(FUNC_XOR(triples[5].a, x[57].get_mask()), FUNC_XOR(triples[4].a, x[58].get_mask())), triples[4].c);  // and_19
                break;
            case 6:
                carry_t_58.complete_and();
                carry_58 = carry_t_58 ^ carry_59;  // carry[58]
                cx_57 = carry_58 ^ x[57];  // cx[57]
                cy_57 = carry_58 ^ y[57];  // cy[57]
                cy_57_p = cy_57.zero_add(triples[5].b);  // cy[57]', mask=b5
                // and_23: a5=triples[5].a, b5=triples[5].b, c5=triples[5].c, output mask=((a6-f(x[56]))-(a5-f(x[57])))
                carry_t_57 = cx_57.prepare_and(cy_57_p, FUNC_XOR(FUNC_XOR(triples[6].a, x[56].get_mask()), FUNC_XOR(triples[5].a, x[57].get_mask())), triples[5].c);  // and_23
                break;
            case 7:
                carry_t_57.complete_and();
                carry_57 = carry_t_57 ^ carry_58;  // carry[57]
                cx_56 = carry_57 ^ x[56];  // cx[56]
                cy_56 = carry_57 ^ y[56];  // cy[56]
                cy_56_p = cy_56.zero_add(triples[6].b);  // cy[56]', mask=b6
                // and_27: a6=triples[6].a, b6=triples[6].b, c6=triples[6].c, output mask=((a7-f(x[55]))-(a6-f(x[56])))
                carry_t_56 = cx_56.prepare_and(cy_56_p, FUNC_XOR(FUNC_XOR(triples[7].a, x[55].get_mask()), FUNC_XOR(triples[6].a, x[56].get_mask())), triples[6].c);  // and_27
                break;
            case 8:
                carry_t_56.complete_and();
                carry_56 = carry_t_56 ^ carry_57;  // carry[56]
                cx_55 = carry_56 ^ x[55];  // cx[55]
                cy_55 = carry_56 ^ y[55];  // cy[55]
                cy_55_p = cy_55.zero_add(triples[7].b);  // cy[55]', mask=b7
                // and_31: a7=triples[7].a, b7=triples[7].b, c7=triples[7].c, output mask=((a8-f(x[54]))-(a7-f(x[55])))
                carry_t_55 = cx_55.prepare_and(cy_55_p, FUNC_XOR(FUNC_XOR(triples[8].a, x[54].get_mask()), FUNC_XOR(triples[7].a, x[55].get_mask())), triples[7].c);  // and_31
                break;
            case 9:
                carry_t_55.complete_and();
                carry_55 = carry_t_55 ^ carry_56;  // carry[55]
                cx_54 = carry_55 ^ x[54];  // cx[54]
                cy_54 = carry_55 ^ y[54];  // cy[54]
                cy_54_p = cy_54.zero_add(triples[8].b);  // cy[54]', mask=b8
                // and_35: a8=triples[8].a, b8=triples[8].b, c8=triples[8].c, output mask=((a9-f(x[53]))-(a8-f(x[54])))
                carry_t_54 = cx_54.prepare_and(cy_54_p, FUNC_XOR(FUNC_XOR(triples[9].a, x[53].get_mask()), FUNC_XOR(triples[8].a, x[54].get_mask())), triples[8].c);  // and_35
                break;
            case 10:
                carry_t_54.complete_and();
                carry_54 = carry_t_54 ^ carry_55;  // carry[54]
                cx_53 = carry_54 ^ x[53];  // cx[53]
                cy_53 = carry_54 ^ y[53];  // cy[53]
                cy_53_p = cy_53.zero_add(triples[9].b);  // cy[53]', mask=b9
                // and_39: a9=triples[9].a, b9=triples[9].b, c9=triples[9].c, output mask=((a10-f(x[52]))-(a9-f(x[53])))
                carry_t_53 = cx_53.prepare_and(cy_53_p, FUNC_XOR(FUNC_XOR(triples[10].a, x[52].get_mask()), FUNC_XOR(triples[9].a, x[53].get_mask())), triples[9].c);  // and_39
                break;
            case 11:
                carry_t_53.complete_and();
                carry_53 = carry_t_53 ^ carry_54;  // carry[53]
                cx_52 = carry_53 ^ x[52];  // cx[52]
                cy_52 = carry_53 ^ y[52];  // cy[52]
                cy_52_p = cy_52.zero_add(triples[10].b);  // cy[52]', mask=b10
                // and_43: a10=triples[10].a, b10=triples[10].b, c10=triples[10].c, output mask=((a11-f(x[51]))-(a10-f(x[52])))
                carry_t_52 = cx_52.prepare_and(cy_52_p, FUNC_XOR(FUNC_XOR(triples[11].a, x[51].get_mask()), FUNC_XOR(triples[10].a, x[52].get_mask())), triples[10].c);  // and_43
                break;
            case 12:
                carry_t_52.complete_and();
                carry_52 = carry_t_52 ^ carry_53;  // carry[52]
                cx_51 = carry_52 ^ x[51];  // cx[51]
                cy_51 = carry_52 ^ y[51];  // cy[51]
                cy_51_p = cy_51.zero_add(triples[11].b);  // cy[51]', mask=b11
                // and_47: a11=triples[11].a, b11=triples[11].b, c11=triples[11].c, output mask=((a12-f(x[50]))-(a11-f(x[51])))
                carry_t_51 = cx_51.prepare_and(cy_51_p, FUNC_XOR(FUNC_XOR(triples[12].a, x[50].get_mask()), FUNC_XOR(triples[11].a, x[51].get_mask())), triples[11].c);  // and_47
                break;
            case 13:
                carry_t_51.complete_and();
                carry_51 = carry_t_51 ^ carry_52;  // carry[51]
                cx_50 = carry_51 ^ x[50];  // cx[50]
                cy_50 = carry_51 ^ y[50];  // cy[50]
                cy_50_p = cy_50.zero_add(triples[12].b);  // cy[50]', mask=b12
                // and_51: a12=triples[12].a, b12=triples[12].b, c12=triples[12].c, output mask=((a13-f(x[49]))-(a12-f(x[50])))
                carry_t_50 = cx_50.prepare_and(cy_50_p, FUNC_XOR(FUNC_XOR(triples[13].a, x[49].get_mask()), FUNC_XOR(triples[12].a, x[50].get_mask())), triples[12].c);  // and_51
                break;
            case 14:
                carry_t_50.complete_and();
                carry_50 = carry_t_50 ^ carry_51;  // carry[50]
                cx_49 = carry_50 ^ x[49];  // cx[49]
                cy_49 = carry_50 ^ y[49];  // cy[49]
                cy_49_p = cy_49.zero_add(triples[13].b);  // cy[49]', mask=b13
                // and_55: a13=triples[13].a, b13=triples[13].b, c13=triples[13].c, output mask=((a14-f(x[48]))-(a13-f(x[49])))
                carry_t_49 = cx_49.prepare_and(cy_49_p, FUNC_XOR(FUNC_XOR(triples[14].a, x[48].get_mask()), FUNC_XOR(triples[13].a, x[49].get_mask())), triples[13].c);  // and_55
                break;
            case 15:
                carry_t_49.complete_and();
                carry_49 = carry_t_49 ^ carry_50;  // carry[49]
                cx_48 = carry_49 ^ x[48];  // cx[48]
                cy_48 = carry_49 ^ y[48];  // cy[48]
                cy_48_p = cy_48.zero_add(triples[14].b);  // cy[48]', mask=b14
                // and_59: a14=triples[14].a, b14=triples[14].b, c14=triples[14].c, output mask=((a15-f(x[47]))-(a14-f(x[48])))
                carry_t_48 = cx_48.prepare_and(cy_48_p, FUNC_XOR(FUNC_XOR(triples[15].a, x[47].get_mask()), FUNC_XOR(triples[14].a, x[48].get_mask())), triples[14].c);  // and_59
                break;
            case 16:
                carry_t_48.complete_and();
                carry_48 = carry_t_48 ^ carry_49;  // carry[48]
                cx_47 = carry_48 ^ x[47];  // cx[47]
                cy_47 = carry_48 ^ y[47];  // cy[47]
                cy_47_p = cy_47.zero_add(triples[15].b);  // cy[47]', mask=b15
                // and_63: a15=triples[15].a, b15=triples[15].b, c15=triples[15].c, output mask=((a16-f(x[46]))-(a15-f(x[47])))
                carry_t_47 = cx_47.prepare_and(cy_47_p, FUNC_XOR(FUNC_XOR(triples[16].a, x[46].get_mask()), FUNC_XOR(triples[15].a, x[47].get_mask())), triples[15].c);  // and_63
                break;
            case 17:
                carry_t_47.complete_and();
                carry_47 = carry_t_47 ^ carry_48;  // carry[47]
                cx_46 = carry_47 ^ x[46];  // cx[46]
                cy_46 = carry_47 ^ y[46];  // cy[46]
                cy_46_p = cy_46.zero_add(triples[16].b);  // cy[46]', mask=b16
                // and_67: a16=triples[16].a, b16=triples[16].b, c16=triples[16].c, output mask=((a17-f(x[45]))-(a16-f(x[46])))
                carry_t_46 = cx_46.prepare_and(cy_46_p, FUNC_XOR(FUNC_XOR(triples[17].a, x[45].get_mask()), FUNC_XOR(triples[16].a, x[46].get_mask())), triples[16].c);  // and_67
                break;
            case 18:
                carry_t_46.complete_and();
                carry_46 = carry_t_46 ^ carry_47;  // carry[46]
                cx_45 = carry_46 ^ x[45];  // cx[45]
                cy_45 = carry_46 ^ y[45];  // cy[45]
                cy_45_p = cy_45.zero_add(triples[17].b);  // cy[45]', mask=b17
                // and_71: a17=triples[17].a, b17=triples[17].b, c17=triples[17].c, output mask=((a18-f(x[44]))-(a17-f(x[45])))
                carry_t_45 = cx_45.prepare_and(cy_45_p, FUNC_XOR(FUNC_XOR(triples[18].a, x[44].get_mask()), FUNC_XOR(triples[17].a, x[45].get_mask())), triples[17].c);  // and_71
                break;
            case 19:
                carry_t_45.complete_and();
                carry_45 = carry_t_45 ^ carry_46;  // carry[45]
                cx_44 = carry_45 ^ x[44];  // cx[44]
                cy_44 = carry_45 ^ y[44];  // cy[44]
                cy_44_p = cy_44.zero_add(triples[18].b);  // cy[44]', mask=b18
                // and_75: a18=triples[18].a, b18=triples[18].b, c18=triples[18].c, output mask=((a19-f(x[43]))-(a18-f(x[44])))
                carry_t_44 = cx_44.prepare_and(cy_44_p, FUNC_XOR(FUNC_XOR(triples[19].a, x[43].get_mask()), FUNC_XOR(triples[18].a, x[44].get_mask())), triples[18].c);  // and_75
                break;
            case 20:
                carry_t_44.complete_and();
                carry_44 = carry_t_44 ^ carry_45;  // carry[44]
                cx_43 = carry_44 ^ x[43];  // cx[43]
                cy_43 = carry_44 ^ y[43];  // cy[43]
                cy_43_p = cy_43.zero_add(triples[19].b);  // cy[43]', mask=b19
                // and_79: a19=triples[19].a, b19=triples[19].b, c19=triples[19].c, output mask=((a20-f(x[42]))-(a19-f(x[43])))
                carry_t_43 = cx_43.prepare_and(cy_43_p, FUNC_XOR(FUNC_XOR(triples[20].a, x[42].get_mask()), FUNC_XOR(triples[19].a, x[43].get_mask())), triples[19].c);  // and_79
                break;
            case 21:
                carry_t_43.complete_and();
                carry_43 = carry_t_43 ^ carry_44;  // carry[43]
                cx_42 = carry_43 ^ x[42];  // cx[42]
                cy_42 = carry_43 ^ y[42];  // cy[42]
                cy_42_p = cy_42.zero_add(triples[20].b);  // cy[42]', mask=b20
                // and_83: a20=triples[20].a, b20=triples[20].b, c20=triples[20].c, output mask=((a21-f(x[41]))-(a20-f(x[42])))
                carry_t_42 = cx_42.prepare_and(cy_42_p, FUNC_XOR(FUNC_XOR(triples[21].a, x[41].get_mask()), FUNC_XOR(triples[20].a, x[42].get_mask())), triples[20].c);  // and_83
                break;
            case 22:
                carry_t_42.complete_and();
                carry_42 = carry_t_42 ^ carry_43;  // carry[42]
                cx_41 = carry_42 ^ x[41];  // cx[41]
                cy_41 = carry_42 ^ y[41];  // cy[41]
                cy_41_p = cy_41.zero_add(triples[21].b);  // cy[41]', mask=b21
                // and_87: a21=triples[21].a, b21=triples[21].b, c21=triples[21].c, output mask=((a22-f(x[40]))-(a21-f(x[41])))
                carry_t_41 = cx_41.prepare_and(cy_41_p, FUNC_XOR(FUNC_XOR(triples[22].a, x[40].get_mask()), FUNC_XOR(triples[21].a, x[41].get_mask())), triples[21].c);  // and_87
                break;
            case 23:
                carry_t_41.complete_and();
                carry_41 = carry_t_41 ^ carry_42;  // carry[41]
                cx_40 = carry_41 ^ x[40];  // cx[40]
                cy_40 = carry_41 ^ y[40];  // cy[40]
                cy_40_p = cy_40.zero_add(triples[22].b);  // cy[40]', mask=b22
                // and_91: a22=triples[22].a, b22=triples[22].b, c22=triples[22].c, output mask=((a23-f(x[39]))-(a22-f(x[40])))
                carry_t_40 = cx_40.prepare_and(cy_40_p, FUNC_XOR(FUNC_XOR(triples[23].a, x[39].get_mask()), FUNC_XOR(triples[22].a, x[40].get_mask())), triples[22].c);  // and_91
                break;
            case 24:
                carry_t_40.complete_and();
                carry_40 = carry_t_40 ^ carry_41;  // carry[40]
                cx_39 = carry_40 ^ x[39];  // cx[39]
                cy_39 = carry_40 ^ y[39];  // cy[39]
                cy_39_p = cy_39.zero_add(triples[23].b);  // cy[39]', mask=b23
                // and_95: a23=triples[23].a, b23=triples[23].b, c23=triples[23].c, output mask=((a24-f(x[38]))-(a23-f(x[39])))
                carry_t_39 = cx_39.prepare_and(cy_39_p, FUNC_XOR(FUNC_XOR(triples[24].a, x[38].get_mask()), FUNC_XOR(triples[23].a, x[39].get_mask())), triples[23].c);  // and_95
                break;
            case 25:
                carry_t_39.complete_and();
                carry_39 = carry_t_39 ^ carry_40;  // carry[39]
                cx_38 = carry_39 ^ x[38];  // cx[38]
                cy_38 = carry_39 ^ y[38];  // cy[38]
                cy_38_p = cy_38.zero_add(triples[24].b);  // cy[38]', mask=b24
                // and_99: a24=triples[24].a, b24=triples[24].b, c24=triples[24].c, output mask=((a25-f(x[37]))-(a24-f(x[38])))
                carry_t_38 = cx_38.prepare_and(cy_38_p, FUNC_XOR(FUNC_XOR(triples[25].a, x[37].get_mask()), FUNC_XOR(triples[24].a, x[38].get_mask())), triples[24].c);  // and_99
                break;
            case 26:
                carry_t_38.complete_and();
                carry_38 = carry_t_38 ^ carry_39;  // carry[38]
                cx_37 = carry_38 ^ x[37];  // cx[37]
                cy_37 = carry_38 ^ y[37];  // cy[37]
                cy_37_p = cy_37.zero_add(triples[25].b);  // cy[37]', mask=b25
                // and_103: a25=triples[25].a, b25=triples[25].b, c25=triples[25].c, output mask=((a26-f(x[36]))-(a25-f(x[37])))
                carry_t_37 = cx_37.prepare_and(cy_37_p, FUNC_XOR(FUNC_XOR(triples[26].a, x[36].get_mask()), FUNC_XOR(triples[25].a, x[37].get_mask())), triples[25].c);  // and_103
                break;
            case 27:
                carry_t_37.complete_and();
                carry_37 = carry_t_37 ^ carry_38;  // carry[37]
                cx_36 = carry_37 ^ x[36];  // cx[36]
                cy_36 = carry_37 ^ y[36];  // cy[36]
                cy_36_p = cy_36.zero_add(triples[26].b);  // cy[36]', mask=b26
                // and_107: a26=triples[26].a, b26=triples[26].b, c26=triples[26].c, output mask=((a27-f(x[35]))-(a26-f(x[36])))
                carry_t_36 = cx_36.prepare_and(cy_36_p, FUNC_XOR(FUNC_XOR(triples[27].a, x[35].get_mask()), FUNC_XOR(triples[26].a, x[36].get_mask())), triples[26].c);  // and_107
                break;
            case 28:
                carry_t_36.complete_and();
                carry_36 = carry_t_36 ^ carry_37;  // carry[36]
                cx_35 = carry_36 ^ x[35];  // cx[35]
                cy_35 = carry_36 ^ y[35];  // cy[35]
                cy_35_p = cy_35.zero_add(triples[27].b);  // cy[35]', mask=b27
                // and_111: a27=triples[27].a, b27=triples[27].b, c27=triples[27].c, output mask=((a28-f(x[34]))-(a27-f(x[35])))
                carry_t_35 = cx_35.prepare_and(cy_35_p, FUNC_XOR(FUNC_XOR(triples[28].a, x[34].get_mask()), FUNC_XOR(triples[27].a, x[35].get_mask())), triples[27].c);  // and_111
                break;
            case 29:
                carry_t_35.complete_and();
                carry_35 = carry_t_35 ^ carry_36;  // carry[35]
                cx_34 = carry_35 ^ x[34];  // cx[34]
                cy_34 = carry_35 ^ y[34];  // cy[34]
                cy_34_p = cy_34.zero_add(triples[28].b);  // cy[34]', mask=b28
                // and_115: a28=triples[28].a, b28=triples[28].b, c28=triples[28].c, output mask=((a29-f(x[33]))-(a28-f(x[34])))
                carry_t_34 = cx_34.prepare_and(cy_34_p, FUNC_XOR(FUNC_XOR(triples[29].a, x[33].get_mask()), FUNC_XOR(triples[28].a, x[34].get_mask())), triples[28].c);  // and_115
                break;
            case 30:
                carry_t_34.complete_and();
                carry_34 = carry_t_34 ^ carry_35;  // carry[34]
                cx_33 = carry_34 ^ x[33];  // cx[33]
                cy_33 = carry_34 ^ y[33];  // cy[33]
                cy_33_p = cy_33.zero_add(triples[29].b);  // cy[33]', mask=b29
                // and_119: a29=triples[29].a, b29=triples[29].b, c29=triples[29].c, output mask=((a30-f(x[32]))-(a29-f(x[33])))
                carry_t_33 = cx_33.prepare_and(cy_33_p, FUNC_XOR(FUNC_XOR(triples[30].a, x[32].get_mask()), FUNC_XOR(triples[29].a, x[33].get_mask())), triples[29].c);  // and_119
                break;
            case 31:
                carry_t_33.complete_and();
                carry_33 = carry_t_33 ^ carry_34;  // carry[33]
                cx_32 = carry_33 ^ x[32];  // cx[32]
                cy_32 = carry_33 ^ y[32];  // cy[32]
                cy_32_p = cy_32.zero_add(triples[30].b);  // cy[32]', mask=b30
                // and_123: a30=triples[30].a, b30=triples[30].b, c30=triples[30].c, output mask=((a31-f(x[31]))-(a30-f(x[32])))
                carry_t_32 = cx_32.prepare_and(cy_32_p, FUNC_XOR(FUNC_XOR(triples[31].a, x[31].get_mask()), FUNC_XOR(triples[30].a, x[32].get_mask())), triples[30].c);  // and_123
                break;
            case 32:
                carry_t_32.complete_and();
                carry_32 = carry_t_32 ^ carry_33;  // carry[32]
                cx_31 = carry_32 ^ x[31];  // cx[31]
                cy_31 = carry_32 ^ y[31];  // cy[31]
                cy_31_p = cy_31.zero_add(triples[31].b);  // cy[31]', mask=b31
                // and_127: a31=triples[31].a, b31=triples[31].b, c31=triples[31].c, output mask=((a32-f(x[30]))-(a31-f(x[31])))
                carry_t_31 = cx_31.prepare_and(cy_31_p, FUNC_XOR(FUNC_XOR(triples[32].a, x[30].get_mask()), FUNC_XOR(triples[31].a, x[31].get_mask())), triples[31].c);  // and_127
                break;
            case 33:
                carry_t_31.complete_and();
                carry_31 = carry_t_31 ^ carry_32;  // carry[31]
                cx_30 = carry_31 ^ x[30];  // cx[30]
                cy_30 = carry_31 ^ y[30];  // cy[30]
                cy_30_p = cy_30.zero_add(triples[32].b);  // cy[30]', mask=b32
                // and_131: a32=triples[32].a, b32=triples[32].b, c32=triples[32].c, output mask=((a33-f(x[29]))-(a32-f(x[30])))
                carry_t_30 = cx_30.prepare_and(cy_30_p, FUNC_XOR(FUNC_XOR(triples[33].a, x[29].get_mask()), FUNC_XOR(triples[32].a, x[30].get_mask())), triples[32].c);  // and_131
                break;
            case 34:
                carry_t_30.complete_and();
                carry_30 = carry_t_30 ^ carry_31;  // carry[30]
                cx_29 = carry_30 ^ x[29];  // cx[29]
                cy_29 = carry_30 ^ y[29];  // cy[29]
                cy_29_p = cy_29.zero_add(triples[33].b);  // cy[29]', mask=b33
                // and_135: a33=triples[33].a, b33=triples[33].b, c33=triples[33].c, output mask=((a34-f(x[28]))-(a33-f(x[29])))
                carry_t_29 = cx_29.prepare_and(cy_29_p, FUNC_XOR(FUNC_XOR(triples[34].a, x[28].get_mask()), FUNC_XOR(triples[33].a, x[29].get_mask())), triples[33].c);  // and_135
                break;
            case 35:
                carry_t_29.complete_and();
                carry_29 = carry_t_29 ^ carry_30;  // carry[29]
                cx_28 = carry_29 ^ x[28];  // cx[28]
                cy_28 = carry_29 ^ y[28];  // cy[28]
                cy_28_p = cy_28.zero_add(triples[34].b);  // cy[28]', mask=b34
                // and_139: a34=triples[34].a, b34=triples[34].b, c34=triples[34].c, output mask=((a35-f(x[27]))-(a34-f(x[28])))
                carry_t_28 = cx_28.prepare_and(cy_28_p, FUNC_XOR(FUNC_XOR(triples[35].a, x[27].get_mask()), FUNC_XOR(triples[34].a, x[28].get_mask())), triples[34].c);  // and_139
                break;
            case 36:
                carry_t_28.complete_and();
                carry_28 = carry_t_28 ^ carry_29;  // carry[28]
                cx_27 = carry_28 ^ x[27];  // cx[27]
                cy_27 = carry_28 ^ y[27];  // cy[27]
                cy_27_p = cy_27.zero_add(triples[35].b);  // cy[27]', mask=b35
                // and_143: a35=triples[35].a, b35=triples[35].b, c35=triples[35].c, output mask=((a36-f(x[26]))-(a35-f(x[27])))
                carry_t_27 = cx_27.prepare_and(cy_27_p, FUNC_XOR(FUNC_XOR(triples[36].a, x[26].get_mask()), FUNC_XOR(triples[35].a, x[27].get_mask())), triples[35].c);  // and_143
                break;
            case 37:
                carry_t_27.complete_and();
                carry_27 = carry_t_27 ^ carry_28;  // carry[27]
                cx_26 = carry_27 ^ x[26];  // cx[26]
                cy_26 = carry_27 ^ y[26];  // cy[26]
                cy_26_p = cy_26.zero_add(triples[36].b);  // cy[26]', mask=b36
                // and_147: a36=triples[36].a, b36=triples[36].b, c36=triples[36].c, output mask=((a37-f(x[25]))-(a36-f(x[26])))
                carry_t_26 = cx_26.prepare_and(cy_26_p, FUNC_XOR(FUNC_XOR(triples[37].a, x[25].get_mask()), FUNC_XOR(triples[36].a, x[26].get_mask())), triples[36].c);  // and_147
                break;
            case 38:
                carry_t_26.complete_and();
                carry_26 = carry_t_26 ^ carry_27;  // carry[26]
                cx_25 = carry_26 ^ x[25];  // cx[25]
                cy_25 = carry_26 ^ y[25];  // cy[25]
                cy_25_p = cy_25.zero_add(triples[37].b);  // cy[25]', mask=b37
                // and_151: a37=triples[37].a, b37=triples[37].b, c37=triples[37].c, output mask=((a38-f(x[24]))-(a37-f(x[25])))
                carry_t_25 = cx_25.prepare_and(cy_25_p, FUNC_XOR(FUNC_XOR(triples[38].a, x[24].get_mask()), FUNC_XOR(triples[37].a, x[25].get_mask())), triples[37].c);  // and_151
                break;
            case 39:
                carry_t_25.complete_and();
                carry_25 = carry_t_25 ^ carry_26;  // carry[25]
                cx_24 = carry_25 ^ x[24];  // cx[24]
                cy_24 = carry_25 ^ y[24];  // cy[24]
                cy_24_p = cy_24.zero_add(triples[38].b);  // cy[24]', mask=b38
                // and_155: a38=triples[38].a, b38=triples[38].b, c38=triples[38].c, output mask=((a39-f(x[23]))-(a38-f(x[24])))
                carry_t_24 = cx_24.prepare_and(cy_24_p, FUNC_XOR(FUNC_XOR(triples[39].a, x[23].get_mask()), FUNC_XOR(triples[38].a, x[24].get_mask())), triples[38].c);  // and_155
                break;
            case 40:
                carry_t_24.complete_and();
                carry_24 = carry_t_24 ^ carry_25;  // carry[24]
                cx_23 = carry_24 ^ x[23];  // cx[23]
                cy_23 = carry_24 ^ y[23];  // cy[23]
                cy_23_p = cy_23.zero_add(triples[39].b);  // cy[23]', mask=b39
                // and_159: a39=triples[39].a, b39=triples[39].b, c39=triples[39].c, output mask=((a40-f(x[22]))-(a39-f(x[23])))
                carry_t_23 = cx_23.prepare_and(cy_23_p, FUNC_XOR(FUNC_XOR(triples[40].a, x[22].get_mask()), FUNC_XOR(triples[39].a, x[23].get_mask())), triples[39].c);  // and_159
                break;
            case 41:
                carry_t_23.complete_and();
                carry_23 = carry_t_23 ^ carry_24;  // carry[23]
                cx_22 = carry_23 ^ x[22];  // cx[22]
                cy_22 = carry_23 ^ y[22];  // cy[22]
                cy_22_p = cy_22.zero_add(triples[40].b);  // cy[22]', mask=b40
                // and_163: a40=triples[40].a, b40=triples[40].b, c40=triples[40].c, output mask=((a41-f(x[21]))-(a40-f(x[22])))
                carry_t_22 = cx_22.prepare_and(cy_22_p, FUNC_XOR(FUNC_XOR(triples[41].a, x[21].get_mask()), FUNC_XOR(triples[40].a, x[22].get_mask())), triples[40].c);  // and_163
                break;
            case 42:
                carry_t_22.complete_and();
                carry_22 = carry_t_22 ^ carry_23;  // carry[22]
                cx_21 = carry_22 ^ x[21];  // cx[21]
                cy_21 = carry_22 ^ y[21];  // cy[21]
                cy_21_p = cy_21.zero_add(triples[41].b);  // cy[21]', mask=b41
                // and_167: a41=triples[41].a, b41=triples[41].b, c41=triples[41].c, output mask=((a42-f(x[20]))-(a41-f(x[21])))
                carry_t_21 = cx_21.prepare_and(cy_21_p, FUNC_XOR(FUNC_XOR(triples[42].a, x[20].get_mask()), FUNC_XOR(triples[41].a, x[21].get_mask())), triples[41].c);  // and_167
                break;
            case 43:
                carry_t_21.complete_and();
                carry_21 = carry_t_21 ^ carry_22;  // carry[21]
                cx_20 = carry_21 ^ x[20];  // cx[20]
                cy_20 = carry_21 ^ y[20];  // cy[20]
                cy_20_p = cy_20.zero_add(triples[42].b);  // cy[20]', mask=b42
                // and_171: a42=triples[42].a, b42=triples[42].b, c42=triples[42].c, output mask=((a43-f(x[19]))-(a42-f(x[20])))
                carry_t_20 = cx_20.prepare_and(cy_20_p, FUNC_XOR(FUNC_XOR(triples[43].a, x[19].get_mask()), FUNC_XOR(triples[42].a, x[20].get_mask())), triples[42].c);  // and_171
                break;
            case 44:
                carry_t_20.complete_and();
                carry_20 = carry_t_20 ^ carry_21;  // carry[20]
                cx_19 = carry_20 ^ x[19];  // cx[19]
                cy_19 = carry_20 ^ y[19];  // cy[19]
                cy_19_p = cy_19.zero_add(triples[43].b);  // cy[19]', mask=b43
                // and_175: a43=triples[43].a, b43=triples[43].b, c43=triples[43].c, output mask=((a44-f(x[18]))-(a43-f(x[19])))
                carry_t_19 = cx_19.prepare_and(cy_19_p, FUNC_XOR(FUNC_XOR(triples[44].a, x[18].get_mask()), FUNC_XOR(triples[43].a, x[19].get_mask())), triples[43].c);  // and_175
                break;
            case 45:
                carry_t_19.complete_and();
                carry_19 = carry_t_19 ^ carry_20;  // carry[19]
                cx_18 = carry_19 ^ x[18];  // cx[18]
                cy_18 = carry_19 ^ y[18];  // cy[18]
                cy_18_p = cy_18.zero_add(triples[44].b);  // cy[18]', mask=b44
                // and_179: a44=triples[44].a, b44=triples[44].b, c44=triples[44].c, output mask=((a45-f(x[17]))-(a44-f(x[18])))
                carry_t_18 = cx_18.prepare_and(cy_18_p, FUNC_XOR(FUNC_XOR(triples[45].a, x[17].get_mask()), FUNC_XOR(triples[44].a, x[18].get_mask())), triples[44].c);  // and_179
                break;
            case 46:
                carry_t_18.complete_and();
                carry_18 = carry_t_18 ^ carry_19;  // carry[18]
                cx_17 = carry_18 ^ x[17];  // cx[17]
                cy_17 = carry_18 ^ y[17];  // cy[17]
                cy_17_p = cy_17.zero_add(triples[45].b);  // cy[17]', mask=b45
                // and_183: a45=triples[45].a, b45=triples[45].b, c45=triples[45].c, output mask=((a46-f(x[16]))-(a45-f(x[17])))
                carry_t_17 = cx_17.prepare_and(cy_17_p, FUNC_XOR(FUNC_XOR(triples[46].a, x[16].get_mask()), FUNC_XOR(triples[45].a, x[17].get_mask())), triples[45].c);  // and_183
                break;
            case 47:
                carry_t_17.complete_and();
                carry_17 = carry_t_17 ^ carry_18;  // carry[17]
                cx_16 = carry_17 ^ x[16];  // cx[16]
                cy_16 = carry_17 ^ y[16];  // cy[16]
                cy_16_p = cy_16.zero_add(triples[46].b);  // cy[16]', mask=b46
                // and_187: a46=triples[46].a, b46=triples[46].b, c46=triples[46].c, output mask=((a47-f(x[15]))-(a46-f(x[16])))
                carry_t_16 = cx_16.prepare_and(cy_16_p, FUNC_XOR(FUNC_XOR(triples[47].a, x[15].get_mask()), FUNC_XOR(triples[46].a, x[16].get_mask())), triples[46].c);  // and_187
                break;
            case 48:
                carry_t_16.complete_and();
                carry_16 = carry_t_16 ^ carry_17;  // carry[16]
                cx_15 = carry_16 ^ x[15];  // cx[15]
                cy_15 = carry_16 ^ y[15];  // cy[15]
                cy_15_p = cy_15.zero_add(triples[47].b);  // cy[15]', mask=b47
                // and_191: a47=triples[47].a, b47=triples[47].b, c47=triples[47].c, output mask=((a48-f(x[14]))-(a47-f(x[15])))
                carry_t_15 = cx_15.prepare_and(cy_15_p, FUNC_XOR(FUNC_XOR(triples[48].a, x[14].get_mask()), FUNC_XOR(triples[47].a, x[15].get_mask())), triples[47].c);  // and_191
                break;
            case 49:
                carry_t_15.complete_and();
                carry_15 = carry_t_15 ^ carry_16;  // carry[15]
                cx_14 = carry_15 ^ x[14];  // cx[14]
                cy_14 = carry_15 ^ y[14];  // cy[14]
                cy_14_p = cy_14.zero_add(triples[48].b);  // cy[14]', mask=b48
                // and_195: a48=triples[48].a, b48=triples[48].b, c48=triples[48].c, output mask=((a49-f(x[13]))-(a48-f(x[14])))
                carry_t_14 = cx_14.prepare_and(cy_14_p, FUNC_XOR(FUNC_XOR(triples[49].a, x[13].get_mask()), FUNC_XOR(triples[48].a, x[14].get_mask())), triples[48].c);  // and_195
                break;
            case 50:
                carry_t_14.complete_and();
                carry_14 = carry_t_14 ^ carry_15;  // carry[14]
                cx_13 = carry_14 ^ x[13];  // cx[13]
                cy_13 = carry_14 ^ y[13];  // cy[13]
                cy_13_p = cy_13.zero_add(triples[49].b);  // cy[13]', mask=b49
                // and_199: a49=triples[49].a, b49=triples[49].b, c49=triples[49].c, output mask=((a50-f(x[12]))-(a49-f(x[13])))
                carry_t_13 = cx_13.prepare_and(cy_13_p, FUNC_XOR(FUNC_XOR(triples[50].a, x[12].get_mask()), FUNC_XOR(triples[49].a, x[13].get_mask())), triples[49].c);  // and_199
                break;
            case 51:
                carry_t_13.complete_and();
                carry_13 = carry_t_13 ^ carry_14;  // carry[13]
                cx_12 = carry_13 ^ x[12];  // cx[12]
                cy_12 = carry_13 ^ y[12];  // cy[12]
                cy_12_p = cy_12.zero_add(triples[50].b);  // cy[12]', mask=b50
                // and_203: a50=triples[50].a, b50=triples[50].b, c50=triples[50].c, output mask=((a51-f(x[11]))-(a50-f(x[12])))
                carry_t_12 = cx_12.prepare_and(cy_12_p, FUNC_XOR(FUNC_XOR(triples[51].a, x[11].get_mask()), FUNC_XOR(triples[50].a, x[12].get_mask())), triples[50].c);  // and_203
                break;
            case 52:
                carry_t_12.complete_and();
                carry_12 = carry_t_12 ^ carry_13;  // carry[12]
                cx_11 = carry_12 ^ x[11];  // cx[11]
                cy_11 = carry_12 ^ y[11];  // cy[11]
                cy_11_p = cy_11.zero_add(triples[51].b);  // cy[11]', mask=b51
                // and_207: a51=triples[51].a, b51=triples[51].b, c51=triples[51].c, output mask=((a52-f(x[10]))-(a51-f(x[11])))
                carry_t_11 = cx_11.prepare_and(cy_11_p, FUNC_XOR(FUNC_XOR(triples[52].a, x[10].get_mask()), FUNC_XOR(triples[51].a, x[11].get_mask())), triples[51].c);  // and_207
                break;
            case 53:
                carry_t_11.complete_and();
                carry_11 = carry_t_11 ^ carry_12;  // carry[11]
                cx_10 = carry_11 ^ x[10];  // cx[10]
                cy_10 = carry_11 ^ y[10];  // cy[10]
                cy_10_p = cy_10.zero_add(triples[52].b);  // cy[10]', mask=b52
                // and_211: a52=triples[52].a, b52=triples[52].b, c52=triples[52].c, output mask=((a53-f(x[9]))-(a52-f(x[10])))
                carry_t_10 = cx_10.prepare_and(cy_10_p, FUNC_XOR(FUNC_XOR(triples[53].a, x[9].get_mask()), FUNC_XOR(triples[52].a, x[10].get_mask())), triples[52].c);  // and_211
                break;
            case 54:
                carry_t_10.complete_and();
                carry_10 = carry_t_10 ^ carry_11;  // carry[10]
                cx_9 = carry_10 ^ x[9];  // cx[9]
                cy_9 = carry_10 ^ y[9];  // cy[9]
                cy_9_p = cy_9.zero_add(triples[53].b);  // cy[9]', mask=b53
                // and_215: a53=triples[53].a, b53=triples[53].b, c53=triples[53].c, output mask=((a54-f(x[8]))-(a53-f(x[9])))
                carry_t_9 = cx_9.prepare_and(cy_9_p, FUNC_XOR(FUNC_XOR(triples[54].a, x[8].get_mask()), FUNC_XOR(triples[53].a, x[9].get_mask())), triples[53].c);  // and_215
                break;
            case 55:
                carry_t_9.complete_and();
                carry_9 = carry_t_9 ^ carry_10;  // carry[9]
                cx_8 = carry_9 ^ x[8];  // cx[8]
                cy_8 = carry_9 ^ y[8];  // cy[8]
                cy_8_p = cy_8.zero_add(triples[54].b);  // cy[8]', mask=b54
                // and_219: a54=triples[54].a, b54=triples[54].b, c54=triples[54].c, output mask=((a55-f(x[7]))-(a54-f(x[8])))
                carry_t_8 = cx_8.prepare_and(cy_8_p, FUNC_XOR(FUNC_XOR(triples[55].a, x[7].get_mask()), FUNC_XOR(triples[54].a, x[8].get_mask())), triples[54].c);  // and_219
                break;
            case 56:
                carry_t_8.complete_and();
                carry_8 = carry_t_8 ^ carry_9;  // carry[8]
                cx_7 = carry_8 ^ x[7];  // cx[7]
                cy_7 = carry_8 ^ y[7];  // cy[7]
                cy_7_p = cy_7.zero_add(triples[55].b);  // cy[7]', mask=b55
                // and_223: a55=triples[55].a, b55=triples[55].b, c55=triples[55].c, output mask=((a56-f(x[6]))-(a55-f(x[7])))
                carry_t_7 = cx_7.prepare_and(cy_7_p, FUNC_XOR(FUNC_XOR(triples[56].a, x[6].get_mask()), FUNC_XOR(triples[55].a, x[7].get_mask())), triples[55].c);  // and_223
                break;
            case 57:
                carry_t_7.complete_and();
                carry_7 = carry_t_7 ^ carry_8;  // carry[7]
                cx_6 = carry_7 ^ x[6];  // cx[6]
                cy_6 = carry_7 ^ y[6];  // cy[6]
                cy_6_p = cy_6.zero_add(triples[56].b);  // cy[6]', mask=b56
                // and_227: a56=triples[56].a, b56=triples[56].b, c56=triples[56].c, output mask=((a57-f(x[5]))-(a56-f(x[6])))
                carry_t_6 = cx_6.prepare_and(cy_6_p, FUNC_XOR(FUNC_XOR(triples[57].a, x[5].get_mask()), FUNC_XOR(triples[56].a, x[6].get_mask())), triples[56].c);  // and_227
                break;
            case 58:
                carry_t_6.complete_and();
                carry_6 = carry_t_6 ^ carry_7;  // carry[6]
                cx_5 = carry_6 ^ x[5];  // cx[5]
                cy_5 = carry_6 ^ y[5];  // cy[5]
                cy_5_p = cy_5.zero_add(triples[57].b);  // cy[5]', mask=b57
                // and_231: a57=triples[57].a, b57=triples[57].b, c57=triples[57].c, output mask=((a58-f(x[4]))-(a57-f(x[5])))
                carry_t_5 = cx_5.prepare_and(cy_5_p, FUNC_XOR(FUNC_XOR(triples[58].a, x[4].get_mask()), FUNC_XOR(triples[57].a, x[5].get_mask())), triples[57].c);  // and_231
                break;
            case 59:
                carry_t_5.complete_and();
                carry_5 = carry_t_5 ^ carry_6;  // carry[5]
                cx_4 = carry_5 ^ x[4];  // cx[4]
                cy_4 = carry_5 ^ y[4];  // cy[4]
                cy_4_p = cy_4.zero_add(triples[58].b);  // cy[4]', mask=b58
                // and_235: a58=triples[58].a, b58=triples[58].b, c58=triples[58].c, output mask=((a59-f(x[3]))-(a58-f(x[4])))
                carry_t_4 = cx_4.prepare_and(cy_4_p, FUNC_XOR(FUNC_XOR(triples[59].a, x[3].get_mask()), FUNC_XOR(triples[58].a, x[4].get_mask())), triples[58].c);  // and_235
                break;
            case 60:
                carry_t_4.complete_and();
                carry_4 = carry_t_4 ^ carry_5;  // carry[4]
                cx_3 = carry_4 ^ x[3];  // cx[3]
                cy_3 = carry_4 ^ y[3];  // cy[3]
                cy_3_p = cy_3.zero_add(triples[59].b);  // cy[3]', mask=b59
                // and_239: a59=triples[59].a, b59=triples[59].b, c59=triples[59].c, output mask=((a60-f(x[2]))-(a59-f(x[3])))
                carry_t_3 = cx_3.prepare_and(cy_3_p, FUNC_XOR(FUNC_XOR(triples[60].a, x[2].get_mask()), FUNC_XOR(triples[59].a, x[3].get_mask())), triples[59].c);  // and_239
                break;
            case 61:
                carry_t_3.complete_and();
                carry_3 = carry_t_3 ^ carry_4;  // carry[3]
                cx_2 = carry_3 ^ x[2];  // cx[2]
                cy_2 = carry_3 ^ y[2];  // cy[2]
                cy_2_p = cy_2.zero_add(triples[60].b);  // cy[2]', mask=b60
                // and_243: a60=triples[60].a, b60=triples[60].b, c60=triples[60].c, output mask=((a61-f(x[1]))-(a60-f(x[2])))
                carry_t_2 = cx_2.prepare_and(cy_2_p, FUNC_XOR(FUNC_XOR(triples[61].a, x[1].get_mask()), FUNC_XOR(triples[60].a, x[2].get_mask())), triples[60].c);  // and_243
                break;
            case 62:
                carry_t_2.complete_and();
                carry_2 = carry_t_2 ^ carry_3;  // carry[2]
                cx_1 = carry_2 ^ x[1];  // cx[1]
                cy_1 = carry_2 ^ y[1];  // cy[1]
                cy_1_p = cy_1.zero_add(triples[61].b);  // cy[1]', mask=b61
                // and_247: a61=triples[61].a, b61=triples[61].b, c61=triples[61].c, output mask=r125
                carry_t_1 = cx_1.prepare_and(cy_1_p, r125, triples[61].c);  // and_247
                break;
            case 63:
                carry_t_1.complete_and();
                carry_1 = carry_t_1 ^ carry_2;  // carry[1]
                msb = t_xy_msb ^ carry_1;  // msb
                break;
        }
        level++;
    }
};

#include "narrow64/rca_msb_and_a_ab.hpp"  // CUT_FRACTIONAL_BITS_OPT at 64 bits
