FUNCTION_IDENTIFIER=87,187,287
MODELOWNER=P_0,-1
DATAOWNER=P_1,-1
BITLENGTH=32
DATTYPE=32
NUM_INPUTS=1
FRACTIONAL=5
PROTOCOL=4
PRE=1
SKIP_PRE=0,1
LIVE=0
OPTIMIZED_BIT_INJECTION_RELU=1
BIT_INJECTION_PREPROCESSING_OPT=1
A_KNOWN_TO_EVALUATORS_OPT=0,1
A2B_ONLINE_OPT=0,1
FUSE_RELU_AVG=0,1
FUSE_CONV_BN=0,1
COMPRESS=0,1
ROT_PREPROCESSING_OPT=0,1
CHEETAH_BOOL_OT_TYPE=0,2
CHEETAH_THREADS=32
PUBLIC_WEIGHTS=0,1
A_KNOWN=0,1
WEIGHT_SHARING_OPT_SIM=0,1
RESHARE_OPT=0,1
MODELWEIGHTS_KNOWN_DURING_PREPROCESSING_OPT=0,1
RESHARE_OPT=0,1
RESHARE_OPT_SIM=0,1
TRUNC_DELAYED=0,1
BIT_INJECTION_TRUNC_SIM=0,1
